ADuCM350BBCZ Device Drivers API Reference Manual: AFE Library
AFE Library
Macros
#define ASSERT_ADI_MISRA_SUPPRESSIONS
#define ASSERT_ADI_MISRA_SUPPRESSIONS
#define REVERT_ADI_MISRA_SUPPRESSIONS
#define REVERT_ADI_MISRA_SUPPRESSIONS
#define SEQ_MMR_WRITE(addr, data) (0x80000000 | ((addr & 0xFC) << 23) | data)
Typedefs
typedef struct
ADI_AFE_DEV_DATA_TYPE * ADI_AFE_DEV_HANDLE
Enumerations
enum ADI_AFE_ADC_GAIN_OFFS_TYPE {
ADI_AFE_ADC_GAIN_OFFS_TIA = 0,
ADI_AFE_ADC_GAIN_OFFS_TEMP_SENS = 1,
ADI_AFE_ADC_GAIN_OFFS_AUX = 2,
ADI_AFE_ADC_GAIN_OFFS_BYPASS = 3
}
enum ADI_AFE_ADC_MUX_SEL_TYPE {
ADI_AFE_ADC_MUX_SEL_FLOATING = 0,
ADI_AFE_ADC_MUX_SEL_TIA = 2,
ADI_AFE_ADC_MUX_SEL_INTERNAL_TEMP_SENS = 3,
ADI_AFE_ADC_MUX_SEL_AN_A = 8,
ADI_AFE_ADC_MUX_SEL_AN_B = 9,
ADI_AFE_ADC_MUX_SEL_AN_C = 10,
ADI_AFE_ADC_MUX_SEL_AN_D = 11,
ADI_AFE_ADC_MUX_SEL_AN_VEXCITE = 12,
ADI_AFE_ADC_MUX_SEL_HALF_DVDD_MINUS_VBIAS = 13,
ADI_AFE_ADC_MUX_SEL_HALF_AVDDTX_MINUS_VBIAS = 14,
ADI_AFE_ADC_MUX_SEL_HALF_AVDDRX_MINUS_VBIAS = 15,
ADI_AFE_ADC_MUX_SEL_HALF_VCCM_ANA_MINUS_VBIAS = 16,
ADI_AFE_ADC_MUX_SEL_HALF_VCCM_DIG_MINUS_VBIAS = 17,
ADI_AFE_ADC_MUX_SEL_HALF_VBACK_MINUS_VBIAS = 18,
ADI_AFE_ADC_MUX_SEL_CAL_ADC_OFFSET_TIA = 24,
ADI_AFE_ADC_MUX_SEL_CAL_ADC_GAIN_TIA_TEMP_SENS = 25,
ADI_AFE_ADC_MUX_SEL_CAL_ADC_OFFSET_TEMP_SENS = 26,
ADI_AFE_ADC_MUX_SEL_CAL_ADC_OFFSET_AUX = 28,
ADI_AFE_ADC_MUX_SEL_CAL_ADC_GAIN_AUX = 29,
ADI_AFE_ADC_MUX_SEL_CAL_P_N_AUTOCAL = 30
}
enum ADI_AFE_CAL_REG_TYPE {
ADI_AFE_CAL_REG_ADC_GAIN_TIA = REG_AFE_AFE_ADC_GAIN_TIA,
ADI_AFE_CAL_REG_ADC_OFFSET_TIA = REG_AFE_AFE_ADC_OFFSET_TIA,
ADI_AFE_CAL_REG_ADC_GAIN_TEMP_SENS = REG_AFE_AFE_ADC_GAIN_TEMP_SENS,
ADI_AFE_CAL_REG_ADC_OFFSET_TEMP_SENS = REG_AFE_AFE_ADC_OFFSET_TEMP_SENS,
ADI_AFE_CAL_REG_ADC_GAIN_AUX = REG_AFE_AFE_ADC_GAIN_AUX,
ADI_AFE_CAL_REG_ADC_OFFSET_AUX = REG_AFE_AFE_ADC_OFFSET_AUX,
ADI_AFE_CAL_REG_DAC_OFFSET_UNITY = REG_AFE_AFE_DAC_OFFSET_UNITY,
ADI_AFE_CAL_REG_DAC_OFFSET_ATTEN = REG_AFE_AFE_DAC_OFFSET_ATTEN,
ADI_AFE_CAL_REG_DAC_GAIN = REG_AFE_AFE_DAC_GAIN,
ADI_AFE_CAL_REG_REF_TRIM0 = REG_AFE_AFE_REF_TRIM0,
ADI_AFE_CAL_REG_REF_TRIM1 = REG_AFE_AFE_REF_TRIM1,
ADI_AFE_CAL_REG_ALDO_TRIM = REG_AFE_AFE_ALDO_TRIM,
ADI_AFE_CAL_REG_DAC_TRIM = REG_AFE_AFE_DAC_TRIM,
ADI_AFE_CAL_REG_INAMP_TRIM = REG_AFE_AFE_INAMP_TRIM,
ADI_AFE_CAL_REG_EXBUF_TRIM = REG_AFE_AFE_EXBUF_TRIM,
ADI_AFE_CAL_REG_TEMP_SENS_TRIM = REG_AFE_AFE_TEMP_SENS_TRIM
}
enum ADI_AFE_DATA_FIFO_SOURCE_TYPE {
ADI_AFE_DATA_FIFO_SOURCE_ADC = 0,
ADI_AFE_DATA_FIFO_SOURCE_DFT = 2,
ADI_AFE_DATA_FIFO_SOURCE_LPF = 3
}
enum ADI_AFE_INT_GROUP_TYPE {
ADI_AFE_INT_GROUP_CAPTURE = 1,
ADI_AFE_INT_GROUP_GENERATE,
ADI_AFE_INT_GROUP_CMD_FIFO,
ADI_AFE_INT_GROUP_DATA_FIFO
}
enum ADI_AFE_RESULT_TYPE {
ADI_AFE_SUCCESS = 0,
ADI_AFE_ERR_UNKNOWN = ADI_DEV_AFE_ERROR_OFFSET,
ADI_AFE_ERR_BAD_DEV_HANDLE = ADI_DEV_AFE_ERROR_OFFSET + 1,
ADI_AFE_ERR_NOT_INITIALIZED = ADI_DEV_AFE_ERROR_OFFSET + 2,
ADI_AFE_ERR_ALREADY_INITIALIZED = ADI_DEV_AFE_ERROR_OFFSET + 3,
ADI_AFE_ERR_ACLKOFF = ADI_DEV_AFE_ERROR_OFFSET + 4,
ADI_AFE_ERR_WRONG_ACLK_FREQUENCY = ADI_DEV_AFE_ERROR_OFFSET + 5,
ADI_AFE_ERR_SEQ = ADI_DEV_AFE_ERROR_OFFSET + 6,
ADI_AFE_ERR_CMD_FIFO_UDF = ADI_DEV_AFE_ERROR_OFFSET + 7,
ADI_AFE_ERR_CMD_FIFO_OVF = ADI_DEV_AFE_ERROR_OFFSET + 8,
ADI_AFE_ERR_DATA_FIFO_UDF = ADI_DEV_AFE_ERROR_OFFSET + 9,
ADI_AFE_ERR_DATA_FIFO_OVF = ADI_DEV_AFE_ERROR_OFFSET + 10,
ADI_AFE_ERR_DMA = ADI_DEV_AFE_ERROR_OFFSET + 11,
ADI_AFE_ERR_CRC = ADI_DEV_AFE_ERROR_OFFSET + 12,
ADI_AFE_ERR_CALLBACK_OVERWRITE = ADI_DEV_AFE_ERROR_OFFSET + 13,
ADI_AFE_ERR_SEQ_ALREADY_INITIALIZED = ADI_DEV_AFE_ERROR_OFFSET + 14,
ADI_AFE_ERR_SEQ_NOT_DISABLED = ADI_DEV_AFE_ERROR_OFFSET + 15,
ADI_AFE_ERR_SEQ_CHECK = ADI_DEV_AFE_ERROR_OFFSET + 16,
ADI_AFE_ERR_SEMAPHORE_FAILED = ADI_DEV_AFE_ERROR_OFFSET + 17,
ADI_AFE_ERR_PARAM_OUT_OF_RANGE = ADI_DEV_AFE_ERROR_OFFSET + 18,
ADI_AFE_ERR_RX_DMA_SIZE_TOO_BIG = ADI_DEV_AFE_ERROR_OFFSET + 19,
ADI_AFE_ERR_SEQ_ABORT_REQUEST = ADI_DEV_AFE_ERROR_OFFSET + 20,
ADI_AFE_ERR_FCW_OUT_OF_RANGE = ADI_DEV_AFE_ERROR_OFFSET + 21,
ADI_AFE_ERR_INVALID_IRQ = ADI_DEV_AFE_ERROR_OFFSET + 22,
ADI_AFE_ERR_INVALID_WG_MODE = ADI_DEV_AFE_ERROR_OFFSET + 23,
ADI_AFE_ERR_INVALID_DATA_FIFO_SRC = ADI_DEV_AFE_ERROR_OFFSET + 24
}
enum ADI_AFE_SEQ_STATE_TYPE {
ADI_AFE_SEQ_STATE_IDLE,
ADI_AFE_SEQ_STATE_WAITING_FOR_CMD_FIFO,
ADI_AFE_SEQ_STATE_INITIALIZED,
ADI_AFE_SEQ_STATE_RUNNING,
ADI_AFE_SEQ_STATE_FINISHED
}
enum ADI_AFE_WAVEGEN_TYPE {
ADI_AFE_WAVEGEN_DIRECT = 0,
ADI_AFE_WAVEGEN_SINUSOID = 2,
ADI_AFE_WAVEGEN_TRAPEZOID = 3
}
Functions
ADI_AFE_RESULT_TYPE adi_AFE_AcMeas (ADI_AFE_DEV_HANDLE const hDevice, uint32_t fcw, uint16_t amplitude, bool_t atten, uint16_t swState, int16_t *dftResults)
AC measurement example with programmable frequency, amplitude, attenuator and switch matrix states.
ADI_AFE_RESULT_TYPE adi_AFE_AcMeas10khz (ADI_AFE_DEV_HANDLE const hDevice, int16_t *dftResults)
AC measurement example using fixed excitation.
ADI_AFE_RESULT_TYPE adi_AFE_AuxChanCal (ADI_AFE_DEV_HANDLE const hDevice)
Aux channel calibration.
ADI_AFE_RESULT_TYPE adi_AFE_AuxChanMeasCustom (ADI_AFE_DEV_HANDLE const hDevice, uint32_t muxChannel, uint16_t *measResult)
Aux channel measurement on specified aux channel.
ADI_AFE_RESULT_TYPE adi_AFE_AuxChanMeasFixed (ADI_AFE_DEV_HANDLE const hDevice, int32_t *measResult)
Aux Channel Measurement with a voltage conversion.
ADI_AFE_RESULT_TYPE adi_AFE_ClearInterruptSource (ADI_AFE_DEV_HANDLE const hDevice, ADI_AFE_INT_GROUP_TYPE group, uint32_t mask)
Clear interrupt sticky bits.
ADI_AFE_RESULT_TYPE adi_AFE_DcMeas (ADI_AFE_DEV_HANDLE const hDevice, uint16_t *measBuffer, uint16_t measBufferLength)
DC measurement example using trapezoid excitation.
ADI_AFE_RESULT_TYPE adi_AFE_EnableInterruptSource (ADI_AFE_DEV_HANDLE const hDevice, ADI_AFE_INT_GROUP_TYPE group, uint32_t mask, bool_t bFlag)
Enable interrupt sources inside the AFE.
ADI_AFE_RESULT_TYPE adi_AFE_EnableSoftwareCRC (ADI_AFE_DEV_HANDLE const hDevice, const bool_t bFlag)
Enable software CRC calculation.
ADI_AFE_RESULT_TYPE adi_AFE_ExciteChanCalAtten (ADI_AFE_DEV_HANDLE const hDevice)
Excitation channel calibration with attenuator enabled.
ADI_AFE_RESULT_TYPE adi_AFE_ExciteChanCalNoAtten (ADI_AFE_DEV_HANDLE const hDevice)
Excitation channel calibration with attenuator disabled.
ADI_AFE_RESULT_TYPE adi_AFE_ExciteChanNoAttenDeltaDacCode (ADI_AFE_DEV_HANDLE const hDevice, uint32_t *pExciteChanNoAttenDeltaDacCode)
Returns the DAC code delta required for the excitation channel (no attenuation) calibration.
ADI_AFE_RESULT_TYPE adi_AFE_ExciteChanPowerUp (ADI_AFE_DEV_HANDLE const hDevice)
Power up the excitation channel.
ADI_AFE_RESULT_TYPE adi_AFE_GetCmdFifoReady (ADI_AFE_DEV_HANDLE const hDevice, bool_t *pbFlag)
Returns the status of the command FIFO ready flag.
ADI_AFE_RESULT_TYPE adi_AFE_GetLowPowerModeFlag (ADI_AFE_DEV_HANDLE const hDevice, bool_t *pbFlag)
Gets the flag for low power mode.
ADI_AFE_RESULT_TYPE adi_AFE_GetRcal (ADI_AFE_DEV_HANDLE const hDevice, uint32_t *pRcal)
Get the RCAL value.
ADI_AFE_RESULT_TYPE adi_AFE_GetRtia (ADI_AFE_DEV_HANDLE const hDevice, uint32_t *pRtia)
Get the RTIA value.
ADI_AFE_RESULT_TYPE adi_AFE_GetRunSequenceBlockingMode (ADI_AFE_DEV_HANDLE const hDevice, bool_t *const pbFlag)
Get the status of the RunSequence blocking mode flag.
ADI_AFE_RESULT_TYPE adi_AFE_GetRxDmaComplete (ADI_AFE_DEV_HANDLE const hDevice, bool_t *pbFlag)
Returns the status of Rx DMA complete flag.
ADI_AFE_RESULT_TYPE adi_AFE_GetSeqError (ADI_AFE_DEV_HANDLE const hDevice)
Returns the current sequencer error code.
ADI_AFE_RESULT_TYPE adi_AFE_GetSeqFinished (ADI_AFE_DEV_HANDLE const hDevice, bool_t *pbFlag)
Returns the status of the sequencer finished flag.
ADI_AFE_RESULT_TYPE adi_AFE_GetSeqState (ADI_AFE_DEV_HANDLE const hDevice, ADI_AFE_SEQ_STATE_TYPE *const pState)
Returns the sequencer state.
ADI_AFE_RESULT_TYPE adi_AFE_HandleNotInitialized (ADI_AFE_DEV_HANDLE const hDevice)
Checks if the AFE device is not initialized.
ADI_AFE_RESULT_TYPE adi_AFE_Init (ADI_AFE_DEV_HANDLE *const phDevice)
Initialize the AFE device.
ADI_AFE_RESULT_TYPE adi_AFE_InvalidHandle (ADI_AFE_DEV_HANDLE const hDevice)
Checks if the AFE device is valid.
ADI_AFE_RESULT_TYPE adi_AFE_PowerDown (ADI_AFE_DEV_HANDLE const hDevice)
Power down the AFE.
ADI_AFE_RESULT_TYPE adi_AFE_PowerUp (ADI_AFE_DEV_HANDLE const hDevice)
Power up the AFE.
ADI_AFE_RESULT_TYPE adi_AFE_ProgramRxDMA (ADI_AFE_DEV_HANDLE const hDevice, uint16_t *buffer, uint32_t length)
Program the Rx DMA channel.
ADI_AFE_RESULT_TYPE adi_AFE_ProgramTxDMA (ADI_AFE_DEV_HANDLE const hDevice, const uint32_t *const buffer, uint32_t length)
Program the Tx DMA channel.
ADI_AFE_RESULT_TYPE adi_AFE_ReadCalibrationRegister (ADI_AFE_DEV_HANDLE const hDevice, ADI_AFE_CAL_REG_TYPE Reg, uint32_t *pVal)
Read from a calibration register.
ADI_AFE_RESULT_TYPE adi_AFE_RegisterAfeCallback (ADI_AFE_DEV_HANDLE hDevice, ADI_AFE_INT_GROUP_TYPE group, ADI_CALLBACK cbFunc, uint32_t cbWatch)
Application callback registration for AFE interrupt handlers.
ADI_AFE_RESULT_TYPE adi_AFE_RegisterCallbackOnReceiveDMA (ADI_AFE_DEV_HANDLE hDevice, ADI_CALLBACK cbFunc, uint32_t cbWatch)
Application callback registration for the AFE receive DMA done interrupt handler.
ADI_AFE_RESULT_TYPE adi_AFE_RegisterCallbackOnTransmitDMA (ADI_AFE_DEV_HANDLE hDevice, ADI_CALLBACK cbFunc, uint32_t cbWatch)
Application callback registration for the AFE transmit DMA done interrupt handler.
ADI_AFE_RESULT_TYPE adi_AFE_RunSequence (ADI_AFE_DEV_HANDLE const hDevice, const uint32_t *const txBuffer, uint16_t *const rxBuffer, uint32_t size)
Run a sequence.
ADI_AFE_RESULT_TYPE adi_AFE_SeqAbort (ADI_AFE_DEV_HANDLE const hDevice)
Abort the sequencer.
ADI_AFE_RESULT_TYPE adi_AFE_SeqCheck (ADI_AFE_DEV_HANDLE const hDevice, const uint32_t *const txBuffer)
Check the sequencer execution was successful.
ADI_AFE_RESULT_TYPE adi_AFE_SeqInit (ADI_AFE_DEV_HANDLE const hDevice, const uint32_t *const txBuffer, uint16_t *const rxBuffer, uint32_t size)
Initialize the hardware needed for running the sequencer.
ADI_AFE_RESULT_TYPE adi_AFE_SeqStart (ADI_AFE_DEV_HANDLE const hDevice)
Start the sequencer.
ADI_AFE_RESULT_TYPE adi_AFE_SeqStop (ADI_AFE_DEV_HANDLE const hDevice)
Stop the sequencer.
ADI_AFE_RESULT_TYPE adi_AFE_SetDataFifoSource (ADI_AFE_DEV_HANDLE const hDevice, ADI_AFE_DATA_FIFO_SOURCE_TYPE sel)
Select the input source for the data FIFO.
ADI_AFE_RESULT_TYPE adi_AFE_SetLowPowerModeFlag (ADI_AFE_DEV_HANDLE const hDevice, bool_t *pbFlag)
Sets the flag for low power mode.
ADI_AFE_RESULT_TYPE adi_AFE_SetRcal (ADI_AFE_DEV_HANDLE const hDevice, uint32_t rcal)
Set the RCAL value.
ADI_AFE_RESULT_TYPE adi_AFE_SetRtia (ADI_AFE_DEV_HANDLE const hDevice, uint32_t rtia)
Set the RTIA value.
ADI_AFE_RESULT_TYPE adi_AFE_SetRunSequenceBlockingMode (ADI_AFE_DEV_HANDLE const hDevice, const bool_t bFlag)
Set the status of the RunSequence blocking mode flag.
ADI_AFE_RESULT_TYPE adi_AFE_SetSeqError (ADI_AFE_DEV_HANDLE const hDevice, ADI_AFE_RESULT_TYPE const error)
Sets the current sequencer error code.
ADI_AFE_RESULT_TYPE adi_AFE_SetSeqState (ADI_AFE_DEV_HANDLE const hDevice, ADI_AFE_SEQ_STATE_TYPE seqState)
Sets the sequencer state.
ADI_AFE_RESULT_TYPE adi_AFE_SetSwitchState (ADI_AFE_DEV_HANDLE const hDevice, uint32_t state)
Program the switch matrix.
ADI_AFE_RESULT_TYPE adi_AFE_SetWavegenType (ADI_AFE_DEV_HANDLE const hDevice, ADI_AFE_WAVEGEN_TYPE sel)
Select the waveform type.
ADI_AFE_RESULT_TYPE adi_AFE_TempSensChanCal (ADI_AFE_DEV_HANDLE const hDevice)
Temperature sensor channel calibration.
ADI_AFE_RESULT_TYPE adi_AFE_TempSensMeas (ADI_AFE_DEV_HANDLE const hDevice, int32_t *tdegc)
Temperature measurement.
ADI_AFE_RESULT_TYPE adi_AFE_TiaChanCal (ADI_AFE_DEV_HANDLE const hDevice)
TIA channel calibration.
ADI_AFE_RESULT_TYPE adi_AFE_TiaChanDacCode (ADI_AFE_DEV_HANDLE const hDevice, uint32_t *pTiaChanDacCode)
Returns the DAC code required for the TIA channel calibration.
ADI_AFE_RESULT_TYPE adi_AFE_UnInit (ADI_AFE_DEV_HANDLE const hDevice)
Uninitialize the AFE device.
ADI_AFE_RESULT_TYPE adi_AFE_WriteCalibrationRegister (ADI_AFE_DEV_HANDLE const hDevice, ADI_AFE_CAL_REG_TYPE Reg, uint32_t Val)
Write to a calibration register.
Variables
const uint32_t seq_afe_acmeas10khz []
const uint32_t seq_afe_auxchancal []
const uint32_t seq_afe_auxchanmeas1 []
const uint32_t seq_afe_auxchanmeas2 []
const uint32_t seq_afe_dcmeas []
const uint32_t seq_afe_excitechancalatten1 []
const uint32_t seq_afe_excitechancalatten2 []
const uint32_t seq_afe_excitechancalnoatten1 []
const uint32_t seq_afe_excitechancalnoatten2 []
const uint32_t seq_afe_excitechanpowerup []
const uint32_t seq_afe_powerup []
const uint32_t seq_afe_tempsenschancal []
const uint32_t seq_afe_tempsensmeas []
const uint32_t seq_afe_tiachancal1 []
const uint32_t seq_afe_tiachancal2 []
const uint32_t seq_afe_tiachancal3 []
const uint32_t seq_afe_tiachancal4 []
const uint32_t seq_afe_tiachancal5 []
Detailed Description
Macro Definition Documentation
#define ASSERT_ADI_MISRA_SUPPRESSIONS
Apply ADI MISRA Suppressions
Definition at line 5 of file afe_lib.c.
#define ASSERT_ADI_MISRA_SUPPRESSIONS
Apply ADI MISRA Suppressions
Definition at line 6 of file afe.c.
#define REVERT_ADI_MISRA_SUPPRESSIONS
Revert ADI MISRA Suppressions
Definition at line 1131 of file afe_lib.c.
#define REVERT_ADI_MISRA_SUPPRESSIONS
Revert ADI MISRA Suppressions
Definition at line 3177 of file afe.c.
Typedef Documentation
typedef struct ADI_AFE_DEV_DATA_TYPE* ADI_AFE_DEV_HANDLE
AFE Device instance private data handle typedef.
Definition at line 194 of file afe.h.
Enumeration Type Documentation
enum ADI_AFE_ADC_GAIN_OFFS_TYPE
Gain and offset selection for ADC. Corresponds to field GAIN_OFFS_SEL in register AFE_ADC_CFG.
Definition at line 187 of file afe.h.
enum ADI_AFE_ADC_MUX_SEL_TYPE
Select signals for the ADC input multiplexer. Corresponds to field MUX_SEL in register AFE_ADC_CFG.
Definition at line 155 of file afe.h.
enum ADI_AFE_CAL_REG_TYPE
Calibration registers.
Definition at line 112 of file afe.h.
enum ADI_AFE_DATA_FIFO_SOURCE_TYPE
AFE data FIFO source select. Corresponds to field DATA_FIFO_SOURCE_SEL in register AFE_FIFO_CFG.
Definition at line 83 of file afe.h.
enum ADI_AFE_INT_GROUP_TYPE
Interrupt groups, each one corresponds to an AFE IRQ.
Definition at line 139 of file afe.h.
enum ADI_AFE_RESULT_TYPE
AFE error codes.
Enumerator
ADI_AFE_SUCCESS
Generic success.
ADI_AFE_ERR_UNKNOWN
Generic error.
ADI_AFE_ERR_BAD_DEV_HANDLE
Invalid device handle.
ADI_AFE_ERR_NOT_INITIALIZED
Device not initialized.
ADI_AFE_ERR_ALREADY_INITIALIZED
Device already initialized.
ADI_AFE_ERR_ACLKOFF
ACLK disabled from the clock gate.
ADI_AFE_ERR_WRONG_ACLK_FREQUENCY
Programmed ACLK frequency is not the required 16MHz.
ADI_AFE_ERR_SEQ
Sequencer error.
ADI_AFE_ERR_CMD_FIFO_UDF
Command FIFO underflow error.
ADI_AFE_ERR_CMD_FIFO_OVF
Command FIFO overflow error.
ADI_AFE_ERR_DATA_FIFO_UDF
Data FIFO underflow error.
ADI_AFE_ERR_DATA_FIFO_OVF
Data FIFO overflow error.
ADI_AFE_ERR_CALLBACK_OVERWRITE
Attempt to overwrite existing callback.
ADI_AFE_ERR_FCW_OUT_OF_RANGE
Waveform generator sinusoid frequency must be 80Hz - 80kHz
ADI_AFE_ERR_INVALID_IRQ
IRQ is not a valid member of the ADI_AFE_INT_GROUP_TYPE enum
ADI_AFE_ERR_INVALID_WG_MODE
Wavegen mode is not a valid member of the ADI_AFE_WAVEGEN_TYPE enum
ADI_AFE_ERR_INVALID_DATA_FIFO_SRC
Data FIFO source is not a valid member of the ADI_AFE_DATA_FIFO_SOURCE_TYPE enum
Definition at line 29 of file afe.h.
enum ADI_AFE_SEQ_STATE_TYPE
AFE sequencer status codes.
Definition at line 66 of file afe.h.
enum ADI_AFE_WAVEGEN_TYPE
AFE waveform type select. Corresponds to field TYPE_SEL in register AFE_WG_CFG.
Definition at line 98 of file afe.h.
Function Documentation
ADI_AFE_RESULT_TYPE adi_AFE_AcMeas (ADI_AFE_DEV_HANDLE const hDevice, uint32_t fcw, uint16_t amplitude, bool_t atten, uint16_t swState, int16_t * dftResults)
AC measurement example with programmable frequency, amplitude, attenuator and switch matrix states.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init(). fcw Frequency control word (Fout = Faclk * (fcw / 2^26)) amplitude Amplitude (DAC codes) atten Enable/disable attenuator (boolean) swState Set the state of the switch mux
[out] dftResults DFT result as real/imaginary pairs - Rcal first, unknown impedance second (4 results)
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
Note: the amplitude parameter is the value written into the AFE_WG_AMPLITUDE register. It does not account for the attenuator state (enabled/disabled)
Definition at line 859 of file afe_lib.c.
ADI_AFE_RESULT_TYPE adi_AFE_AcMeas10khz (ADI_AFE_DEV_HANDLE const hDevice, int16_t * dftResults)
AC measurement example using fixed excitation.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init().
[out] dftResults Real and imaginary DFT results for both Rcal and TIA measurements.
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_BAD_DEV_HANDLE Invalid device handle.
ADI_AFE_ERR_NOT_INITIALIZED Device not initialized.
ADI_AFE_ERR_ACLKOFF ACLK disabled from the clock gate.
ADI_AFE_ERR_WRONG_ACLK_FREQUENCY Programmed ACLK frequency is not the required 16MHz.
It is an implementation of step 10 in the "AFE Example Use Cases" from HRM. The conversion from real and imaginary to magnitude and phase has to be performed in the application space.
Definition at line 813 of file afe_lib.c.
ADI_AFE_RESULT_TYPE adi_AFE_AuxChanCal (ADI_AFE_DEV_HANDLE const hDevice)
Aux channel calibration.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init().
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_BAD_DEV_HANDLE Invalid device handle.
ADI_AFE_ERR_NOT_INITIALIZED Device not initialized.
ADI_AFE_ERR_ACLKOFF ACLK disabled from the clock gate.
ADI_AFE_ERR_WRONG_ACLK_FREQUENCY Programmed ACLK frequency is not the required 16MHz.
The function calibrates the ADC aux channel.
It is an implementation of step 2 in the "AFE Example Use Cases" from HRM.
Definition at line 78 of file afe_lib.c.
ADI_AFE_RESULT_TYPE adi_AFE_AuxChanMeasCustom (ADI_AFE_DEV_HANDLE const hDevice, uint32_t muxChannel, uint16_t * measResult)
Aux channel measurement on specified aux channel.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init(). muxChannel ADC Mux Channel
[out] measResult Measurement result.
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
The function performs a measurement from aux channel.
Definition at line 216 of file afe_lib.c.
ADI_AFE_RESULT_TYPE adi_AFE_AuxChanMeasFixed (ADI_AFE_DEV_HANDLE const hDevice, int32_t * measResult)
Aux Channel Measurement with a voltage conversion.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init().
[out] measResult Measurement result.
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_BAD_DEV_HANDLE Invalid device handle.
ADI_AFE_ERR_NOT_INITIALIZED Device not initialized.
ADI_AFE_ERR_ACLKOFF ACLK disabled from the clock gate.
ADI_AFE_ERR_WRONG_ACLK_FREQUENCY Programmed ACLK frequency is not the required 16MHz.
The function performs a measurement from aux channel.
It is an implementation of step 3 in the "AFE Example Use Cases" from HRM.
Definition at line 161 of file afe_lib.c.
ADI_AFE_RESULT_TYPE adi_AFE_ClearInterruptSource (ADI_AFE_DEV_HANDLE const hDevice, ADI_AFE_INT_GROUP_TYPE group, uint32_t mask)
Clear interrupt sticky bits.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init().
[in] group Interrupt group identifier.
[in] mask Interrupt group mask.
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_BAD_DEV_HANDLE Invalid device handle.
ADI_AFE_ERR_NOT_INITIALIZED Device not initialized.
ADI_AFE_ERR_ACLKOFF ACLK disabled from the clock gate.
ADI_AFE_ERR_WRONG_ACLK_FREQUENCY Programmed ACLK frequency is not the required 16MHz.
Definition at line 2695 of file afe.c.
Referenced by adi_AFE_SeqInit().
ADI_AFE_RESULT_TYPE adi_AFE_DcMeas (ADI_AFE_DEV_HANDLE const hDevice, uint16_t * measBuffer, uint16_t measBufferLength)
DC measurement example using trapezoid excitation.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init().
[in] measBufferLength Number of samples to be returned by the DC measurement function.
[out] measBuffer Pointer to the results array.
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_BAD_DEV_HANDLE Invalid device handle.
ADI_AFE_ERR_NOT_INITIALIZED Device not initialized.
ADI_AFE_ERR_ACLKOFF ACLK disabled from the clock gate.
ADI_AFE_ERR_WRONG_ACLK_FREQUENCY Programmed ACLK frequency is not the required 16MHz.
It is an implementation of step 12 in the "AFE Example Use Cases" from HRM.
Definition at line 931 of file afe_lib.c.
ADI_AFE_RESULT_TYPE adi_AFE_EnableInterruptSource (ADI_AFE_DEV_HANDLE const hDevice, ADI_AFE_INT_GROUP_TYPE group, uint32_t mask, bool_t bFlag)
Enable interrupt sources inside the AFE.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init().
[in] group Interrupt group identifier.
[in] mask Interrupt group mask.
[in] bFlag True to unmask interrupt sources, False to mask interrupt sources.
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_BAD_DEV_HANDLE Invalid device handle.
ADI_AFE_ERR_NOT_INITIALIZED Device not initialized.
ADI_AFE_ERR_ACLKOFF ACLK disabled from the clock gate.
ADI_AFE_ERR_WRONG_ACLK_FREQUENCY Programmed ACLK frequency is not the required 16MHz.
Definition at line 2618 of file afe.c.
Referenced by adi_AFE_SeqInit().
ADI_AFE_RESULT_TYPE adi_AFE_EnableSoftwareCRC (ADI_AFE_DEV_HANDLE const hDevice, const bool_t bFlag)
Enable software CRC calculation.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init().
[in] bFlag True to use software CRC False to use stored CRC values
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
Under normal circumstances, the CRC is stored in Flash together with the sequence it belongs to (hardware CRC). However, sometimes it may be needed to modify the sequence dynamically (e.g. the frequency control word in a frequency sweep), and the programmed CRC cannot verify the integrity of the sequence anymore. If the software CRC is enabled, the CRC of the current sequence is calculated on-the-fly, and the hardware CRC is ignored. Warning: using the hardware CRC can detect error such as Flash read errors, which the software CRC cannot detect. Usage of software CRC is discouraged.
Definition at line 1679 of file afe.c.
Referenced by adi_AFE_AcMeas(), adi_AFE_AuxChanMeasCustom(), and adi_AFE_TiaChanCal().
ADI_AFE_RESULT_TYPE adi_AFE_ExciteChanCalAtten (ADI_AFE_DEV_HANDLE const hDevice)
Excitation channel calibration with attenuator enabled.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init().
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_BAD_DEV_HANDLE Invalid device handle.
ADI_AFE_ERR_NOT_INITIALIZED Device not initialized.
ADI_AFE_ERR_ACLKOFF ACLK disabled from the clock gate.
ADI_AFE_ERR_WRONG_ACLK_FREQUENCY Programmed ACLK frequency is not the required 16MHz.
The function calibrates the excitation chanel when the attenuator is enabled.
It is an implementation of step 8 in the "AFE Example Use Cases" from HRM.
Definition at line 613 of file afe_lib.c.
ADI_AFE_RESULT_TYPE adi_AFE_ExciteChanCalNoAtten (ADI_AFE_DEV_HANDLE const hDevice)
Excitation channel calibration with attenuator disabled.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init().
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_BAD_DEV_HANDLE Invalid device handle.
ADI_AFE_ERR_NOT_INITIALIZED Device not initialized.
ADI_AFE_ERR_ACLKOFF ACLK disabled from the clock gate.
ADI_AFE_ERR_WRONG_ACLK_FREQUENCY Programmed ACLK frequency is not the required 16MHz.
The function calibrates the excitation chanel when the attenuator is disabled.
It is an implementation of step 9 in the "AFE Example Use Cases" from HRM.
Definition at line 710 of file afe_lib.c.
ADI_AFE_RESULT_TYPE adi_AFE_ExciteChanNoAttenDeltaDacCode (ADI_AFE_DEV_HANDLE const hDevice, uint32_t * pExciteChanNoAttenDeltaDacCode)
Returns the DAC code delta required for the excitation channel (no attenuation) calibration.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init().
[out] ExciteChanNoAttenDeltaDacCode DAC code.
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_BAD_DEV_HANDLE Invalid device handle.
ADI_AFE_ERR_NOT_INITIALIZED Device not initialized.
Excitation channel calibration codes, stored as delta from midscale. The delta value will be added and subtracted for interpolation. Calculated using the same formula as adi_AFE_TiaChanDacCode. Note: Offset has 0.5LSB resolution, left-shifting by 1
Definition at line 1099 of file afe_lib.c.
Referenced by adi_AFE_ExciteChanCalNoAtten().
ADI_AFE_RESULT_TYPE adi_AFE_ExciteChanPowerUp (ADI_AFE_DEV_HANDLE const hDevice)
Power up the excitation channel.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init().
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_BAD_DEV_HANDLE Invalid device handle.
ADI_AFE_ERR_NOT_INITIALIZED Device not initialized.
ADI_AFE_ERR_ACLKOFF ACLK disabled from the clock gate.
ADI_AFE_ERR_WRONG_ACLK_FREQUENCY Programmed ACLK frequency is not the required 16MHz.
The function powers up the excitation using the recommended timing sequence.
It is an implementation of step 6 in the "AFE Example Use Cases" from HRM.
Definition at line 395 of file afe_lib.c.
ADI_AFE_RESULT_TYPE adi_AFE_GetCmdFifoReady (ADI_AFE_DEV_HANDLE const hDevice, bool_t * pbFlag)
Returns the status of the command FIFO ready flag.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init().
[in] pbFlag True if command FIFO ready False if command FIFO not ready
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_BAD_DEV_HANDLE Invalid device handle.
ADI_AFE_ERR_NOT_INITIALIZED Device not initialized.
ADI_AFE_ERR_ACLKOFF ACLK disabled from the clock gate.
ADI_AFE_ERR_WRONG_ACLK_FREQUENCY Programmed ACLK frequency is not the required 16MHz.
Returns the status of the boolean flag that indicates that the command FIFO is ready for sequencer operation: either full, or the DMA transfer has finished because the sequence is less than 8 commands long.
Definition at line 945 of file afe.c.
ADI_AFE_RESULT_TYPE adi_AFE_GetLowPowerModeFlag (ADI_AFE_DEV_HANDLE const hDevice, bool_t * pbFlag)
Gets the flag for low power mode.
Parameters
hDevice Device handle obtained from adi_AFE_Init(). pError Error of ADI_AFE_RESULT_TYPE.
Returns
*bInterruptFlag Pointer to the flag used to enter low power mode.
Gets the value of the private flag, bInterruptFlag, used by the adi_AFE_RunSequence() function when entering low power mode. Because this flag is private, it cannot be used directly to, for example, exit low power mode from another interrupt handler.
Definition at line 1703 of file afe.c.
ADI_AFE_RESULT_TYPE adi_AFE_GetRcal (ADI_AFE_DEV_HANDLE const hDevice, uint32_t * pRcal)
Get the RCAL value.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init().
[out] Rcal Value of RCAL in ohms.
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_BAD_DEV_HANDLE Invalid device handle.
ADI_AFE_ERR_NOT_INITIALIZED Device not initialized.
Definition at line 1851 of file afe.c.
Referenced by adi_AFE_ExciteChanNoAttenDeltaDacCode(), adi_AFE_TiaChanCal(), and adi_AFE_TiaChanDacCode().
ADI_AFE_RESULT_TYPE adi_AFE_GetRtia (ADI_AFE_DEV_HANDLE const hDevice, uint32_t * pRtia)
Get the RTIA value.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init().
[out] Rtia Value of RTIA in ohms.
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_BAD_DEV_HANDLE Invalid device handle.
ADI_AFE_ERR_NOT_INITIALIZED Device not initialized.
Definition at line 1918 of file afe.c.
Referenced by adi_AFE_ExciteChanNoAttenDeltaDacCode(), adi_AFE_TiaChanCal(), and adi_AFE_TiaChanDacCode().
ADI_AFE_RESULT_TYPE adi_AFE_GetRunSequenceBlockingMode (ADI_AFE_DEV_HANDLE const hDevice, bool_t *const pbFlag)
Get the status of the RunSequence blocking mode flag.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init().
[in] pbFlag True if adi_AFE_RunSequence is to run in blocking mode False if adi_AFE_RunSequence is to run in non-blocking mode
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_BAD_DEV_HANDLE Invalid device handle.
ADI_AFE_ERR_NOT_INITIALIZED Device not initialized.
ADI_AFE_ERR_ACLKOFF ACLK disabled from the clock gate.
ADI_AFE_ERR_WRONG_ACLK_FREQUENCY Programmed ACLK frequency is not the required 16MHz.
Gets the value of the boolean flag which indicates if the adi_AFE_RunSequence function is to be run in blocking or non-blocking mode.
Definition at line 1111 of file afe.c.
ADI_AFE_RESULT_TYPE adi_AFE_GetRxDmaComplete (ADI_AFE_DEV_HANDLE const hDevice, bool_t * pbFlag)
Returns the status of Rx DMA complete flag.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init().
[in] pbFlag True if Rx DMA has completed, or Rx DMA not used False if Rx DMA has not completed
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_BAD_DEV_HANDLE Invalid device handle.
ADI_AFE_ERR_NOT_INITIALIZED Device not initialized.
ADI_AFE_ERR_ACLKOFF ACLK disabled from the clock gate.
ADI_AFE_ERR_WRONG_ACLK_FREQUENCY Programmed ACLK frequency is not the required 16MHz.
Definition at line 1032 of file afe.c.
Referenced by adi_AFE_RunSequence().
ADI_AFE_RESULT_TYPE adi_AFE_GetSeqError (ADI_AFE_DEV_HANDLE const hDevice)
Returns the current sequencer error code.
Parameters
hDevice Device handle obtained from adi_AFE_Init().
Returns
Definition at line 788 of file afe.c.
ADI_AFE_RESULT_TYPE adi_AFE_GetSeqFinished (ADI_AFE_DEV_HANDLE const hDevice, bool_t * pbFlag)
Returns the status of the sequencer finished flag.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init().
[in] pbFlag True if sequencer has finished False if sequencer has not finished
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_BAD_DEV_HANDLE Invalid device handle.
ADI_AFE_ERR_NOT_INITIALIZED Device not initialized.
ADI_AFE_ERR_ACLKOFF ACLK disabled from the clock gate.
ADI_AFE_ERR_WRONG_ACLK_FREQUENCY Programmed ACLK frequency is not the required 16MHz.
Returns the status of the boolean flag that indicates if the sequencer finished execution or not.
Definition at line 989 of file afe.c.
Referenced by adi_AFE_RunSequence().
ADI_AFE_RESULT_TYPE adi_AFE_GetSeqState (ADI_AFE_DEV_HANDLE const hDevice, ADI_AFE_SEQ_STATE_TYPE *const pState)
Returns the sequencer state.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init().
[in] pState Sequencer state of ADI_AFE_SEQ_STATE_TYPE.
Returns
Definition at line 862 of file afe.c.
ADI_AFE_RESULT_TYPE adi_AFE_HandleNotInitialized (ADI_AFE_DEV_HANDLE const hDevice)
Checks if the AFE device is not initialized.
Parameters
hDevice Device handle obtained from adi_AFE_Init().
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_NOT_INITIALIZED Device not initialized.
Definition at line 1791 of file afe.c.
Referenced by adi_AFE_AcMeas(), adi_AFE_AcMeas10khz(), adi_AFE_AuxChanCal(), adi_AFE_AuxChanMeasFixed(), adi_AFE_ClearInterruptSource(), adi_AFE_DcMeas(), adi_AFE_EnableInterruptSource(), adi_AFE_ExciteChanCalAtten(), adi_AFE_ExciteChanCalNoAtten(), adi_AFE_ExciteChanNoAttenDeltaDacCode(), adi_AFE_ExciteChanPowerUp(), adi_AFE_GetCmdFifoReady(), adi_AFE_GetLowPowerModeFlag(), adi_AFE_GetRcal(), adi_AFE_GetRtia(), adi_AFE_GetRunSequenceBlockingMode(), adi_AFE_GetRxDmaComplete(), adi_AFE_GetSeqError(), adi_AFE_GetSeqFinished(), adi_AFE_GetSeqState(), adi_AFE_Init(), adi_AFE_PowerDown(), adi_AFE_PowerUp(), adi_AFE_ProgramRxDMA(), adi_AFE_ProgramTxDMA(), adi_AFE_ReadCalibrationRegister(), adi_AFE_RegisterAfeCallback(), adi_AFE_RegisterCallbackOnReceiveDMA(), adi_AFE_RegisterCallbackOnTransmitDMA(), adi_AFE_RunSequence(), adi_AFE_SeqAbort(), adi_AFE_SeqCheck(), adi_AFE_SeqInit(), adi_AFE_SeqStart(), adi_AFE_SeqStop(), adi_AFE_SetDataFifoSource(), adi_AFE_SetLowPowerModeFlag(), adi_AFE_SetRcal(), adi_AFE_SetRtia(), adi_AFE_SetRunSequenceBlockingMode(), adi_AFE_SetSeqError(), adi_AFE_SetSeqState(), adi_AFE_SetSwitchState(), adi_AFE_SetWavegenType(), adi_AFE_TempSensChanCal(), adi_AFE_TempSensMeas(), adi_AFE_TiaChanCal(), adi_AFE_TiaChanDacCode(), adi_AFE_UnInit(), and adi_AFE_WriteCalibrationRegister().
ADI_AFE_RESULT_TYPE adi_AFE_Init (ADI_AFE_DEV_HANDLE *const phDevice)
Initialize the AFE device.
Parameters
[in] phDevice Pointer to the new device handle.
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_ALREADY_INITIALIZED Device already initialized.
ADI_AFE_ERR_BAD_DEV_HANDLE Invalid device handle.
ADI_AFE_ERR_ACLKOFF ACLK disabled from the clock gate.
ADI_AFE_ERR_WRONG_ACLK_FREQUENCY Programmed ACLK frequency is not the required 16MHz.
ADI_AFE_ERR_CALLBACK_OVERWRITE Attempt to overwrite existing callback.
Initializes the AFE for the first use. The function will enable the AFE clock (ACLK), initialize DMA channels, enable AFE interrupts, and reset the interrupt callbacks.
Note
The function does not require an ACLK frequency of 16MHz and can be called before the ALCK frequency is setup. An ACLK frequency of 16MHz is required for all AFE functions.
See Also
adi_AFE_UnInit()
Definition at line 2421 of file afe.c.
ADI_AFE_RESULT_TYPE adi_AFE_InvalidHandle (ADI_AFE_DEV_HANDLE const hDevice)
Checks if the AFE device is valid.
Parameters
hDevice Device handle obtained from adi_AFE_Init().
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_BAD_DEV_HANDLE Invalid device handle.
Definition at line 1767 of file afe.c.
Referenced by adi_AFE_AcMeas(), adi_AFE_AcMeas10khz(), adi_AFE_AuxChanCal(), adi_AFE_AuxChanMeasFixed(), adi_AFE_ClearInterruptSource(), adi_AFE_DcMeas(), adi_AFE_EnableInterruptSource(), adi_AFE_ExciteChanCalAtten(), adi_AFE_ExciteChanCalNoAtten(), adi_AFE_ExciteChanNoAttenDeltaDacCode(), adi_AFE_ExciteChanPowerUp(), adi_AFE_GetCmdFifoReady(), adi_AFE_GetLowPowerModeFlag(), adi_AFE_GetRcal(), adi_AFE_GetRtia(), adi_AFE_GetRunSequenceBlockingMode(), adi_AFE_GetRxDmaComplete(), adi_AFE_GetSeqError(), adi_AFE_GetSeqFinished(), adi_AFE_GetSeqState(), adi_AFE_PowerDown(), adi_AFE_PowerUp(), adi_AFE_ProgramRxDMA(), adi_AFE_ProgramTxDMA(), adi_AFE_ReadCalibrationRegister(), adi_AFE_RegisterAfeCallback(), adi_AFE_RegisterCallbackOnReceiveDMA(), adi_AFE_RegisterCallbackOnTransmitDMA(), adi_AFE_RunSequence(), adi_AFE_SeqAbort(), adi_AFE_SeqCheck(), adi_AFE_SeqInit(), adi_AFE_SeqStart(), adi_AFE_SeqStop(), adi_AFE_SetDataFifoSource(), adi_AFE_SetLowPowerModeFlag(), adi_AFE_SetRcal(), adi_AFE_SetRtia(), adi_AFE_SetRunSequenceBlockingMode(), adi_AFE_SetSeqError(), adi_AFE_SetSeqState(), adi_AFE_SetSwitchState(), adi_AFE_SetWavegenType(), adi_AFE_TempSensChanCal(), adi_AFE_TempSensMeas(), adi_AFE_TiaChanCal(), adi_AFE_TiaChanDacCode(), adi_AFE_UnInit(), and adi_AFE_WriteCalibrationRegister().
ADI_AFE_RESULT_TYPE adi_AFE_PowerDown (ADI_AFE_DEV_HANDLE const hDevice)
Power down the AFE.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init().
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_BAD_DEV_HANDLE Invalid device handle.
ADI_AFE_ERR_NOT_INITIALIZED Device not initialized.
ADI_AFE_ERR_ACLKOFF ACLK disabled from the clock gate.
ADI_AFE_ERR_WRONG_ACLK_FREQUENCY Programmed ACLK frequency is not the required 16MHz.
The function powers down the AFE. It uses Cortex writes instead of sequencer because accurate timing is not required.
It is an implementation of step 13 in the "AFE Example Use Cases" from HRM. It can be implemented as a sequence, but since it has no strict timing requirements it's easier to write to registers directly, and avoid the sequencer overhead.
Definition at line 977 of file afe_lib.c.
ADI_AFE_RESULT_TYPE adi_AFE_PowerUp (ADI_AFE_DEV_HANDLE const hDevice)
Power up the AFE.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init().
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_BAD_DEV_HANDLE Invalid device handle.
ADI_AFE_ERR_NOT_INITIALIZED Device not initialized.
ADI_AFE_ERR_ACLKOFF ACLK disabled from the clock gate.
ADI_AFE_ERR_WRONG_ACLK_FREQUENCY Programmed ACLK frequency is not the required 16MHz.
The function powers up the AFE using the recommended timing sequence.
It is an implementation of step 1 in the "AFE Example Use Cases" from HRM.
Definition at line 33 of file afe_lib.c.
ADI_AFE_RESULT_TYPE adi_AFE_ProgramRxDMA (ADI_AFE_DEV_HANDLE const hDevice, uint16_t * buffer, uint32_t length)
Program the Rx DMA channel.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init().
[in] buffer Pointer to the array of words to be written through the Rx DMA channel
[in] length Buffer size expressed as number of halfwords
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_BAD_DEV_HANDLE Invalid device handle.
ADI_AFE_ERR_NOT_INITIALIZED Device not initialized.
ADI_AFE_ERR_ACLKOFF ACLK disabled from the clock gate.
ADI_AFE_ERR_WRONG_ACLK_FREQUENCY Programmed ACLK frequency is not the required 16MHz.
The function programs the DMA Rx channel.
Note
If the <buffer> parameter is NULL, the function will reprogram the Rx DMA channel with the same parameters as the previous transfer.
Definition at line 700 of file afe.c.
Referenced by adi_AFE_SeqInit().
ADI_AFE_RESULT_TYPE adi_AFE_ProgramTxDMA (ADI_AFE_DEV_HANDLE const hDevice, const uint32_t *const buffer, uint32_t length)
Program the Tx DMA channel.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init().
[in] buffer Pointer to the array of words to be sent through the Tx DMA channel.
[in] length Buffer size expressed as number of words
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_BAD_DEV_HANDLE Invalid device handle.
ADI_AFE_ERR_NOT_INITIALIZED Device not initialized.
ADI_AFE_ERR_ACLKOFF ACLK disabled from the clock gate.
ADI_AFE_ERR_WRONG_ACLK_FREQUENCY Programmed ACLK frequency is not the required 16MHz.
The function programs the DMA Tx channel.
Note
If the <buffer> parameter is NULL, the function will reprogram the Tx DMA channel with the same parameters as the previous transfer.
Definition at line 639 of file afe.c.
Referenced by adi_AFE_SeqInit().
ADI_AFE_RESULT_TYPE adi_AFE_ReadCalibrationRegister (ADI_AFE_DEV_HANDLE const hDevice, ADI_AFE_CAL_REG_TYPE Reg, uint32_t * pVal)
Read from a calibration register.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init().
[in] Reg Calibration register to be read.
[in] pVal Pointer to the value read from the register.
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_BAD_DEV_HANDLE Invalid device handle.
ADI_AFE_ERR_NOT_INITIALIZED Device not initialized.
ADI_AFE_ERR_ACLKOFF ACLK disabled from the clock gate.
ADI_AFE_ERR_WRONG_ACLK_FREQUENCY Programmed ACLK frequency is not the required 16MHz. *
Reads the value of an AFE calibration register. No unlock/lock is required.
Definition at line 418 of file afe.c.
ADI_AFE_RESULT_TYPE adi_AFE_RegisterAfeCallback (ADI_AFE_DEV_HANDLE hDevice, ADI_AFE_INT_GROUP_TYPE group, ADI_CALLBACK cbFunc, uint32_t cbWatch)
Application callback registration for AFE interrupt handlers.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init().
[in] group AFE interrupt group type identifier.
[in] cbFunc Application callback address; the function to call.
[in] cbWatch The interrupts to watch, controlling which interrupts result in a callback.
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_BAD_DEV_HANDLE Invalid device handle.
ADI_AFE_ERR_NOT_INITIALIZED Device not initialized.
ADI_AFE_ERR_ACLKOFF ACLK disabled from the clock gate.
ADI_AFE_ERR_WRONG_ACLK_FREQUENCY Programmed ACLK frequency is not the required 16MHz.
ADI_AFE_ERR_CALLBACK_OVERWRITE Attempt to overwrite existing callback.
Registers an application-defined callback function with one of the AFE interrupt handlers. Callbacks are made in response to received AFE interrupts, depending on whether they are enabled and whether the corresponding callback watch bits are set. This allows the application to control which interrupts it wants to be called back on.
The callback to the application is made in context of the originating interrupt (i.e. the AFE interrupt handler that is registered in the system's interrupt vector table). Extended processing during the callback (an extension of the AFE interrupt handler) is discouraged so as to avoid lower-priority interrupt blocking. Also, any register read-modify-write operations should be protected using the ADI_ENTER_CRITICAL_REGION()/ADI_EXIT_CRITICAL_REGION() pair to prevent higher-priority interrupts from modifying said register during the read-modify-write operation.
Note
CALLBACKS: AFE interrupt callbacks are disabled by default during the API initialization (adi_AFE_Init()). The application may use the #adi_AFE_RegisterCallback() API to register an application-defined callback function with the interrupt handler that will be called in response to selected AFE interrupts. The callback registration API takes an interrupt mask (of type uint32_t) that designates the set of interrupts to watch (upon which to dispatch the callback). When any of the watched interrupts occur, the appropriate AFE interrupt handler will make the callback to the application for application-based interrupt handling. The application callback should avoid extended processing during the callback as the callback is made context of the initiating interrupt and will block lower-priority interrupts. If extended application-level interrupt processing is required, the application should schedule it for the main application loop and exit the callback as soon as possible.
Definition at line 2116 of file afe.c.
ADI_AFE_RESULT_TYPE adi_AFE_RegisterCallbackOnReceiveDMA (ADI_AFE_DEV_HANDLE hDevice, ADI_CALLBACK cbFunc, uint32_t cbWatch)
Application callback registration for the AFE receive DMA done interrupt handler.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init().
[in] cbFunc Application callback address; the function to call.
[in] cbWatch Ignored.
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_BAD_DEV_HANDLE Invalid device handle.
ADI_AFE_ERR_NOT_INITIALIZED Device not initialized.
ADI_AFE_ERR_ACLKOFF ACLK disabled from the clock gate.
ADI_AFE_ERR_WRONG_ACLK_FREQUENCY Programmed ACLK frequency is not the required 16MHz.
ADI_AFE_ERR_CALLBACK_OVERWRITE Attempt to overwrite existing callback.
Registers an application-defined callback function with the DMA done interrupt handler for the AFE receive channel (DMA_AFE_RX_IRQn).
         The callback to the application is made in context of the originating interrupt (i.e., the AFE
         interrupt handler that is registered in the system's interrupt vector table).  Extended processing
         during the callback (an extension of the AFE interrupt handler) is discouraged so as to avoid lower-priority
         interrupt blocking.  Also, any register read-modify-write operations should be protected using the
         ADI_ENTER_CRITICAL_REGION()/ADI_EXIT_CRITICAL_REGION() pair to prevent higher-priority interrupts from modifying
         said register during the read-modify-write operation.
Note
CALLBACKS: AFE interrupt callbacks are disabled by default during the API initialization (adi_AFE_Init()). The application may use the adi_AFE_RegisterCallbackOnReceiveDMA() API to register an application-defined callback function with the interrupt handler that will be called in response to a DMA done interrupt for the AFE receive channel. When a DMA done interrupt occurs, the interrupt handler will make the callback to the application for application-based interrupt handling. The application callback should avoid extended processing during the callback as the callback is made context of the initiating interrupt and will block lower-priority interrupts. If extended application-level interrupt processing is required, the application should schedule it for the main application loop and exit the callback as soon as possible.
The value of the cbWatch parameter is ignored, because there is a single interrupt source that needs watching.
Definition at line 2046 of file afe.c.
ADI_AFE_RESULT_TYPE adi_AFE_RegisterCallbackOnTransmitDMA (ADI_AFE_DEV_HANDLE hDevice, ADI_CALLBACK cbFunc, uint32_t cbWatch)
Application callback registration for the AFE transmit DMA done interrupt handler.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init().
[in] cbFunc Application callback address; the function to call.
[in] cbWatch Ignored.
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_BAD_DEV_HANDLE Invalid device handle.
ADI_AFE_ERR_NOT_INITIALIZED Device not initialized.
ADI_AFE_ERR_ACLKOFF ACLK disabled from the clock gate.
ADI_AFE_ERR_WRONG_ACLK_FREQUENCY Programmed ACLK frequency is not the required 16MHz.
ADI_AFE_ERR_CALLBACK_OVERWRITE Attempt to overwrite existing callback.
Registers an application-defined callback function with the DMA done interrupt handler for the AFE transmit channel (DMA_AFE_TX_IRQn).
         The callback to the application is made in context of the originating interrupt (i.e., the AFE
         interrupt handler that is registered in the system's interrupt vector table).  Extended processing
         during the callback (an extension of the AFE interrupt handler) is discouraged so as to avoid lower-priority
         interrupt blocking.  Also, any register read-modify-write operations should be protected using the
         ADI_ENTER_CRITICAL_REGION()/ADI_EXIT_CRITICAL_REGION() pair to prevent higher-priority interrupts from modifying
         said register during the read-modify-write operation.
Note
CALLBACKS: AFE interrupt callbacks are disabled by default during the API initialization (adi_AFE_Init()). The application may use the adi_AFE_RegisterCallbackOnTransmitDMA() API to register an application-defined callback function with the interrupt handler that will be called in response to a DMA done interrupt for the AFE transmit channel. When a DMA done interrupt occurs, the interrupt handler will make the callback to the application for application-based interrupt handling. The application callback should avoid extended processing during the callback as the callback is made context of the initiating interrupt and will block lower-priority interrupts. If extended application-level interrupt processing is required, the application should schedule it for the main application loop and exit the callback as soon as possible.
The value of the cbWatch parameter is ignored, because there is a single interrupt source that needs watching.
Definition at line 1977 of file afe.c.
ADI_AFE_RESULT_TYPE adi_AFE_RunSequence (ADI_AFE_DEV_HANDLE const hDevice, const uint32_t *const txBuffer, uint16_t *const rxBuffer, uint32_t size)
Run a sequence.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init().
[in] txBuffer Array of sequencer commands to be sent through the Tx DMA channel
[in] rxBuffer Destination array for the data, to be written through the Rx DMA channel
[in] size Size of the expected data, expressed as number of halfwords
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_BAD_DEV_HANDLE Invalid device handle.
ADI_AFE_ERR_NOT_INITIALIZED Device not initialized.
ADI_AFE_ERR_ACLKOFF ACLK disabled from the clock gate.
ADI_AFE_ERR_WRONG_ACLK_FREQUENCY Programmed ACLK frequency is not the required 16MHz.
Before enabling the sequencer the command FIFO needs to be serviced. Either the FIFO is full (if the sequence is 8 commands or more), or the Tx DMA channel has completed the programmed transfers (sequences of less than 8 commands). This guarantees the command FIFO will not underflow on sequencer enable.
The function can be run in either blocking (default) or non-blocking mode. To enable non-blocking mode, the adi_AFE_SetRunSequenceBlockingMode() function must be called before the first call to adi_AFE_RunSequence().
Blocking mode: The function does not exit normally until the sequencer has finished execution, and the Rx DMA transfers have completed (if the Rx DMA channel is used for the current sequence). Low power mode (CORE_SLEEP) is entered while the sequence is executing until exectution finishes and the Rx DMA transefers are complete. The function performs all the steps needed to run the sequencer. It includes waiting for events required for the sequencer operation.
Non-Blocking mode: The function initializes and starts the sequence and then exits. Interrupts/callbacks or MMR polling should be used at the application level to determine when the sequencer and Rx DMA execution has completed. The seqState in the AFE device handle will be set to ADI_AFE_SEQ_STATE_RUNNING before the function exits and should also be updated at the application level.
If an error occurs, the waits can be skipped by setting the seqError variable, typically in an interrupt handler.
Definition at line 1515 of file afe.c.
Referenced by adi_AFE_AcMeas(), adi_AFE_AcMeas10khz(), adi_AFE_AuxChanCal(), adi_AFE_AuxChanMeasCustom(), adi_AFE_AuxChanMeasFixed(), adi_AFE_DcMeas(), adi_AFE_ExciteChanCalAtten(), adi_AFE_ExciteChanCalNoAtten(), adi_AFE_ExciteChanPowerUp(), adi_AFE_PowerUp(), adi_AFE_TempSensChanCal(), adi_AFE_TempSensMeas(), and adi_AFE_TiaChanCal().
ADI_AFE_RESULT_TYPE adi_AFE_SeqAbort (ADI_AFE_DEV_HANDLE const hDevice)
Abort the sequencer.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init().
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_BAD_DEV_HANDLE Invalid device handle.
ADI_AFE_ERR_NOT_INITIALIZED Device not initialized.
ADI_AFE_ERR_ACLKOFF ACLK disabled from the clock gate.
ADI_AFE_ERR_WRONG_ACLK_FREQUENCY Programmed ACLK frequency is not the required 16MHz.
The function stops the sequencer by writing a 0 to SEQ_EN, disables DMA requests and disables hardware accelerators
Its intended usage is following errors conditions during sequencer execution.
Definition at line 1379 of file afe.c.
Referenced by adi_AFE_RunSequence().
ADI_AFE_RESULT_TYPE adi_AFE_SeqCheck (ADI_AFE_DEV_HANDLE const hDevice, const uint32_t *const txBuffer)
Check the sequencer execution was successful.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init().
[in] txBuffer Array of sequencer commands to be sent through the Tx DMA channel.
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_BAD_DEV_HANDLE Invalid device handle.
ADI_AFE_ERR_NOT_INITIALIZED Device not initialized.
ADI_AFE_ERR_ACLKOFF ACLK disabled from the clock gate.
ADI_AFE_ERR_WRONG_ACLK_FREQUENCY Programmed ACLK frequency is not the required 16MHz.
The function checks that the command count and CRC calculated by the AFE sequencer match the values programmed in the sequencer commands array.
Definition at line 1437 of file afe.c.
Referenced by adi_AFE_RunSequence().
ADI_AFE_RESULT_TYPE adi_AFE_SeqInit (ADI_AFE_DEV_HANDLE const hDevice, const uint32_t *const txBuffer, uint16_t *const rxBuffer, uint32_t size)
Initialize the hardware needed for running the sequencer.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init().
[in] txBuffer Array of sequencer commands to be sent through the Tx DMA channel
[in] rxBuffer Destination array for the data, to be written through the Rx DMA channel
[in] size Size of the expected data, expressed as number of halfwords
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_BAD_DEV_HANDLE Invalid device handle.
ADI_AFE_ERR_NOT_INITIALIZED Device not initialized.
ADI_AFE_ERR_ACLKOFF ACLK disabled from the clock gate.
ADI_AFE_ERR_WRONG_ACLK_FREQUENCY Programmed ACLK frequency is not the required 16MHz.
The function prepares the hardware for running a sequence. It performs the following tasks:
program the DMA channels. If size is 0, no Rx DMA transfer is programmed.
enable the command FIFO and Tx DMA requests
enable the data FIFO and Rx DMA requests if required
reset the AFE CRC and command counter registers
unmask interrupts (CMD_FIFO_FULL and END_OF_SEQ)
initialize internal statuses
Definition at line 1153 of file afe.c.
Referenced by adi_AFE_RunSequence().
ADI_AFE_RESULT_TYPE adi_AFE_SeqStart (ADI_AFE_DEV_HANDLE const hDevice)
Start the sequencer.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init().
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_BAD_DEV_HANDLE Invalid device handle.
ADI_AFE_ERR_NOT_INITIALIZED Device not initialized.
ADI_AFE_ERR_ACLKOFF ACLK disabled from the clock gate.
ADI_AFE_ERR_WRONG_ACLK_FREQUENCY Programmed ACLK frequency is not the required 16MHz.
The function starts the sequencer by writing a 1 to SEQ_EN.
Definition at line 1273 of file afe.c.
Referenced by adi_AFE_RunSequence().
ADI_AFE_RESULT_TYPE adi_AFE_SeqStop (ADI_AFE_DEV_HANDLE const hDevice)
Stop the sequencer.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init().
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_BAD_DEV_HANDLE Invalid device handle.
ADI_AFE_ERR_NOT_INITIALIZED Device not initialized.
ADI_AFE_ERR_ACLKOFF ACLK disabled from the clock gate.
ADI_AFE_ERR_WRONG_ACLK_FREQUENCY Programmed ACLK frequency is not the required 16MHz.
The function stops the sequencer by writing a 0 to SEQ_EN. It also disables both FIFOs and DMA requests.
Definition at line 1320 of file afe.c.
Referenced by adi_AFE_RunSequence().
ADI_AFE_RESULT_TYPE adi_AFE_SetDataFifoSource (ADI_AFE_DEV_HANDLE const hDevice, ADI_AFE_DATA_FIFO_SOURCE_TYPE sel)
Select the input source for the data FIFO.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init().
[in] sel Select bits for the data FIFO input source.
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_BAD_DEV_HANDLE Invalid device handle.
ADI_AFE_ERR_NOT_INITIALIZED Device not initialized.
ADI_AFE_ERR_ACLKOFF ACLK disabled from the clock gate.
ADI_AFE_ERR_WRONG_ACLK_FREQUENCY Programmed ACLK frequency is not the required 16MHz.
Definition at line 196 of file afe.c.
ADI_AFE_RESULT_TYPE adi_AFE_SetLowPowerModeFlag (ADI_AFE_DEV_HANDLE const hDevice, bool_t * pbFlag)
Sets the flag for low power mode.
Parameters
hDevice Device handle obtained from adi_AFE_Init(). pError Error of ADI_AFE_RESULT_TYPE.
Returns
*bInterruptFlag Pointer to the flag used to enter low power mode.
Sets the private flag, bInterruptFlag, used by the adi_AFE_RunSequence() function when entering low power mode. Because this flag is private, it cannot be used directly to, for example, exit low power mode from another interrupt handler.
Definition at line 1735 of file afe.c.
ADI_AFE_RESULT_TYPE adi_AFE_SetRcal (ADI_AFE_DEV_HANDLE const hDevice, uint32_t rcal)
Set the RCAL value.
Parameters
hDevice Device handle obtained from adi_AFE_Init(). rcal Value of RCAL in ohms.
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_BAD_DEV_HANDLE Invalid device handle.
ADI_AFE_ERR_NOT_INITIALIZED Device not initialized.
Definition at line 1817 of file afe.c.
ADI_AFE_RESULT_TYPE adi_AFE_SetRtia (ADI_AFE_DEV_HANDLE const hDevice, uint32_t rtia)
Set the RTIA value.
Parameters
hDevice Device handle obtained from adi_AFE_Init(). rtia Value of RTIA in ohms.
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_BAD_DEV_HANDLE Invalid device handle.
ADI_AFE_ERR_NOT_INITIALIZED Device not initialized.
Definition at line 1884 of file afe.c.
ADI_AFE_RESULT_TYPE adi_AFE_SetRunSequenceBlockingMode (ADI_AFE_DEV_HANDLE const hDevice, const bool_t bFlag)
Set the status of the RunSequence blocking mode flag.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init().
[in] bFlag True if adi_AFE_RunSequence is to run in blocking mode False if adi_AFE_RunSequence is to run in non-blocking mode
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_BAD_DEV_HANDLE Invalid device handle.
ADI_AFE_ERR_NOT_INITIALIZED Device not initialized.
ADI_AFE_ERR_ACLKOFF ACLK disabled from the clock gate.
ADI_AFE_ERR_WRONG_ACLK_FREQUENCY Programmed ACLK frequency is not the required 16MHz.
Sets or clears the boolean flag which indicates if the adi_AFE_RunSequence function is to be run in blocking or non-blocking mode.
Definition at line 1076 of file afe.c.
ADI_AFE_RESULT_TYPE adi_AFE_SetSeqError (ADI_AFE_DEV_HANDLE const hDevice, ADI_AFE_RESULT_TYPE const error)
Sets the current sequencer error code.
Parameters
hDevice Device handle obtained from adi_AFE_Init(). pError Error of ADI_AFE_RESULT_TYPE.
Returns
Definition at line 824 of file afe.c.
ADI_AFE_RESULT_TYPE adi_AFE_SetSeqState (ADI_AFE_DEV_HANDLE const hDevice, ADI_AFE_SEQ_STATE_TYPE seqState)
Sets the sequencer state.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init().
[in] pState Sequencer state of ADI_AFE_SEQ_STATE_TYPE.
Returns
Definition at line 900 of file afe.c.
ADI_AFE_RESULT_TYPE adi_AFE_SetSwitchState (ADI_AFE_DEV_HANDLE const hDevice, uint32_t state)
Program the switch matrix.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init().
[in] state Encoded switch matrix state.
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_BAD_DEV_HANDLE Invalid device handle.
ADI_AFE_ERR_NOT_INITIALIZED Device not initialized.
ADI_AFE_ERR_ACLKOFF ACLK disabled from the clock gate.
ADI_AFE_ERR_WRONG_ACLK_FREQUENCY Programmed ACLK frequency is not the required 16MHz.
The function programs the switch matrix by writing to AFE_SW_CFG using encoded switch states.
Definition at line 316 of file afe.c.
Referenced by adi_AFE_PowerDown().
ADI_AFE_RESULT_TYPE adi_AFE_SetWavegenType (ADI_AFE_DEV_HANDLE const hDevice, ADI_AFE_WAVEGEN_TYPE sel)
Select the waveform type.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init().
[in] sel Waveform generator select bits.
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_BAD_DEV_HANDLE Invalid device handle.
ADI_AFE_ERR_NOT_INITIALIZED Device not initialized.
ADI_AFE_ERR_ACLKOFF ACLK disabled from the clock gate.
ADI_AFE_ERR_WRONG_ACLK_FREQUENCY Programmed ACLK frequency is not the required 16MHz.
Definition at line 255 of file afe.c.
ADI_AFE_RESULT_TYPE adi_AFE_TempSensChanCal (ADI_AFE_DEV_HANDLE const hDevice)
Temperature sensor channel calibration.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init().
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_BAD_DEV_HANDLE Invalid device handle.
ADI_AFE_ERR_NOT_INITIALIZED Device not initialized.
ADI_AFE_ERR_ACLKOFF ACLK disabled from the clock gate.
ADI_AFE_ERR_WRONG_ACLK_FREQUENCY Programmed ACLK frequency is not the required 16MHz.
The function calibrates the ADC temperature sensor channel.
It is an implementation of step 4 in the "AFE Example Use Cases" from HRM.
Definition at line 259 of file afe_lib.c.
ADI_AFE_RESULT_TYPE adi_AFE_TempSensMeas (ADI_AFE_DEV_HANDLE const hDevice, int32_t * tdegc)
Temperature measurement.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init().
[out] tdegc EMasured temperature, in degrees Celsius.
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_BAD_DEV_HANDLE Invalid device handle.
ADI_AFE_ERR_NOT_INITIALIZED Device not initialized.
ADI_AFE_ERR_ACLKOFF ACLK disabled from the clock gate.
ADI_AFE_ERR_WRONG_ACLK_FREQUENCY Programmed ACLK frequency is not the required 16MHz.
The function performs a temperature measurement using the internal temperature sensor.
It is an implementation of step 5 in the "AFE Example Use Cases" from HRM.
Definition at line 335 of file afe_lib.c.
ADI_AFE_RESULT_TYPE adi_AFE_TiaChanCal (ADI_AFE_DEV_HANDLE const hDevice)
TIA channel calibration.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init().
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_BAD_DEV_HANDLE Invalid device handle.
ADI_AFE_ERR_NOT_INITIALIZED Device not initialized.
ADI_AFE_ERR_ACLKOFF ACLK disabled from the clock gate.
ADI_AFE_ERR_WRONG_ACLK_FREQUENCY Programmed ACLK frequency is not the required 16MHz.
The function calibrates the TIA channel.
It is an implementation of step 7 in the "AFE Example Use Cases" from HRM.
It performs a measurement at a time and uses register reads instead of DMA to retrieve the results.
Definition at line 441 of file afe_lib.c.
ADI_AFE_RESULT_TYPE adi_AFE_TiaChanDacCode (ADI_AFE_DEV_HANDLE const hDevice, uint32_t * pTiaChanDacCode)
Returns the DAC code required for the TIA channel calibration.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init().
[out] TiaChanDacCode DAC code.
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_BAD_DEV_HANDLE Invalid device handle.
ADI_AFE_ERR_NOT_INITIALIZED Device not initialized.
Formula is: (750mV / RTIA) * 0.9 * RCAL / 1600mV * 4096 = (1728 * RCAL) / RTIA Add midscale at the end.
Definition at line 1047 of file afe_lib.c.
Referenced by adi_AFE_TiaChanCal().
ADI_AFE_RESULT_TYPE adi_AFE_UnInit (ADI_AFE_DEV_HANDLE const hDevice)
Uninitialize the AFE device.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init().
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_ALREADY_INITIALIZED Device already initialized.
Uninitializes the AFE for the first use. The function will enable the AFE clock (ACLK), initialize DMA channels, enable AFE interrupts, and reset the interrupt callbacks.
Note
The function does not require an ACLK frequency of 16MHz and can be called in any clock configuration. For example, the AFE can be unitialized after the ALCK frequency has been slowed down from 16MHz.
See Also
adi_AFE_Init()
Definition at line 2532 of file afe.c.
ADI_AFE_RESULT_TYPE adi_AFE_WriteCalibrationRegister (ADI_AFE_DEV_HANDLE const hDevice, ADI_AFE_CAL_REG_TYPE Reg, uint32_t Val)
Write to a calibration register.
Parameters
[in] hDevice Device handle obtained from adi_AFE_Init().
[in] Reg Calibration register to be written.
[in] Val Value to be written to the register.
Returns
Status
ADI_AFE_SUCCESS Call completed successfully.
ADI_AFE_ERR_BAD_DEV_HANDLE Invalid device handle.
ADI_AFE_ERR_NOT_INITIALIZED Device not initialized.
ADI_AFE_ERR_ACLKOFF ACLK disabled from the clock gate.
ADI_AFE_ERR_WRONG_ACLK_FREQUENCY Programmed ACLK frequency is not the required 16MHz.
Writes a 32-bit value to an AFE calibration register, handling the calibration register unlock prior to the write, and locking it again after the write takes place.
Definition at line 365 of file afe.c.
Referenced by adi_AFE_AuxChanCal(), adi_AFE_ExciteChanCalAtten(), adi_AFE_ExciteChanCalNoAtten(), adi_AFE_TempSensChanCal(), and adi_AFE_TiaChanCal().
Variable Documentation
const uint32_t seq_afe_acmeas10khz[]
Initial value:
= {
    0x001500F3,
    0x84005818,
    0x8A000034,
    0x9800A3D7,
    0x9E000516,
    0x88000F01,
    0x86008811,
    0xA0000002,
    0x0000063E,
    0x80024EF0,
    0x00000C7E,
    0x8002CFF0,
    0x0003233E,
    0x80020EF0,
    0x86003267,
    0x0000063E,
    0x80024EF0,
    0x00000C7E,
    0x8002CFF0,
    0x0003233E,
    0x80020EF0,
    0x82000002
}
Definition at line 297 of file afe_sequences.h.
const uint32_t seq_afe_auxchancal[]
Initial value:
= {
    0x000F00CA,
    0x84007818,
    0x0000063E,
    0xA000031C,
    0x0000063E,
    0x800301B0,
    0x0009087E,
    0x800200B0,
    0xA0000300,
    0xA000031D,
    0x0000063E,
    0x800301B0,
    0x0009087E,
    0x800200B0,
    0xA0000300,
    0x82000002
}
Definition at line 38 of file afe_sequences.h.
const uint32_t seq_afe_auxchanmeas1[]
Initial value:
= {
    0x000800F0,
    0x84007818,
    0xA0000000,
    0x0000063E,
    0x800301B0,
    0x0009087E,
    0x800200B0,
    0xA0000000,
    0x82000002
}
Definition at line 81 of file afe_sequences.h.
const uint32_t seq_afe_auxchanmeas2[]
Initial value:
= {
    0x000E00CA,
    0x84007818,
    0xA000022C,
    0x0000063E,
    0x800301B0,
    0x0009087E,
    0x800200B0,
    0xA0000220,
    0xA0000228,
    0x0000063E,
    0x800301B0,
    0x0009087E,
    0x800200B0,
    0xA0000200,
    0x82000002
}
Definition at line 60 of file afe_sequences.h.
const uint32_t seq_afe_dcmeas[]
Initial value:
= {
    0x001000B4,
    0x84007818,
    0x8A000036,
    0x8C000800,
    0x8E000C80,
    0x90007F8D,
    0x92000CC1,
    0x0000063E,
    0x94007F8D,
    0x96000CC1,
    0x86003267,
    0xA0000002,
    0x0000063E,
    0x80034FF0,
    0x003D08FE,
    0x80020EF0,
    0x82000002
}
Definition at line 327 of file afe_sequences.h.
const uint32_t seq_afe_excitechancalatten1[]
Initial value:
= {
    0x000900E8,
    0x88000F01,
    0x86008811,
    0xAA000800,
    0xA0000002,
    0x0000063E,
    0x80030FF0,
    0x0009087E,
    0x80020EF0,
    0x82000002
}
Definition at line 233 of file afe_sequences.h.
const uint32_t seq_afe_excitechancalatten2[]
Initial value:
= {
    0x0006007C,
    0xAA000800,
    0x0000063E,
    0x80030FF0,
    0x0009087E,
    0x80020EF0,
    0x82000002
}
Definition at line 251 of file afe_sequences.h.
const uint32_t seq_afe_excitechancalnoatten1[]
Initial value:
= {
    0x000900F4,
    0x88000F00,
    0x86008811,
    0xAA000800,
    0xA0000002,
    0x0000063E,
    0x80030FF0,
    0x0009087E,
    0x80020EF0,
    0x82000002
}
Definition at line 266 of file afe_sequences.h.
const uint32_t seq_afe_excitechancalnoatten2[]
Initial value:
= {
    0x0006007C,
    0xAA000800,
    0x0000063E,
    0x80030FF0,
    0x0009087E,
    0x80020EF0,
    0x82000002
}
Definition at line 284 of file afe_sequences.h.
const uint32_t seq_afe_excitechanpowerup[]
Initial value:
= {
    0x00030050,
    0x80020EF0,
    0x0000063E,
    0x82000002
}
Definition at line 140 of file afe_sequences.h.
const uint32_t seq_afe_powerup[]
Initial value:
= {
    0x000800FC,
    0x80080010,
    0x00007CFE,
    0x80040030,
    0x0004E1FE,
    0x80020030,
    0x0001387E,
    0x800200B0,
    0x82000002
}
Definition at line 23 of file afe_sequences.h.
const uint32_t seq_afe_tempsenschancal[]
Initial value:
= {
    0x001500D3,
    0x84007818,
    0x0000063E,
    0xA000031A,
    0x0000063E,
    0x800301B0,
    0x0009087E,
    0x800200B0,
    0xA0000300,
    0xA0000318,
    0x0000063E,
    0x800301B0,
    0x0009087E,
    0x800200B0,
    0xA0000300,
    0xA0000319,
    0x0000063E,
    0x800301B0,
    0x0009087E,
    0x800200B0,
    0xA0000300,
    0x82000002
}
Definition at line 96 of file afe_sequences.h.
const uint32_t seq_afe_tempsensmeas[]
Initial value:
= {
    0x00090078,
    0x800210B0,
    0xA0000103,
    0x0000063E,
    0x800331B0,
    0x0009087E,
    0x800200B0,
    0xA0000100,
    0xA0000300,
    0x82000002
}
Definition at line 124 of file afe_sequences.h.
const uint32_t seq_afe_tiachancal1[]
Initial value:
= {
    0x000800E8,
    0x86008811,
    0xAA0008E7,
    0xA0000018,
    0x0000063E,
    0x80030FF0,
    0x0009087E,
    0x80020EF0,
    0x82000002
}
Definition at line 152 of file afe_sequences.h.
const uint32_t seq_afe_tiachancal2[]
Initial value:
= {
    0x00070026,
    0xA0000000,
    0xA0000019,
    0x0000063E,
    0x80030FF0,
    0x0009087E,
    0x80020EF0,
    0x82000002
}
Definition at line 169 of file afe_sequences.h.
const uint32_t seq_afe_tiachancal3[]
Initial value:
= {
    0x00070074,
    0xA0000000,
    0xA000001E,
    0x0000063E,
    0x80030FF0,
    0x0009087E,
    0x80020EF0,
    0x82000002
}
Definition at line 185 of file afe_sequences.h.
const uint32_t seq_afe_tiachancal4[]
Initial value:
= {
    0x00080022,
    0xA0000000,
    0xA0000002,
    0x86003000,
    0x0000063E,
    0x80030FF0,
    0x0009087E,
    0x80020EF0,
    0x82000002
}
Definition at line 201 of file afe_sequences.h.
const uint32_t seq_afe_tiachancal5[]
Initial value:
= {
    0x00060070,
    0x86008811,
    0x0000063E,
    0x80030FF0,
    0x0009087E,
    0x80020EF0,
    0x82000002
}
Definition at line 218 of file afe_sequences.h.