ADuCM350BBCZ Device Drivers API Reference Manual: GPT Driver
GPT Driver
Typedefs
typedef struct
ADI_GPT_DEV_DATA_TYPE * ADI_GPT_HANDLE
Gptimer Handle.
Enumerations
enum ADI_GPT_CAPTURE_EVENTS_TYPE {
ADI_GPT_CAPTURE_EVENT_NONE = -1,
ADI_GPT_0_CAPTURE_EVENT_WAKEUP_TIMER = T0CON_EVENT_WUT,
ADI_GPT_0_CAPTURE_EVENT_EXTERNAL_INT_0 = T0CON_EVENT_EXT0,
ADI_GPT_0_CAPTURE_EVENT_EXTERNAL_INT_1 = T0CON_EVENT_EXT1,
ADI_GPT_0_CAPTURE_EVENT_EXTERNAL_INT_2 = T0CON_EVENT_EXT2,
ADI_GPT_0_CAPTURE_EVENT_EXTERNAL_INT_3 = T0CON_EVENT_EXT3,
ADI_GPT_0_CAPTURE_EVENT_EXTERNAL_INT_4 = T0CON_EVENT_EXT4,
ADI_GPT_0_CAPTURE_EVENT_EXTERNAL_INT_5 = T0CON_EVENT_EXT5,
ADI_GPT_0_CAPTURE_EVENT_EXTERNAL_INT_6 = T0CON_EVENT_EXT6,
ADI_GPT_0_CAPTURE_EVENT_EXTERNAL_INT_7 = T0CON_EVENT_EXT7,
ADI_GPT_0_CAPTURE_EVENT_EXTERNAL_INT_8 = T0CON_EVENT_EXT8,
ADI_GPT_0_CAPTURE_EVENT_AFE = T0CON_EVENT_AFE,
ADI_GPT_0_CAPTURE_EVENT_CAPTOUCH = T0CON_EVENT_CT,
ADI_GPT_0_CAPTURE_EVENT_WATCHDOG_TIMER = T0CON_EVENT_WDT,
ADI_GPT_0_CAPTURE_EVENT_FLASH_CONTROLLER = T0CON_EVENT_FEE,
ADI_GPT_0_CAPTURE_EVENT_TIMER1 = T0CON_EVENT_GPT1,
ADI_GPT_0_CAPTURE_EVENT_TIMER2 = T0CON_EVENT_GPT2,
ADI_GPT_1_CAPTURE_EVENT_UART = T1CON_EVENT_COM,
ADI_GPT_1_CAPTURE_EVENT_SPI0 = T1CON_EVENT_SPI0,
ADI_GPT_1_CAPTURE_EVENT_SPI1 = T1CON_EVENT_SPI1,
ADI_GPT_1_CAPTURE_EVENT_SPIH = T1CON_EVENT_SPIH,
ADI_GPT_1_CAPTURE_EVENT_I2C_SLAVE = T1CON_EVENT_I2CS,
ADI_GPT_1_CAPTURE_EVENT_I2C_MASTER = T1CON_EVENT_I2CM,
ADI_GPT_1_CAPTURE_EVENT_I2S = T1CON_EVENT_I2S,
ADI_GPT_1_CAPTURE_EVENT_USB = T1CON_EVENT_USB,
ADI_GPT_1_CAPTURE_EVENT_USB_DMA = T1CON_EVENT_USBDMA,
ADI_GPT_1_CAPTURE_EVENT_CRC = T1CON_EVENT_CRC,
ADI_GPT_1_CAPTURE_EVENT_BEEPER = T1CON_EVENT_BEEP,
ADI_GPT_1_CAPTURE_EVENT_DMA_ERROR = T1CON_EVENT_DMAERR,
ADI_GPT_1_CAPTURE_EVENT_DMA_DONE = T1CON_EVENT_DMADONE,
ADI_GPT_1_CAPTURE_EVENT_GPFLASH_CONTROLLER = T1CON_EVENT_GPFEE,
ADI_GPT_1_CAPTURE_EVENT_TIMER0 = T1CON_EVENT_GPT0,
ADI_GPT_1_CAPTURE_EVENT_TIMER2 = T1CON_EVENT_GPT2,
ADI_GPT_2_CAPTURE_EVENT_EXTERNAL_INT_0 = T2CON_EVENT_EXT0,
ADI_GPT_2_CAPTURE_EVENT_EXTERNAL_INT_1 = T2CON_EVENT_EXT1,
ADI_GPT_2_CAPTURE_EVENT_EXTERNAL_INT_2 = T2CON_EVENT_EXT2,
ADI_GPT_2_CAPTURE_EVENT_EXTERNAL_INT_3 = T2CON_EVENT_EXT3,
ADI_GPT_2_CAPTURE_EVENT_EXTERNAL_INT_4 = T2CON_EVENT_EXT4,
ADI_GPT_2_CAPTURE_EVENT_EXTERNAL_INT_5 = T2CON_EVENT_EXT5,
ADI_GPT_2_CAPTURE_EVENT_EXTERNAL_INT_6 = T2CON_EVENT_EXT6,
ADI_GPT_2_CAPTURE_EVENT_EXTERNAL_INT_7 = T2CON_EVENT_EXT7,
ADI_GPT_2_CAPTURE_EVENT_EXTERNAL_INT_8 = T2CON_EVENT_EXT8,
ADI_GPT_2_CAPTURE_EVENT_AFE = T2CON_EVENT_AFE,
ADI_GPT_2_CAPTURE_EVENT_CAPTOUCH = T2CON_EVENT_CT,
ADI_GPT_2_CAPTURE_EVENT_REALTIME_CLOCK = T2CON_EVENT_RTC,
ADI_GPT_2_CAPTURE_EVENT_TIMER0 = T2CON_EVENT_GPT0,
ADI_GPT_2_CAPTURE_EVENT_TIMER1 = T2CON_EVENT_GPT1
}
enum ADI_GPT_CLOCK_SELECT_TYPE {
ADI_GPT_CLOCK_SELECT_PCLK = TCON_CLK_PCLK,
ADI_GPT_CLOCK_SELECT_HFOSC = TCON_CLK_HFOSC,
ADI_GPT_CLOCK_SELECT_32KHZ_INTERNAL_CLOCK = TCON_CLK_LFOSC,
ADI_GPT_CLOCK_SELECT_EXTERNAL_CLOCK = TCON_CLK_LFXTAL
}
enum ADI_GPT_COUNT_MODE_TYPE {
ADI_GPT_COUNT_DOWN = 0,
ADI_GPT_COUNT_UP = TCON_UP
}
GP Timer couting modes.
enum ADI_GPT_DEV_ID_TYPE {
ADI_GPT_DEVID_0 = 0,
ADI_GPT_DEVID_1,
ADI_GPT_DEVID_2,
ADI_GPT_MAX_DEVID
}
Gptimer Device IDs.
enum ADI_GPT_EVENT_TYPE {
ADI_GPT_EVENT_TIMEOUT = BITM_GPT_GPTSTA_TMOUT,
ADI_GPT_EVENT_CAPTURED = BITM_GPT_GPTSTA_CAP
}
GP Timer callback events.
enum ADI_GPT_PRESCALER_TYPE {
ADI_GPT_PRESCALER_1 = TCON_PRE_DIV1,
ADI_GPT_PRESCALER_16 = TCON_PRE_DIV16,
ADI_GPT_PRESCALER_256 = TCON_PRE_DIV256,
ADI_GPT_PRESCALER_32768 = TCON_PRE_DIV32768
}
enum ADI_GPT_RESULT_TYPE {
ADI_GPT_SUCCESS = 0,
ADI_GPT_ERR_UNKNOWN_ERROR = ADI_DEV_GPT_ERROR_OFFSET,
ADI_GPT_ERR_ALREADY_INITIALIZED,
ADI_GPT_ERR_NOT_INITIALIZED,
ADI_GPT_ERR_BAD_INSTANCE,
ADI_GPT_ERR_PARAM_OUT_OF_RANGE,
ADI_GPT_ERR_BAD_DEV_HANDLE
}
Functions
ADI_GPT_RESULT_TYPE adi_GPT_ClearCapturedEventStatus (ADI_GPT_HANDLE const hDevice)
Clear the timer's Capture Event Status.
ADI_GPT_RESULT_TYPE adi_GPT_ClearTimeoutInterrupt (ADI_GPT_HANDLE hDevice)
Clear the timer's timeout IRQ status.
ADI_GPT_RESULT_TYPE adi_GPT_GetCapturedValue (ADI_GPT_HANDLE hDevice, uint16_t *pCapturedValue)
Read a GP Timer's Captured Event Value.
bool_t adi_GPT_GetCaptureEventPending (ADI_GPT_HANDLE hDevice)
Determine if the GP Timer has captured an event.
ADI_GPT_RESULT_TYPE adi_GPT_GetLdVal (ADI_GPT_HANDLE hDevice, uint16_t *pTimerLdVal)
GP Read the Timer's 16-bit load value (LD) which is used to re-load the timer's TX register.
bool_t adi_GPT_GetTimeOutEventStatus (ADI_GPT_HANDLE hDevice)
Determine if the GP Timer has timed out.
bool_t adi_GPT_GetTimerBusy (ADI_GPT_HANDLE hDevice)
Determine if the GP Timer is ready to receive configuration commands.
bool_t adi_GPT_GetTimerConfigValid (ADI_GPT_HANDLE hDevice)
Return the timer's configuration status.
ADI_GPT_RESULT_TYPE adi_GPT_GetTxVal (ADI_GPT_HANDLE hDevice, uint16_t *pTimerValue)
GP Read the Timer's 16-bit timer value (remaining time to count down/up)
ADI_GPT_RESULT_TYPE adi_GPT_Init (ADI_GPT_DEV_ID_TYPE InstanceNum, ADI_GPT_HANDLE *phDevice)
GP Timer Initialization.
ADI_GPT_RESULT_TYPE adi_GPT_RegisterCallback (ADI_GPT_HANDLE hDevice, ADI_CALLBACK pfCallback, void *pCBParam)
GP Timer Callback registration or un-registration function. Registers or un-registers the callback function, which will be called back to notify the events. The events listed in the enumeration ADI_GPT_EVENT_TYPE will be notified to the application.
ADI_GPT_RESULT_TYPE adi_GPT_ResetTimer (ADI_GPT_HANDLE hDevice)
GP Timer Reset Resets a timer to default settings.
ADI_GPT_RESULT_TYPE adi_GPT_SetCaptureEventEnable (ADI_GPT_HANDLE hDevice, bool_t bEnable)
GP Timer Event Enable Enable or Disable the capturing of events.
ADI_GPT_RESULT_TYPE adi_GPT_SetClockSelect (ADI_GPT_HANDLE hDevice, ADI_GPT_CLOCK_SELECT_TYPE ClockSelect)
GP Clock Select Selects the clock source for a GP Timer.
ADI_GPT_RESULT_TYPE adi_GPT_SetCountMode (ADI_GPT_HANDLE hDevice, ADI_GPT_COUNT_MODE_TYPE Mode)
GP Set Count Mode Timers can be configured to either count up or count down.
ADI_GPT_RESULT_TYPE adi_GPT_SetEventToCapture (ADI_GPT_HANDLE hDevice, ADI_GPT_CAPTURE_EVENTS_TYPE Event)
GP Timer Set Event to Capture Each timer can be configured to capture one of various events.
ADI_GPT_RESULT_TYPE adi_GPT_SetFreeRunningMode (ADI_GPT_HANDLE hDevice)
Set GP Timer to operate in Free Running Mode.
ADI_GPT_RESULT_TYPE adi_GPT_SetLdVal (ADI_GPT_HANDLE hDevice, const uint16_t TimerLdVal)
GP Set the Timer's 16-bit load value (LD)
ADI_GPT_RESULT_TYPE adi_GPT_SetPeriodicMode (ADI_GPT_HANDLE hDevice, bool_t bMod, uint16_t reloadValue)
Place GP Timer in/out of Perodic Mode and set the reload value load value will be changed on a write to TxCLRI (The load value will also be set on a timeout) Timer can be configured to be periodic.
ADI_GPT_RESULT_TYPE adi_GPT_SetPrescaler (ADI_GPT_HANDLE hDevice, ADI_GPT_PRESCALER_TYPE preScaler)
GP Timer set prescaler Timer can be configured with various prescaler values.
ADI_GPT_RESULT_TYPE adi_GPT_SetTimerEnable (ADI_GPT_HANDLE hDevice, bool_t bEnable)
Enable/Disable the GP Timer.
ADI_GPT_RESULT_TYPE adi_GPT_UnInit (ADI_GPT_HANDLE const hDevice)
Close the specified GP Timer.
Detailed Description
General Purpose Timer Device Driver
Typedef Documentation
typedef struct ADI_GPT_DEV_DATA_TYPE* ADI_GPT_HANDLE
Gptimer Handle.
The GP Timer Handle declaration. The handle is used in all subsequent GP Timer API calls.
Note
May require a MISRA suppression about incomplete types (rule 18.1)
Definition at line 199 of file gpt.h.
Enumeration Type Documentation
enum ADI_GPT_CAPTURE_EVENTS_TYPE
GP Timer Capture Event Definitions
There are 30 interrupt events that can be captured by the general purpose timers. These events are divided into two groups of 16 inputs for each of the timers as shown below. Any one of the 16 events associated with a general purpose timer can cause a capture of the 16 bit TxVAL register in to the 16 bit TxCAP register.
Enumerator
ADI_GPT_CAPTURE_EVENT_NONE
No event
ADI_GPT_0_CAPTURE_EVENT_WAKEUP_TIMER
Wakeup Timer triggered event capture
ADI_GPT_0_CAPTURE_EVENT_EXTERNAL_INT_0
Implemenation specific externally triggered event capture
ADI_GPT_0_CAPTURE_EVENT_EXTERNAL_INT_1
Implemenation specific externally triggered event capture
ADI_GPT_0_CAPTURE_EVENT_EXTERNAL_INT_2
Implemenation specific externally triggered event capture
ADI_GPT_0_CAPTURE_EVENT_EXTERNAL_INT_3
Implemenation specific externally triggered event capture
ADI_GPT_0_CAPTURE_EVENT_EXTERNAL_INT_4
Implemenation specific externally triggered event capture
ADI_GPT_0_CAPTURE_EVENT_EXTERNAL_INT_5
Implemenation specific externally triggered event capture
ADI_GPT_0_CAPTURE_EVENT_EXTERNAL_INT_6
Implemenation specific externally triggered event capture
ADI_GPT_0_CAPTURE_EVENT_EXTERNAL_INT_7
Implemenation specific externally triggered event capture
ADI_GPT_0_CAPTURE_EVENT_EXTERNAL_INT_8
Implemenation specific externally triggered event capture
ADI_GPT_0_CAPTURE_EVENT_AFE
AFE triggered event capture
ADI_GPT_0_CAPTURE_EVENT_CAPTOUCH
CapTouch triggered event capture
ADI_GPT_0_CAPTURE_EVENT_WATCHDOG_TIMER
Watch Dog Timer triggered event capture
ADI_GPT_0_CAPTURE_EVENT_FLASH_CONTROLLER
Flash Controller event capture
ADI_GPT_0_CAPTURE_EVENT_TIMER1
GP Timer1 triggered event capture
ADI_GPT_0_CAPTURE_EVENT_TIMER2
GP Timer2 triggered event capture
ADI_GPT_1_CAPTURE_EVENT_UART
UART triggered event capture
ADI_GPT_1_CAPTURE_EVENT_SPI0
SPI0 triggered event capture
ADI_GPT_1_CAPTURE_EVENT_SPI1
SPI1 triggered event capture
ADI_GPT_1_CAPTURE_EVENT_SPIH
High-speed SPI triggered event capture
ADI_GPT_1_CAPTURE_EVENT_I2C_SLAVE
I2C Slave triggered event capture
ADI_GPT_1_CAPTURE_EVENT_I2C_MASTER
I2C Master triggered event capture
ADI_GPT_1_CAPTURE_EVENT_I2S
I2S triggered event capture
ADI_GPT_1_CAPTURE_EVENT_USB
USB triggered event capture
ADI_GPT_1_CAPTURE_EVENT_USB_DMA
USB DMA triggered event capture
ADI_GPT_1_CAPTURE_EVENT_CRC
CRC triggered event capture
ADI_GPT_1_CAPTURE_EVENT_BEEPER
BEEPER triggered event capture
ADI_GPT_1_CAPTURE_EVENT_DMA_ERROR
DMA Error triggered event capture
ADI_GPT_1_CAPTURE_EVENT_DMA_DONE
DMA Done triggered event capture
ADI_GPT_1_CAPTURE_EVENT_GPFLASH_CONTROLLER
GP Flash Controller event capture
ADI_GPT_1_CAPTURE_EVENT_TIMER0
GP Timer triggered event capture
ADI_GPT_1_CAPTURE_EVENT_TIMER2
GP Timer triggered event capture
ADI_GPT_2_CAPTURE_EVENT_EXTERNAL_INT_0
Implemenation specific externally triggered event capture
ADI_GPT_2_CAPTURE_EVENT_EXTERNAL_INT_1
Implemenation specific externally triggered event capture
ADI_GPT_2_CAPTURE_EVENT_EXTERNAL_INT_2
Implemenation specific externally triggered event capture
ADI_GPT_2_CAPTURE_EVENT_EXTERNAL_INT_3
Implemenation specific externally triggered event capture
ADI_GPT_2_CAPTURE_EVENT_EXTERNAL_INT_4
Implemenation specific externally triggered event capture
ADI_GPT_2_CAPTURE_EVENT_EXTERNAL_INT_5
Implemenation specific externally triggered event capture
ADI_GPT_2_CAPTURE_EVENT_EXTERNAL_INT_6
Implemenation specific externally triggered event capture
ADI_GPT_2_CAPTURE_EVENT_EXTERNAL_INT_7
Implemenation specific externally triggered event capture
ADI_GPT_2_CAPTURE_EVENT_EXTERNAL_INT_8
Implemenation specific externally triggered event capture
ADI_GPT_2_CAPTURE_EVENT_AFE
AFE triggered event capture
ADI_GPT_2_CAPTURE_EVENT_CAPTOUCH
CapTouch triggered event capture
ADI_GPT_2_CAPTURE_EVENT_REALTIME_CLOCK
RTC triggered event capture
ADI_GPT_2_CAPTURE_EVENT_TIMER0
GP Timer triggered event capture
ADI_GPT_2_CAPTURE_EVENT_TIMER1
GP Timer triggered event capture
Definition at line 90 of file gpt.h.
enum ADI_GPT_CLOCK_SELECT_TYPE
GP Timer Clock Select Definitions. The GP Timers can be clocked from a variety of sources.
Enumerator
ADI_GPT_CLOCK_SELECT_PCLK
Use internal system clock
ADI_GPT_CLOCK_SELECT_HFOSC
Use internal 16 MHz oscillator
ADI_GPT_CLOCK_SELECT_32KHZ_INTERNAL_CLOCK
Use internal 32 kHz oscillator
ADI_GPT_CLOCK_SELECT_EXTERNAL_CLOCK
Use external 32 kHz crystal
Definition at line 73 of file gpt.h.
enum ADI_GPT_COUNT_MODE_TYPE
GP Timer couting modes.
GP Timers can be set to count up or to count down.
Enumerator
ADI_GPT_COUNT_DOWN
GP Timer count down mode
ADI_GPT_COUNT_UP
GP Timer count up mode
Definition at line 171 of file gpt.h.
enum ADI_GPT_DEV_ID_TYPE
Gptimer Device IDs.
List of all GP Timer Device IDs for the ADuCxxx part
Enumerator
ADI_GPT_DEVID_0
GP Timer Device 0
ADI_GPT_DEVID_1
GP Timer Device 1
ADI_GPT_DEVID_2
GP Timer Device 2
ADI_GPT_MAX_DEVID
max number of GPT
Definition at line 183 of file gpt.h.
enum ADI_GPT_EVENT_TYPE
GP Timer callback events.
When a callback is registered to get notification about the time out and event capture, the application supplied callback will be called with one of the following events.
Enumerator
ADI_GPT_EVENT_TIMEOUT
The timer has expired. The given timer event is captured. Application should use the API adi_GPT_GetCapturedValue to get the timer value when the event is captured.
Definition at line 155 of file gpt.h.
enum ADI_GPT_PRESCALER_TYPE
GP Timer Prescaler Definitions used to scale down the clock source.
Enumerator
ADI_GPT_PRESCALER_1
Count up/down every source clock
ADI_GPT_PRESCALER_16
Count up/down every 16 source clocks
ADI_GPT_PRESCALER_256
Count up/down every 256 source clocks
ADI_GPT_PRESCALER_32768
Count up/down every 32768 source clocks
Definition at line 60 of file gpt.h.
enum ADI_GPT_RESULT_TYPE
Gptimer API return codes
Enumerator
ADI_GPT_SUCCESS
No Error
ADI_GPT_ERR_UNKNOWN_ERROR
An unknown error was detected
ADI_GPT_ERR_ALREADY_INITIALIZED
Gptimer is already initialized
ADI_GPT_ERR_NOT_INITIALIZED
Gptimer not yet initialized
ADI_GPT_ERR_BAD_INSTANCE
Asking to initialize an unknown instance
ADI_GPT_ERR_PARAM_OUT_OF_RANGE
Parameter is out of range.
ADI_GPT_ERR_BAD_DEV_HANDLE
Invalid device handle passed
Definition at line 43 of file gpt.h.
Function Documentation
ADI_GPT_RESULT_TYPE adi_GPT_ClearCapturedEventStatus (ADI_GPT_HANDLE const hDevice)
Clear the timer's Capture Event Status.
The capture event interrupt status is sticky. This routine will clear the capture event interrupt.
Parameters
[in] hDevice Handle to the GP Timer intance as returned by adi_GPT_Init
Returns
Status
ADI_GPT_SUCCESS if successful
ADI_GPT_ERR_BAD_DEV_HANDLE [D] if device handle is invalid
Definition at line 314 of file gpt.c.
Referenced by adi_GPT_ResetTimer().
ADI_GPT_RESULT_TYPE adi_GPT_ClearTimeoutInterrupt (ADI_GPT_HANDLE hDevice)
Clear the timer's timeout IRQ status.
The timeout event interrupt status is sticky. This routine will clear the timeout event interrupt.
Parameters
[in] hDevice Handle to the GP Timer intance as returned by adi_GPT_Init
Returns
Status
ADI_GPT_SUCCESS if successful
ADI_GPT_ERR_BAD_DEV_HANDLE [D] if device handle is invalid
Definition at line 342 of file gpt.c.
Referenced by adi_GPT_ResetTimer().
ADI_GPT_RESULT_TYPE adi_GPT_GetCapturedValue (ADI_GPT_HANDLE hDevice, uint16_t * pCapturedValue)
Read a GP Timer's Captured Event Value.
When an event is triggered the timer's TxVAL register is copied into the TxCAP register. This functions simply returns the unsigned 16-bit value stored in the timer's TxCAP Register.
Parameters
[in] hDevice Handle to the GP Timer intance as returned by adi_GPT_Init
[out] pCapturedValue Pointer to the 16-bit capture event value which will be written upon success
Returns
Status
ADI_GPT_SUCCESS if successful
ADI_GPT_ERR_BAD_DEV_HANDLE [D] if device handle is invalid
Definition at line 371 of file gpt.c.
bool_t adi_GPT_GetCaptureEventPending (ADI_GPT_HANDLE hDevice)
Determine if the GP Timer has captured an event.
Parameters
[in] hDevice Handle to the GP Timer intance as returned by adi_GPT_Init
Returns
Status
false if the timer has not captured an event
true if the timer has captured an event
Note
This routine will return false in the event the Handle is NULL
Definition at line 421 of file gpt.c.
ADI_GPT_RESULT_TYPE adi_GPT_GetLdVal (ADI_GPT_HANDLE hDevice, uint16_t * pTimerLdVal)
GP Read the Timer's 16-bit load value (LD) which is used to re-load the timer's TX register.
Parameters
[in] hDevice Handle to the GP Timer intance as returned by adi_GPT_Init
[out] pTimerLdVal Pointer to the 16-bit load value which will be written upon success
Returns
Status
ADI_GPT_SUCCESS if successful
ADI_GPT_ERR_BAD_DEV_HANDLE [D] if device handle is invalid
Definition at line 503 of file gpt.c.
bool_t adi_GPT_GetTimeOutEventStatus (ADI_GPT_HANDLE hDevice)
Determine if the GP Timer has timed out.
Parameters
[in] hDevice Handle to the GP Timer intance as returned by adi_GPT_Init
Returns
Status
false if the timer has not timed out
true if the timer has timed out
Definition at line 436 of file gpt.c.
bool_t adi_GPT_GetTimerBusy (ADI_GPT_HANDLE hDevice)
Determine if the GP Timer is ready to receive configuration commands.
Parameters
[in] hDevice Handle to the GP Timer intance as returned by adi_GPT_Init
Returns
Status
true if the timer is busy and not ready to receive commands to TxCON
false if the timer is ready to receive commands to TxCON
false [D] if the device handle is invalid
Definition at line 397 of file gpt.c.
bool_t adi_GPT_GetTimerConfigValid (ADI_GPT_HANDLE hDevice)
Return the timer's configuration status.
Parameters
[in] hDevice Handle to the GP Timer intance as returned by adi_GPT_Init written upon success
Returns
Status
true: If the timer has been initialized
false: If the timer has not been initialized
Note
This routine only examines whether or not the timer has been
initialized. It does not verify the configuration of the timer beyond
that.
Definition at line 457 of file gpt.c.
ADI_GPT_RESULT_TYPE adi_GPT_GetTxVal (ADI_GPT_HANDLE hDevice, uint16_t * pTimerValue)
GP Read the Timer's 16-bit timer value (remaining time to count down/up)
Parameters
[in] hDevice Handle to the GP Timer intance as returned by adi_GPT_Init
[out] pTimerValue Pointer to the 16-bit timer value which will be written upon success
Returns
Status
ADI_GPT_SUCCESS if successful
ADI_GPT_ERR_BAD_DEV_HANDLE [D] if device handle is invalid
Definition at line 530 of file gpt.c.
ADI_GPT_RESULT_TYPE adi_GPT_Init (ADI_GPT_DEV_ID_TYPE InstanceNum, ADI_GPT_HANDLE * phDevice)
GP Timer Initialization.
Parameters
[in] InstanceNum ADI_GPT_DEV_ID_TYPE specifying the instance of the GPTimer to use
[in] phDevice Pointer to a location that the device handle will be written to upon successful initialization
Returns
Status
ADI_GPT_SUCCESS if successfully initialized
ADI_GPT_ERR_ALREADY_INITIALIZED [D] if GP timer already initialized
ADI_GPT_ERR_BAD_INSTANCE [D] if instance number is invalid
Note
1. The contents of hDevice will be set to NULL upon failure
The timers, by default, will be initialized to Not enabled No capture events Clock select is PCLK Count Down Mode Prescaler is 1
To override these default you must use the appropriate GP timer configuration APIs.
Definition at line 186 of file gpt.c.
ADI_GPT_RESULT_TYPE adi_GPT_RegisterCallback (ADI_GPT_HANDLE hDevice, ADI_CALLBACK pfCallback, void * pCBParam)
GP Timer Callback registration or un-registration function. Registers or un-registers the callback function, which will be called back to notify the events. The events listed in the enumeration ADI_GPT_EVENT_TYPE will be notified to the application.
Parameters
[in] hDevice Handle to the GP Timer intance as returned by adi_GPT_Init
[in] pfCallback Pointer to the callback function.
[in] pCBParam Callback prameter, which will be passed back to the application when the callback is called.
Returns
Status
ADI_GPT_SUCCESS if successful.
ADI_GPT_ERR_BAD_DEV_HANDLE [D] if device handle is invalid.
Definition at line 860 of file gpt.c.
ADI_GPT_RESULT_TYPE adi_GPT_ResetTimer (ADI_GPT_HANDLE hDevice)
GP Timer Reset Resets a timer to default settings.
Parameters
[in] hDevice Handle to the GP Timer intance as returned by adi_GPT_Init
Returns
Status
ADI_GPT_SUCCESS if successful
ADI_GPT_ERR_BAD_DEV_HANDLE [D] if device handle is invalid
Note
The timer will be disabled.
Definition at line 830 of file gpt.c.
Referenced by adi_GPT_Init().
ADI_GPT_RESULT_TYPE adi_GPT_SetCaptureEventEnable (ADI_GPT_HANDLE hDevice, bool_t bEnable)
GP Timer Event Enable Enable or Disable the capturing of events.
Parameters
[in] hDevice Handle to the GP Timer intance as returned by adi_GPT_Init
[in] bEnable True: Enable Event Capture False: Disable Event Capture
Returns
Status
ADI_GPT_SUCCESS if successful
ADI_GPT_ERR_BAD_DEV_HANDLE [D] if device handle is invalid
Definition at line 593 of file gpt.c.
ADI_GPT_RESULT_TYPE adi_GPT_SetClockSelect (ADI_GPT_HANDLE hDevice, ADI_GPT_CLOCK_SELECT_TYPE ClockSelect)
GP Clock Select Selects the clock source for a GP Timer.
Parameters
[in] hDevice Handle to the GP Timer intance as returned by adi_GPT_Init().
[in] ClockSelect Selection is made from one of the following clock sources: UCLK/PCLK, according to target processor PCLK/Internal HF 16 MHz oscillator, according to target processor Internal LF 32 kHz oscillator External LF 32 kHz crystal (requires external crystal oscillator circuit enable)
Returns
Status
ADI_GPT_SUCCESS if successful
ADI_GPT_ERR_BAD_DEV_HANDLE [D] if device handle is invalid
ADI_GPT_ERR_PARAM_OUT_OF_RANGE [D] if param is invalid
Note
If selecting the external clock source, ADI_GPT_CLOCK_SELECT_EXTERNAL_CLOCK, the external crystal oscillator circuit must be separetly enabled via the Power Device Driver. If and when disabeling the "External Clock" source, make sure it is not also being used (as a system clock mutplixer input) by some other system resource.
Definition at line 798 of file gpt.c.
ADI_GPT_RESULT_TYPE adi_GPT_SetCountMode (ADI_GPT_HANDLE hDevice, ADI_GPT_COUNT_MODE_TYPE Mode)
GP Set Count Mode Timers can be configured to either count up or count down.
Parameters
[in] hDevice Handle to the GP Timer intance as returned by adi_GPT_Init
[in] Mode ADI_GPT_COUNT_MODE_TYPE
Returns
Status
ADI_GPT_SUCCESS if successful
ADI_GPT_ERR_BAD_DEV_HANDLE [D] if device handle is invalid
Definition at line 761 of file gpt.c.
ADI_GPT_RESULT_TYPE adi_GPT_SetEventToCapture (ADI_GPT_HANDLE hDevice, ADI_GPT_CAPTURE_EVENTS_TYPE Event)
GP Timer Set Event to Capture Each timer can be configured to capture one of various events.
Parameters
[in] hDevice Handle to the GP Timer intance as returned by adi_GPT_Init
[in] Event
Returns
Status
ADI_GPT_SUCCESS if successful
ADI_GPT_ERR_BAD_DEV_HANDLE [D] if device handle is invalid
ADI_GPT_ERR_PARAM_OUT_OF_RANGE [D] if param is invalid
Definition at line 558 of file gpt.c.
ADI_GPT_RESULT_TYPE adi_GPT_SetFreeRunningMode (ADI_GPT_HANDLE hDevice)
Set GP Timer to operate in Free Running Mode.
Parameters
[in] hDevice Handle to the GP Timer intance as returned by adi_GPT_Init
Returns
Status
ADI_GPT_SUCCESS if successful
ADI_GPT_ERR_BAD_DEV_HANDLE [D] if device handle is invalid
Definition at line 731 of file gpt.c.
ADI_GPT_RESULT_TYPE adi_GPT_SetLdVal (ADI_GPT_HANDLE hDevice, const uint16_t TimerLdVal)
GP Set the Timer's 16-bit load value (LD)
Parameters
[in] hDevice Handle to the GP Timer intance as returned by adi_GPT_Init
[in] TimerLdVal Value to be written to the timer's LD register
Returns
Status
ADI_GPT_SUCCESS if successful
ADI_GPT_ERR_BAD_DEV_HANDLE [D] if device handle is invalid
Definition at line 474 of file gpt.c.
ADI_GPT_RESULT_TYPE adi_GPT_SetPeriodicMode (ADI_GPT_HANDLE hDevice, bool_t bMod, uint16_t reloadValue)
Place GP Timer in/out of Perodic Mode and set the reload value load value will be changed on a write to TxCLRI (The load value will also be set on a timeout) Timer can be configured to be periodic.
Parameters
[in] hDevice Handle to the GP Timer intance as returned by adi_GPT_Init
[in] bMod True: Enable periodic mode False: Disable periodic mode
[in] reloadValue used to set TxLD
Returns
Status
ADI_GPT_SUCCESS if successful
ADI_GPT_ERR_BAD_DEV_HANDLE [D] if device handle is invalid
Definition at line 699 of file gpt.c.
ADI_GPT_RESULT_TYPE adi_GPT_SetPrescaler (ADI_GPT_HANDLE hDevice, ADI_GPT_PRESCALER_TYPE preScaler)
GP Timer set prescaler Timer can be configured with various prescaler values.
Parameters
[in] hDevice Handle to the GP Timer intance as returned by adi_GPT_Init
[in] preScaler Prescaler emum value for clock scaling
Returns
Status
ADI_GPT_SUCCESS if successful
ADI_GPT_ERR_BAD_DEV_HANDLE [D] if device handle is invalid
ADI_GPT_ERR_PARAM_OUT_OF_RANGE [D] if param is invalid
Definition at line 626 of file gpt.c.
ADI_GPT_RESULT_TYPE adi_GPT_SetTimerEnable (ADI_GPT_HANDLE hDevice, bool_t bEnable)
Enable/Disable the GP Timer.
Parameters
[in] hDevice Handle to the GP Timer intance as returned by adi_GPT_Init
[in] bEnable True: Enable the timer False: Disable and reset the timer, including the GPTVAL register
Returns
Status
ADI_GPT_SUCCESS if successful
ADI_GPT_ERR_BAD_DEV_HANDLE [D] if device handle is invalid
Definition at line 661 of file gpt.c.
Referenced by adi_GPT_ResetTimer(), and adi_GPT_UnInit().
ADI_GPT_RESULT_TYPE adi_GPT_UnInit (ADI_GPT_HANDLE const hDevice)
Close the specified GP Timer.
This routine will close a GP Timer and place it in a non-operation state.
Parameters
[in] hDevice Handle to the GP Timer intance as returned by adi_GPT_Init
Returns
Status
ADI_GPT_SUCCESS if successfully uninitialized
ADI_GPT_ERR_BAD_DEV_HANDLE [D] if device handle is invalid
Note
1. The timer will be disabled
If the timer is not in an initialized state no error will occur
Definition at line 274 of file gpt.c.