ADuCM350BBCZ Device Drivers API Reference Manual: System Interfaces
System Interfaces
Macros
#define __HFOSC 16000000
#define __HFXTAL 16000000
#define __LFCLK 32768
#define __USBPHYCLK 60000000
#define CLKCON0_RVAL (0x0000)
#define CLKCON1_RVAL (0x1010)
#define CLKCON3_RVAL (0x0088)
#define CLKCON4_RVAL (0x008F)
#define CLKCON5_RVAL (0x0180)
#define CLOCK_POWERUP_TIMEOUT (750000 / 50 + 1)
#define HFMUX_EXTERNAL_XTAL_VAL (1 << BITP_SYSCLK_CLKCON0_CLKMUX)
#define HFMUX_GPIO_VAL (3 << BITP_SYSCLK_CLKCON0_CLKMUX)
#define HFMUX_INTERNAL_OSC_VAL (0 << BITP_SYSCLK_CLKCON0_CLKMUX)
#define HFMUX_SYSTEM_PLL_VAL (2 << BITP_SYSCLK_CLKCON0_CLKMUX)
#define LFXTALEN_WORKAROUND (1)
#define LFXTALEN_WORKAROUND_WAIT_TIME (70 / 8 + 1)
#define MEAS_CLOCK_SOURCE_SPLL
#define MEAS_SPLL_DIV2_DEFAULT ADI_SYS_CLOCK_PLL_DIV2_ENABLED
#define MEAS_SPLL_MSEL_DEFAULT ADI_SYS_CLOCK_PLL_MSEL_4
#define MEAS_SPLL_NSEL_DEFAULT ADI_SYS_CLOCK_PLL_NSEL_16
#define OSCKEY_UNLOCK (0xCB14)
#define SLEEPDEEP_BIT (1 << 2)
#define SLEEPONEXIT_BIT (1 << 1)
#define SPLL_DIV2_DEFAULT ADI_SYS_CLOCK_PLL_DIV2_ENABLED
#define SPLL_MSEL_DEFAULT ADI_SYS_CLOCK_PLL_MSEL_4
#define SPLL_NSEL_DEFAULT ADI_SYS_CLOCK_PLL_NSEL_16
#define UPLL_DIV2_DEFAULT ADI_SYS_CLOCK_PLL_DIV2_DISABLED
#define UPLL_LOCK_WORKAROUND (1)
#define UPLL_LOCK_WORKAROUND_PRECHARGE_TIME (200 / 6 + 1)
#define UPLL_MSEL_DEFAULT ADI_SYS_CLOCK_PLL_MSEL_4
#define UPLL_NSEL_DEFAULT ADI_SYS_CLOCK_PLL_NSEL_15
Enumerations
enum ADI_SYS_CLOCK_GATE_ID {
ADI_SYS_CLOCK_GATE_CTCLK,
ADI_SYS_CLOCK_GATE_ACLK,
ADI_SYS_CLOCK_GATE_I2S,
ADI_SYS_CLOCK_GATE_UART,
ADI_SYS_CLOCK_GATE_I2C,
ADI_SYS_CLOCK_GATE_SPIH,
ADI_SYS_CLOCK_GATE_SPI1,
ADI_SYS_CLOCK_GATE_SPI0
}
enum ADI_SYS_CLOCK_ID {
ADI_SYS_CLOCK_USBPHY,
ADI_SYS_CLOCK_USBCTL,
ADI_SYS_CLOCK_PCLK,
ADI_SYS_CLOCK_I2C,
ADI_SYS_CLOCK_UART,
ADI_SYS_CLOCK_I2S,
ADI_SYS_CLOCK_SPI0,
ADI_SYS_CLOCK_SPI1,
ADI_SYS_CLOCK_SPIH,
ADI_SYS_CLOCK_CORE,
ADI_SYS_CLOCK_BUS,
ADI_SYS_CLOCK_FCLK,
ADI_SYS_CLOCK_HCLK_CT,
ADI_SYS_CLOCK_ACLK,
ADI_SYS_CLOCK_CT,
ADI_SYS_CLOCK_AFE
}
enum ADI_SYS_CLOCK_MUX_GROUP_ID {
ADI_SYS_CLOCK_MUX_SPLL,
ADI_SYS_CLOCK_MUX_LFCLK,
ADI_SYS_CLOCK_MUX_OUTPUT,
ADI_SYS_CLOCK_MUX_ROOT
}
enum ADI_SYS_CLOCK_MUX_ID {
ADI_SYS_CLOCK_MUX_SPLL_HF_OSC,
ADI_SYS_CLOCK_MUX_SPLL_HF_XTAL,
ADI_SYS_CLOCK_MUX_LFCLK_LFOSC,
ADI_SYS_CLOCK_MUX_LFCLK_LFXTAL,
ADI_SYS_CLOCK_MUX_OUTPUT_ROOT_CLK,
ADI_SYS_CLOCK_MUX_OUTPUT_LF_CLK,
ADI_SYS_CLOCK_MUX_OUTPUT_CT_CLK,
ADI_SYS_CLOCK_MUX_OUTPUT_HCLK_BUS,
ADI_SYS_CLOCK_MUX_OUTPUT_HCLK_CORE,
ADI_SYS_CLOCK_MUX_OUTPUT_P_CLK,
ADI_SYS_CLOCK_MUX_OUTPUT_USB_CTRL_CLK,
ADI_SYS_CLOCK_MUX_OUTPUT_USB_PHY_CLK,
ADI_SYS_CLOCK_MUX_OUTPUT_GPT0_CLK,
ADI_SYS_CLOCK_MUX_OUTPUT_GPT1_CLK,
ADI_SYS_CLOCK_MUX_OUTPUT_GPT2_CLK,
ADI_SYS_CLOCK_MUX_OUTPUT_WUT_CLK,
ADI_SYS_CLOCK_MUX_OUTPUT_RTC_CNT_CLK,
ADI_SYS_CLOCK_MUX_ROOT_HFOSC,
ADI_SYS_CLOCK_MUX_ROOT_HFXTAL,
ADI_SYS_CLOCK_MUX_ROOT_SPLL,
ADI_SYS_CLOCK_MUX_ROOT_GPIO
}
enum ADI_SYS_CLOCK_PLL_DIV2_TYPE {
ADI_SYS_CLOCK_PLL_DIV2_DISABLED = (0 << BITP_SYSCLK_CLKCON3_SPLLDIV2),
ADI_SYS_CLOCK_PLL_DIV2_ENABLED = (1 << BITP_SYSCLK_CLKCON3_SPLLDIV2)
}
enum ADI_SYS_CLOCK_PLL_MSEL_TYPE {
ADI_SYS_CLOCK_PLL_MSEL_1 = (0 << BITP_SYSCLK_CLKCON3_SPLLMSEL),
ADI_SYS_CLOCK_PLL_MSEL_2 = (1 << BITP_SYSCLK_CLKCON3_SPLLMSEL),
ADI_SYS_CLOCK_PLL_MSEL_4 = (2 << BITP_SYSCLK_CLKCON3_SPLLMSEL)
}
enum ADI_SYS_CLOCK_PLL_NSEL_TYPE {
ADI_SYS_CLOCK_PLL_NSEL_4 = (4 << BITP_SYSCLK_CLKCON3_SPLLNSEL),
ADI_SYS_CLOCK_PLL_NSEL_8 = (8 << BITP_SYSCLK_CLKCON3_SPLLNSEL),
ADI_SYS_CLOCK_PLL_NSEL_15 = (15 << BITP_SYSCLK_CLKCON3_SPLLNSEL),
ADI_SYS_CLOCK_PLL_NSEL_16 = (16 << BITP_SYSCLK_CLKCON3_SPLLNSEL)
}
enum ADI_SYS_CLOCK_SOURCE_ID {
ADI_SYS_CLOCK_SOURCE_HFXTAL,
ADI_SYS_CLOCK_SOURCE_LFXTAL,
ADI_SYS_CLOCK_SOURCE_HFOSC,
ADI_SYS_CLOCK_SOURCE_LFOSC,
ADI_SYS_CLOCK_SOURCE_SPLL,
ADI_SYS_CLOCK_SOURCE_UPLL,
ADI_SYS_CLOCK_SOURCE_GPIO
}
enum ADI_SYS_CLOCK_SOURCE_STATUS {
ADI_SYS_CLOCK_SOURCE_DISABLED = 0,
ADI_SYS_CLOCK_SOURCE_ENABLED_NOT_STABLE,
ADI_SYS_CLOCK_SOURCE_ENABLED_STABLE,
ADI_SYS_CLOCK_SOURCE_ID_NOT_VALID
}
enum ADI_SYS_CLOCK_TIMEOUT_TYPE {
ADI_SYS_CLOCK_TIMEOUT_DONT_WAIT_STABLE = 0,
ADI_SYS_CLOCK_TIMEOUT_USE_DEFAULT
}
enum ADI_SYS_POWER_MODE {
ADI_SYS_MODE_ACTIVE = 0,
ADI_SYS_MODE_CORE_SLEEP = 1,
ADI_SYS_MODE_SYS_SLEEP = 2,
ADI_SYS_MODE_HIBERNATE = 3
}
enum ADI_SYS_RESULT_TYPE {
ADI_SYS_SUCCESS = 0,
ADI_SYS_ERR_UNKNOWN_ERROR = ADI_DEV_SYS_ERROR_OFFSET,
ADI_SYS_ERR_CLOCK_DIVIDE_OUT_OF_RANGE,
ADI_SYS_ERR_INVALID_CLOCK_ID,
ADI_SYS_ERR_INVALID_CLOCK_INTERRUPT,
ADI_SYS_ERR_INVALID_CLOCK_RATIO,
ADI_SYS_ERR_INVALID_CLOCK_SPEED,
ADI_SYS_ERR_INVALID_POWER_MODE,
ADI_SYS_ERR_PARAM_OUT_OF_RANGE,
ADI_SYS_ERR_CLOCK_SOURCE_TIMEOUT,
ADI_SYS_ERR_CLOCK_SOURCE_USED_ROOT_CLK,
ADI_SYS_ERR_CLOCK_SOURCE_USED_PLL_CLK,
ADI_SYS_ERR_CLOCK_SOURCE_USED_GPT_CLK,
ADI_SYS_ERR_CLOCK_SOURCE_USED_WUT_CLK,
ADI_SYS_ERR_CLOCK_SOURCE_USED_RTC_CLK,
ADI_SYS_ERR_CLOCK_SOURCE_USED_LF_CLK,
ADI_SYS_ERR_CLOCK_PLACEHOLDER,
ADI_SYS_ERR_SPLL_CHANGE_NOT_ALLOWED,
ADI_SYS_ERR_PORT_NOT_VALID,
ADI_SYS_ERR_INVALID_MEAS_CLOCK_SOURCE,
ADI_SYS_ERR_INVALID_STATE_TRANSITION
}
Functions
ADI_SYS_CLOCK_SOURCE_STATUS GetClockSourceStatus (ADI_SYS_CLOCK_SOURCE_ID id)
Return the status of a clock source.
ADI_SYS_CLOCK_MUX_ID GetSystemClockMux (ADI_SYS_CLOCK_MUX_GROUP_ID id)
Read the value of a system clock mux.
uint32_t GetSystemExtClkFreq (void)
Gets the system external clock frequency.
ADI_SYS_RESULT_TYPE SetPllFreq (ADI_SYS_CLOCK_SOURCE_ID id, ADI_SYS_CLOCK_PLL_MSEL_TYPE msel, ADI_SYS_CLOCK_PLL_NSEL_TYPE nsel, ADI_SYS_CLOCK_PLL_DIV2_TYPE div2)
Program PLL frequency.
ADI_SYS_RESULT_TYPE SetSystemClockDivider (ADI_SYS_CLOCK_ID id, uint8_t div)
System set clock divide factor for an individual clock group.
void SetSystemClockMux (ADI_SYS_CLOCK_MUX_ID id)
Select a system clock mux.
void SetSystemExtClkFreq (uint32_t ExtClkFreq)
Sets the system external clock frequency.
ADI_SYS_RESULT_TYPE SystemClockSourcePowerDownIfUnused (ADI_SYS_CLOCK_SOURCE_ID id)
Power down clock source.
ADI_SYS_RESULT_TYPE SystemClockSourcePowerUp (ADI_SYS_CLOCK_SOURCE_ID id, ADI_SYS_CLOCK_TIMEOUT_TYPE timeout)
Power up clock source.
void SystemCoreClockUpdate (void)
Update internal SystemCoreClock variables.
ADI_SYS_RESULT_TYPE SystemEnableClock (ADI_SYS_CLOCK_GATE_ID id, bool_t bEnable)
Enable/disable individual peripheral clocks.
ADI_SYS_RESULT_TYPE SystemEnableClockSource (ADI_SYS_CLOCK_SOURCE_ID id, bool_t bEnable)
Enable/disable clock sources.
ADI_SYS_RESULT_TYPE SystemEnterLowPowerMode (const ADI_SYS_POWER_MODE PowerMode, bool_t volatile *pbInterruptOccurred, const uint8_t PriorityMask)
Puts the processor into given low power mode.
void SystemExitLowPowerMode (bool_t volatile *pbInterruptOccurred)
uint32_t SystemGetClockFrequency (ADI_SYS_CLOCK_ID id)
System set clock divide factor for an individual clock group.
void SystemInit (void)
Setup the microcontroller system. Initialize the System and update the SystemFrequency variable.
Variables
void __vector_table
Detailed Description
add result types to doxygen
Macro Definition Documentation
#define __HFOSC 16000000
System clock constant
Definition at line 38 of file system.c.
Referenced by SystemCoreClockUpdate().
#define __HFXTAL 16000000
System clock constant (may also be 8000000)
Definition at line 39 of file system.c.
Referenced by SystemCoreClockUpdate().
#define __LFCLK 32768
System clock constant (same whether internal osc or external xtal)
Definition at line 40 of file system.c.
Referenced by SystemCoreClockUpdate().
#define __USBPHYCLK 60000000
System clock constant
Definition at line 37 of file system.c.
Referenced by SystemGetClockFrequency().
#define SLEEPDEEP_BIT (1 << 2)
SCR Deep Sleep (SLEEPDEEP)
Definition at line 45 of file system.c.
Referenced by SystemEnterLowPowerMode().
#define SLEEPONEXIT_BIT (1 << 1)
SCR Sleep On Exit (SLEEPONEXIT)
Definition at line 46 of file system.c.
Referenced by SystemEnterLowPowerMode().
Enumeration Type Documentation
enum ADI_SYS_CLOCK_MUX_GROUP_ID
Clock multiplexer identifiers
Enumerator
ADI_SYS_CLOCK_MUX_SPLL
SPLL/UPLL input mux
ADI_SYS_CLOCK_MUX_LFCLK
32kHz (LFLCK) clock mux
ADI_SYS_CLOCK_MUX_OUTPUT
Clock out mux
ADI_SYS_CLOCK_MUX_ROOT
root_clk mux
Definition at line 86 of file system.h.
enum ADI_SYS_CLOCK_PLL_DIV2_TYPE
PLL parameter DIV2, applies to both SPLL and UPLL. Using SPLL bit position macros, the UPLL are identical.
Definition at line 185 of file system.h.
enum ADI_SYS_CLOCK_PLL_MSEL_TYPE
PLL parameter M (divider), applies to both SPLL and UPLL. Using SPLL bit position macros, the UPLL are identical.
Definition at line 175 of file system.h.
enum ADI_SYS_CLOCK_PLL_NSEL_TYPE
PLL parameter N (multiplier), applies to both SPLL and UPLL. The enumeration is incomplete, it only covers the recommended PLL settings. Using SPLL bit position macros, the UPLL are identical.
Definition at line 164 of file system.h.
enum ADI_SYS_CLOCK_SOURCE_STATUS
Clock source status.
Definition at line 150 of file system.h.
enum ADI_SYS_CLOCK_TIMEOUT_TYPE
Used to control the timeout failsafes while powering up clock sources.
Definition at line 143 of file system.h.
enum ADI_SYS_POWER_MODE
Power modes
Enumerator
ADI_SYS_MODE_ACTIVE
Fully Active
ADI_SYS_MODE_CORE_SLEEP
Core Sleep power-down mode
ADI_SYS_MODE_SYS_SLEEP
System Sleep power-down mode
ADI_SYS_MODE_HIBERNATE
Full Hybernate power-down mode
Definition at line 193 of file system.h.
enum ADI_SYS_RESULT_TYPE
System API function return codes
Enumerator
ADI_SYS_SUCCESS
No error detected.
ADI_SYS_ERR_UNKNOWN_ERROR
Generic unknown error occurred.
ADI_SYS_ERR_CLOCK_DIVIDE_OUT_OF_RANGE
Requested divide value is out of range.
ADI_SYS_ERR_INVALID_CLOCK_ID
Invalid ADI_SYS_CLOCK_ID specified.
ADI_SYS_ERR_INVALID_CLOCK_INTERRUPT
Invalid ADI_SYS_CLOCK_INTERRUPT_ID specified.
ADI_SYS_ERR_INVALID_CLOCK_RATIO
PDIV:HDIV ration must be integral.
ADI_SYS_ERR_INVALID_CLOCK_SPEED
Peripheral clock must >= system clock.
ADI_SYS_ERR_INVALID_POWER_MODE
Invalid low-power mode requested.
ADI_SYS_ERR_PARAM_OUT_OF_RANGE
Input param out of range.
ADI_SYS_ERR_CLOCK_SOURCE_TIMEOUT
Timeout while clock source powering up.
ADI_SYS_ERR_CLOCK_SOURCE_USED_ROOT_CLK
Clock source used as root clock when trying to power it down.
ADI_SYS_ERR_CLOCK_SOURCE_USED_PLL_CLK
Clock source used as PLL clock when trying to power it down.
ADI_SYS_ERR_CLOCK_SOURCE_USED_GPT_CLK
Clock source used as GPT clock when trying to power it down.
ADI_SYS_ERR_CLOCK_SOURCE_USED_WUT_CLK
Clock source used as WUT clock when trying to power it down.
ADI_SYS_ERR_CLOCK_SOURCE_USED_RTC_CLK
LFXTAL used as RTC clock when trying to power it down.
ADI_SYS_ERR_CLOCK_SOURCE_USED_LF_CLK
Clock source used as lf_clk when trying to power it down.
ADI_SYS_ERR_CLOCK_PLACEHOLDER
Unused placeholder
ADI_SYS_ERR_SPLL_CHANGE_NOT_ALLOWED
SPLL drives the system clock and cannot be changed.
ADI_SYS_ERR_PORT_NOT_VALID
Error when configuring GPIO as clock source.
ADI_SYS_ERR_INVALID_MEAS_CLOCK_SOURCE
MEAS_CLOCK_SOURCE macro invalid or undefined.
ADI_SYS_ERR_INVALID_STATE_TRANSITION
Undefined system clock state or invalid transition
Definition at line 210 of file system.h.
Function Documentation
ADI_SYS_CLOCK_SOURCE_STATUS GetClockSourceStatus (ADI_SYS_CLOCK_SOURCE_ID id)
Return the status of a clock source.
Parameters
[in] id Clock source identifier.
Returns
Status
#ADI_SYS_CLOCK_SOURCE_DISABLED if the clock source is disabled.
#ADI_SYS_CLOCK_SOURCE_ENABLED_NOT_STABLE if the clock source is enabled but not stable.
#ADI_SYS_CLOCK_SOURCE_ENABLED_STABLE if the clock source is enabled and stable.
#ADI_SYS_CLOCK_SOURCE_ID_NOT_VALID if the clock source identifier is not valid.
Return the status of a clock source.
Definition at line 1272 of file system.c.
Referenced by SystemClockSourcePowerUp().
ADI_SYS_CLOCK_MUX_ID GetSystemClockMux (ADI_SYS_CLOCK_MUX_GROUP_ID id)
Read the value of a system clock mux.
Parameters
id Multiplexor group identifier.
Returns
Multiplexor select value.
Definition at line 540 of file system.c.
Referenced by SetPllFreq(), and SystemClockSourcePowerDownIfUnused().
uint32_t GetSystemExtClkFreq (void)
Gets the system external clock frequency.
Returns
External Clock frequency
Gets the clock frequency of the source connected to the external GPIO clock input source
Definition at line 595 of file system.c.
ADI_SYS_RESULT_TYPE SetPllFreq (ADI_SYS_CLOCK_SOURCE_ID id, ADI_SYS_CLOCK_PLL_MSEL_TYPE msel, ADI_SYS_CLOCK_PLL_NSEL_TYPE nsel, ADI_SYS_CLOCK_PLL_DIV2_TYPE div2)
Program PLL frequency.
Parameters
[in] id Clock source identifier, can be either #ADI_SYS_CLOCK_SOURCE_SPLL or #ADI_SYS_CLOCK_SOURCE_UPLL. msel PLL M divider. nsel PLL N multiplier. div2 PLL DIV2 parameter.
Returns
Status
ADI_SYS_SUCCESS if the PLL has been programmed successfully.
ADI_SYS_ERR_SPLL_CHANGE_NOT_ALLOWED if trying to program SPLL and SPLL drives the system clock.
ADI_SYS_ERR_INVALID_CLOCK_ID if the clock identifier does not match either PLL.
Program PLL frequency (parameters M, N, DIV2) for either the System PLL or USB PLL.
Definition at line 1379 of file system.c.
ADI_SYS_RESULT_TYPE SetSystemClockDivider (ADI_SYS_CLOCK_ID id, uint8_t div)
System set clock divide factor for an individual clock group.
Parameters
[in] id Clock domain identifier
[in] div Clock divide value to be set (right-justified uint8_t)
Returns
Status
ADI_SYS_SUCCESS if successfully set the given clock divide factor.
ADI_SYS_ERR_CLOCK_DIVIDE_OUT_OF_RANGE [D] if the divider is out of range.
ADI_SYS_ERR_INVALID_CLOCK_ID [D] if the specified clock is invalid.
ADI_SYS_ERR_INVALID_CLOCK_SPEED [D] if the specified clock speed invalid.
ADI_SYS_ERR_INVALID_CLOCK_RATIO [D] if the specified clock ratio invalid.
Manage individual peripheral clock dividers.
See Also
SystemGetClockFrequency
Definition at line 765 of file system.c.
void SetSystemClockMux (ADI_SYS_CLOCK_MUX_ID id)
Select a system clock mux.
Parameters
dev Device ID
Returns
none
Setup a microcontroller system clock multiplexer. Initialize the System clock multiplexer and update the SystemCoreClock variable.
Definition at line 402 of file system.c.
Referenced by SystemInit().
void SetSystemExtClkFreq (uint32_t ExtClkFreq)
Sets the system external clock frequency.
Parameters
ExtClkFreq External clock frequency in Hz
Returns
none
Sets the clock frequency of the source connected to the external GPIO clock input source
Definition at line 386 of file system.c.
ADI_SYS_RESULT_TYPE SystemClockSourcePowerDownIfUnused (ADI_SYS_CLOCK_SOURCE_ID id)
Power down clock source.
Parameters
[in] id Clock source identifier.
Returns
Status
ADI_SYS_SUCCESS if the clock source powers up successfully.
ADI_SYS_ERR_CLOCK_SOURCE_USED_ROOT_CLK: if the clock source is used as root clock when trying to power it down.
ADI_SYS_ERR_CLOCK_SOURCE_USED_PLL_CLK: if the clock source is used as PLL input clock when trying to power it down.
ADI_SYS_ERR_CLOCK_SOURCE_USED_GPT_CLK: if the clock source is used as GPT clock when trying to power it down, and the GPT is enabled.
Disable clock source, if the clock source is not used. For each clock source, all possibilities of it being used are checked.
Definition at line 1096 of file system.c.
ADI_SYS_RESULT_TYPE SystemClockSourcePowerUp (ADI_SYS_CLOCK_SOURCE_ID id, ADI_SYS_CLOCK_TIMEOUT_TYPE timeout)
Power up clock source.
Parameters
[in] id Clock source identifier.
[in] timeout
Returns
Status
ADI_SYS_SUCCESS if the clock source powers up successfully.
#ADI_SYS_ERR_CLOCK_TIMEOUT [D] if a timeout error is registered.
Enable clock source and wait until the output is stable. Optionally the wait can be bypassed. The recommended timeout option is ADI_SYS_CLOCK_TIMEOUT_USE_DEFAULT, the other options are for development purpose.
Definition at line 990 of file system.c.
Referenced by adi_Beep_Init(), adi_RNG_Init(), and adi_RTC_Init().
void SystemCoreClockUpdate (void)
Update internal SystemCoreClock variables.
Returns
none
Updates the internal SystemCoreClocks with current core Clock retrieved from cpu registers.
Definition at line 310 of file system.c.
Referenced by SetSystemClockDivider(), SetSystemClockMux(), SystemGetClockFrequency(), and SystemInit().
ADI_SYS_RESULT_TYPE SystemEnableClock (ADI_SYS_CLOCK_GATE_ID id, bool_t bEnable)
Enable/disable individual peripheral clocks.
Parameters
[in] id Clock identifier
[in] bEnable Flag to indicate enable/disable individual clock gate. 'true' to enable and 'false' to disable
Returns
Status
ADI_SYS_SUCCESS if successfully managed the clock gate.
ADI_SYS_ERR_INVALID_CLOCK_ID [D] if the specified clock is invalid.
Manage individual clock gates.
Definition at line 707 of file system.c.
Referenced by adi_AFE_Init(), adi_AFE_UnInit(), adi_CT_Init(), adi_CT_UnInit(), adi_SPI_MasterInit(), adi_SPI_SlaveInit(), adi_SPI_UnInit(), adi_UART_Enable(), adi_UART_Init(), and adi_UART_UnInit().
ADI_SYS_RESULT_TYPE SystemEnableClockSource (ADI_SYS_CLOCK_SOURCE_ID id, bool_t bEnable)
Enable/disable clock sources.
Parameters
[in] id Clock source identifier. bEnable Enable (true) or disable (false) the clock source.
Returns
Status
ADI_SYS_SUCCESS if the clock source powers up successfully.
Enables or disables clock sources without additional checks, by writing a "1" or "0" to the enable bit. In case of the external GPIO, it configures P0.11 as input, with no pullup.
Definition at line 879 of file system.c.
Referenced by SystemClockSourcePowerDownIfUnused(), and SystemClockSourcePowerUp().
ADI_SYS_RESULT_TYPE SystemEnterLowPowerMode (const ADI_SYS_POWER_MODE PowerMode, bool_t volatile * pbInterruptOccurred, const uint8_t PriorityMask)
Puts the processor into given low power mode.
Parameters
[in] PowerMode One of the ADI_PWR_MODE_TYPE enum values, defining the specific low-power modes to use.
[in,out] pbInterruptOccurred Control parameter selection low-power operation. Either a NULL pointer for automatic hardware-based sleeping between interrupts, or a pointer to bool_t for software looping sleep between interrupts.
If a flag pointer is passed in, the flag must be false on entry, and will be cleared false on exit.
When a NULL is passed, it means the application wants the low-power implementation to use the automatic "sleep-on-exit" hardware sleep mode in which wakeup interrupts are dispatched and then automaticelly put the processor back to sleep on exit. All interrupts execute the same WFI instruction (no looping) under hardware control, which results in a faster re-sleep than the software mode.
When a non-NULL value is passed, it is interpreted as a pointer to a shared bool_t application control veriable allowing the wake-up interrupts to control whether/when the control loop should re-sleep the processor as each interrupt exits. Any interrupt that sets the variable will cause the sleep loop to exit. Otherwise, exiting interrupts will cause the core to re-sleep until the flag is set. Each interrupt executes a different WFI instruction inside a software loop (slower re-sleep).
Parameters
[in] PriorityMask A right-justified (unshifted) wakeup interrupt priority mask, corresponding to the programmable interrupt priority encoding scheme defined by the Cortex NVIC controller. The PriorityMask value blocks interrupts with an equal or lower priority than the specified level, such that only higher-priority interrupts (less in numerical value) than the priority mask awake the processor. A zero-valued PriorityMask disables interrupt masking.
Returns
Status
ADI_SYS_SUCCESS If successfully put the processor into low power mode.
ADI_SYS_ERR_PARAM_OUT_OF_RANGE [D] PriorityMask contains unimplemented hardware bits.
ADI_SYS_ERR_INVALID_POWER_MODE [D] Invalid low-power mode.
Puts the processor into a low-power mode with interrupt-based wakeup(s). Applications specify the low-power mode, a pointer to an application-defined interrupt flag, and an interrupt priority mask controlling the interrupt priority level that may awake the processor.
pbInterruptOccurred
When NULL, the processor is automatically put back to sleep as awaking interrupts exit. This mode employs the hardware "sleep-on-exit" system control register bit: SLEEPONEXIT_BIT in conjunction with the "wait-for- interrupt" (WFI) instruction to implement a persistant sleep mode.
When non-Null, a software strategy is used to control sleeping. As awakening interrupts are processed, they can set the flag true and thereby cause the sleep mode to be exited. Note that all interrupts share a common flag and any interrupt that sets the flag will cause the sleep mode to be exited.
Use of the pbInterruptOccurred parameter provides a mechanism to resolve two potential hibernation trouble spots: 1) the inherent race between the intended wakeup interrupt and the execution of the Wait-For-Interrupt instruction (WFI) used to sleep the processor, and 2) unrelated interrupts (of sufficient priority) that may terminate the wait prematurely.
In the first case of the race condition, the race is avoided by testing the pbInterruptOccurred flag prior to the WFI within a common critical section. This allows the SystemEnterLowPowerMode() implementation to insure the intended wakeup interrupt has not occurred already and control whether to sleep the processor. This insures the intended wakeup interrupt has not already occurred prior to the wait, thereby eliminating the race condition otherwise present.
In the second case of an unrelated interrupt terminating the sleep prematurely, the problem is solved by requiring the interrupt handler(s) which is(are) intended to awake the sleeping processor to set the application-defined pbInterruptOccurred flag in their respective interrupt handler(s). This insures only those interrupts that explicitly set the flag will break the sleeping processor out of the sleep cycle. Other (incidental) interrupts put the processor back to sleep after the interrupt because the flag would not have been set. This is why there is a loop around the WFI instruction.
The pbInterruptOccurred flag must be initialized to zero before first use, and this should be done prior to enabling any interrupt which may set it (otherwise interrupts may be missed). If this flag is a global or a static variable then static initialization to zero or false will be sufficient.
The flag should only be set, from an interrupt handler, by calling SystemExitLowPowerMode() and passing the flag variable by reference. The flag should not be assigned to directly, other than for initialization.
SystemEnterLowPowerMode() will always clear the flag again before returning, so the variable does not need to be cleared by user code on each use. Explicitly clearing the flag, outside of SystemEnterLowPowerMode() runs the risk of missing interrupts.
PriorityMask
A zero-valued PriorityMask disables interrupt masking, leaving all interrupts eligible to awake the sleeping processor. This means that zero-valued interrupts cannot be masked. A non-zero PriorityMask limits interrupts that may awake the sleeping processor to those with a higher priority level (lower numerically) than the specified PriorityMask value.
Each "programmable" peripheral interrupt has an associated priority-level register (which defaults to zero) within the Nested Vectored Interrupt Controller (NVIC). The number of interrupt priority encoding bits is defined by constant __NVIC_PRIO_BITS and is a fixed silicon attribute configured during chip design. The interrupt priority-level registers range in width from 3 to 8 bits.
The ADuCM350 uses 3-bit priority encoding, allowing priority levels ranging between 0 (the highest, default programmable priority) and 7 (the lowest). For example, if the PriorityMask parameter is set to 3, only interrupts with assigned priority 0, 1, and 2 may awake the processor. Since default priority of all programmable interrupts is 0, setting up maskable interrupts requires that they be demoted in priority (raised numerically) relative to interrupts that are intended to awake the processor.
Note
The number of priority levels is uncorrelated with the actual number of interrupts or their position in the Interrupt Vector Table (IVT). Interrupt priorities may be programmed individually.
The priority levels are actually stored in the core as a left-justified value in an 8-bit field. The SystemEnterLowPowerMode() API takes care of aligning the passed PriorityMask value to the core register (BASEPRI).
The default priority level for all interrupts is zero implies it is impossible to mask interrupts with a default zero-level priority encoding.
Power modes 4 and 5 only support select interrupt sources to awake the processor.
See Also
SystemExitLowPowerMode
Definition at line 1544 of file system.c.
Referenced by adi_AFE_RunSequence(), adi_I2S_Transmit(), and adi_SPI_MasterTransfer().
uint32_t SystemGetClockFrequency (ADI_SYS_CLOCK_ID id)
System set clock divide factor for an individual clock group.
Parameters
[in] id Clock identifier
Returns
Currently configured frequency of operation for specified clock (Hz).
Obtain individual peripheral clock frequencies.
See Also
SystemSetClockDivider
Definition at line 618 of file system.c.
Referenced by adi_AFE_AcMeas(), adi_AFE_AcMeas10khz(), adi_AFE_AuxChanCal(), adi_AFE_AuxChanMeasFixed(), adi_AFE_ClearInterruptSource(), adi_AFE_DcMeas(), adi_AFE_EnableInterruptSource(), adi_AFE_ExciteChanCalAtten(), adi_AFE_ExciteChanCalNoAtten(), adi_AFE_ExciteChanPowerUp(), adi_AFE_GetCmdFifoReady(), adi_AFE_GetRxDmaComplete(), adi_AFE_GetSeqError(), adi_AFE_GetSeqFinished(), adi_AFE_GetSeqState(), adi_AFE_PowerDown(), adi_AFE_PowerUp(), adi_AFE_ProgramRxDMA(), adi_AFE_ProgramTxDMA(), adi_AFE_ReadCalibrationRegister(), adi_AFE_RegisterAfeCallback(), adi_AFE_RegisterCallbackOnReceiveDMA(), adi_AFE_RegisterCallbackOnTransmitDMA(), adi_AFE_RunSequence(), adi_AFE_SeqAbort(), adi_AFE_SeqCheck(), adi_AFE_SeqInit(), adi_AFE_SeqStart(), adi_AFE_SeqStop(), adi_AFE_SetDataFifoSource(), adi_AFE_SetSeqError(), adi_AFE_SetSeqState(), adi_AFE_SetSwitchState(), adi_AFE_SetWavegenType(), adi_AFE_TempSensChanCal(), adi_AFE_TempSensMeas(), adi_AFE_TiaChanCal(), adi_AFE_WriteCalibrationRegister(), adi_I2C_SetMasterClock(), adi_SPI_GetBitrate(), adi_SPI_SetBitrate(), adi_UART_GetBaudRate(), and adi_UART_SetBaudRate().
void SystemInit (void)
Setup the microcontroller system. Initialize the System and update the SystemFrequency variable.
Initialize the system
Returns
none
Definition at line 216 of file system.c.