ADuCM350BBCZ Device Drivers API Reference Manual: UART Driver
UART Driver
Data Structures
struct ADI_UART_GENERIC_SETTINGS_TYPE
struct ADI_UART_INIT_DATA
Macros
#define ASSERT_ADI_MISRA_SUPPRESSIONS
#define IS_BLOCKING_MODE(hDevice) false
#define IS_INTERRUPT_MODE(hDevice) false
#define IS_NONBLOCKING_MODE(hDevice) false
#define IS_POLLED_MODE(hDevice) false
#define REVERT_ADI_MISRA_SUPPRESSIONS
Typedefs
typedef struct
ADI_UART_DEV_DATA_TYPE * ADI_UART_HANDLE
ADI_UART_HANDLE.
Enumerations
enum ADI_UART_BAUDRATE_TYPE {
ADI_UART_BAUD_9600 = 0,
ADI_UART_BAUD_19200,
ADI_UART_BAUD_38400,
ADI_UART_BAUD_57600,
ADI_UART_BAUD_115200,
ADI_UART_BAUD_230400,
ADI_UART_BAUD_460800,
ADI_UART_BAUD_MAX_ENTRIES
}
enum ADI_UART_DEV_ID_TYPE { ADI_UART_DEVID_0 =0 }
enum ADI_UART_DRV_STATE_TYPE {
ADI_UART_DRV_STATE_UNKNOWN = 0,
ADI_UART_DRV_STATE_INITIALIZED,
ADI_UART_DRV_STATE_READY
}
enum ADI_UART_PARITY_TYPE {
ADI_UART_PARITY_NONE,
ADI_UART_PARITY_ODD,
ADI_UART_PARITY_EVEN
}
enum ADI_UART_RESULT_TYPE {
ADI_UART_SUCCESS = 0,
ADI_UART_ERR_UNKNOWN = ADI_DEV_UART_ERROR_OFFSET,
ADI_UART_ERR_ALREADY_INITIALIZED,
ADI_UART_ERR_INVALID_INSTANCE,
ADI_UART_ERR_INVALID_DEVID,
ADI_UART_ERR_INVALID_PARAMS,
ADI_UART_ERR_NOT_SUPPORTED,
ADI_UART_ERR_NOT_INITIALIZED,
ADI_UART_ERR_GPIO_CONFIG_FAILED,
ADI_UART_ERR_INVALID_BUFFER,
ADI_UART_ERR_SEMAPHORE_FAILED
}
enum ADI_UART_WLS_TYPE {
ADI_UART_WLS_5 = 0,
ADI_UART_WLS_6 = 1,
ADI_UART_WLS_7 = 2,
ADI_UART_WLS_8 = 3
}
Functions
ADI_UART_RESULT_TYPE adi_UART_BufFlush (ADI_UART_HANDLE const hDevice)
Flush UART FIFOS.
ADI_UART_RESULT_TYPE adi_UART_BufRx (ADI_UART_HANDLE const hDevice, const void *pData, int16_t *pSize)
Receives Data from UART.
ADI_UART_RESULT_TYPE adi_UART_BufTx (ADI_UART_HANDLE const hDevice, const void *const pData, int16_t *pSize)
Transmits data on UART.
ADI_UART_RESULT_TYPE adi_UART_Enable (ADI_UART_HANDLE const hDevice, const bool_t bFlag)
Enable UART.
uint32_t adi_UART_GetBaudRate (const ADI_UART_HANDLE hDevice)
Get Baudrate.
bool_t adi_UART_GetBlockingMode (const ADI_UART_HANDLE hDevice)
Get Blocking Mode.
bool_t adi_UART_GetBreakBit (ADI_UART_HANDLE const hDevice)
Get break bit.
bool_t adi_UART_GetDmaMode (const ADI_UART_HANDLE hDevice)
Get DMA Mode.
bool_t adi_UART_GetEnable (const ADI_UART_HANDLE hDevice)
Get Enable.
ADI_UART_RESULT_TYPE adi_UART_GetGenericSettings (ADI_UART_HANDLE const hDevice, ADI_UART_GENERIC_SETTINGS_TYPE *const pSettings)
Get Generic Settings.
bool_t adi_UART_GetInterruptMode (const ADI_UART_HANDLE hDevice)
Get Interrupt Mode.
bool_t adi_UART_GetLoopback (const ADI_UART_HANDLE hDevice)
Get Loopback.
uint16_t adi_UART_GetNumRxBytes (const ADI_UART_HANDLE hDevice)
Checks for the data availability.
uint16_t adi_UART_GetNumTxBytes (const ADI_UART_HANDLE hDevice)
Returns number of bytes that can be transmitted.
ADI_UART_PARITY_TYPE adi_UART_GetParityMode (const ADI_UART_HANDLE hDevice)
Get parity mode.
bool_t adi_UART_GetStickParity (const ADI_UART_HANDLE hDevice)
Get stick parity.
bool_t adi_UART_GetStopBit (ADI_UART_HANDLE const hDevice)
Get Stop bit.
ADI_UART_WLS_TYPE adi_UART_GetWordLength (const ADI_UART_HANDLE hDevice)
Get Word length.
ADI_UART_RESULT_TYPE adi_UART_Init (const ADI_UART_DEV_ID_TYPE devID, ADI_UART_HANDLE *const pHandle, ADI_UART_INIT_DATA *const pInitData)
UART Initialization.
ADI_UART_RESULT_TYPE adi_UART_SetBaudRate (ADI_UART_HANDLE const hDevice, const ADI_UART_BAUDRATE_TYPE BaudRateIndex)
Set Baud Rate.
ADI_UART_RESULT_TYPE adi_UART_SetBlockingMode (ADI_UART_HANDLE const hDevice, const bool_t bFlag)
Set blocking mode.
ADI_UART_RESULT_TYPE adi_UART_SetBreakBit (ADI_UART_HANDLE const hDevice, const bool_t bFlag)
Set Break bit.
ADI_UART_RESULT_TYPE adi_UART_SetDmaMode (ADI_UART_HANDLE const hDevice, const bool_t bFlag)
Enables DMA.
ADI_UART_RESULT_TYPE adi_UART_SetGenericSettings (ADI_UART_HANDLE const hDevice, ADI_UART_GENERIC_SETTINGS_TYPE *const pSettings)
Set Generic Settings.
ADI_UART_RESULT_TYPE adi_UART_SetHandshakeMode (ADI_UART_HANDLE const hDevice, const bool_t bFlag)
ADI_UART_RESULT_TYPE adi_UART_SetInterruptMode (ADI_UART_HANDLE const hDevice, const bool_t bFlag)
Set interrupt mode.
ADI_UART_RESULT_TYPE adi_UART_SetLoopback (ADI_UART_HANDLE const hDevice, const bool_t bFlag)
Set Loopback.
ADI_UART_RESULT_TYPE adi_UART_SetParityMode (ADI_UART_HANDLE const hDevice, const ADI_UART_PARITY_TYPE Parity)
Set parity mode.
ADI_UART_RESULT_TYPE adi_UART_SetStickParity (ADI_UART_HANDLE const hDevice, const bool_t bFlag)
Set Stick parity.
ADI_UART_RESULT_TYPE adi_UART_SetStopBit (ADI_UART_HANDLE const hDevice, const bool_t bFlag)
Set Stop Bit.
ADI_UART_RESULT_TYPE adi_UART_SetWordLength (ADI_UART_HANDLE const hDevice, const ADI_UART_WLS_TYPE WordLength)
Set word length.
ADI_UART_RESULT_TYPE adi_UART_UnInit (ADI_UART_HANDLE const hDevice)
Un-Initialize UART.
Detailed Description
Macro Definition Documentation
#define ASSERT_ADI_MISRA_SUPPRESSIONS
Apply ADI MISRA Suppressions
Definition at line 23 of file uart.c.
#define REVERT_ADI_MISRA_SUPPRESSIONS
Revert ADI MISRA Suppressions
Definition at line 2189 of file uart.c.
Typedef Documentation
typedef struct ADI_UART_DEV_DATA_TYPE* ADI_UART_HANDLE
ADI_UART_HANDLE.
Uart device handle
Definition at line 189 of file uart.h.
Enumeration Type Documentation
enum ADI_UART_BAUDRATE_TYPE
UART default baudrates
Enumerator
ADI_UART_BAUD_9600
baud rate 9600
ADI_UART_BAUD_19200
baud rate 19200
ADI_UART_BAUD_38400
baud rate 38400
ADI_UART_BAUD_57600
baud rate 57600
ADI_UART_BAUD_115200
baud rate 115200
ADI_UART_BAUD_230400
baud rate 230400
ADI_UART_BAUD_460800
baud rate 460800
Definition at line 77 of file uart.h.
enum ADI_UART_DEV_ID_TYPE
UART device identifiers
Enumerator
ADI_UART_DEVID_0
Uart Device ID 0
Definition at line 39 of file uart.h.
enum ADI_UART_DRV_STATE_TYPE
UART driver state
Enumerator
ADI_UART_DRV_STATE_UNKNOWN
UART is not initialized
ADI_UART_DRV_STATE_INITIALIZED
UART driver initialized
ADI_UART_DRV_STATE_READY
UART driver is ready
Definition at line 139 of file uart.h.
enum ADI_UART_PARITY_TYPE
UART parity mode
Enumerator
ADI_UART_PARITY_NONE
parity is disabled
ADI_UART_PARITY_ODD
odd parity
ADI_UART_PARITY_EVEN
even parity
Definition at line 50 of file uart.h.
enum ADI_UART_RESULT_TYPE
UART result codes
Enumerator
ADI_UART_SUCCESS
generic success
ADI_UART_ERR_UNKNOWN
generic error
ADI_UART_ERR_ALREADY_INITIALIZED
device initialized
ADI_UART_ERR_INVALID_INSTANCE
given instance is invalid
ADI_UART_ERR_INVALID_DEVID
invalid device id
ADI_UART_ERR_INVALID_PARAMS
invalid parameters
ADI_UART_ERR_NOT_SUPPORTED
unsupported operation
ADI_UART_ERR_NOT_INITIALIZED
device not initialized
ADI_UART_ERR_GPIO_CONFIG_FAILED
GPIO configuration failed
ADI_UART_ERR_INVALID_BUFFER
invalid or no buffer
ADI_UART_ERR_SEMAPHORE_FAILED
semaphore-related error
Definition at line 118 of file uart.h.
enum ADI_UART_WLS_TYPE
UART Word or Data length
Enumerator
ADI_UART_WLS_5
word length of 5 bits
ADI_UART_WLS_6
word length of 6 bits
ADI_UART_WLS_7
word length of 7 bits
ADI_UART_WLS_8
word length of 8 bits
Definition at line 63 of file uart.h.
Function Documentation
ADI_UART_RESULT_TYPE adi_UART_BufFlush (ADI_UART_HANDLE const hDevice)
Flush UART FIFOS.
Parameters
[in] hDevice Handle to the device which is returned through adi_UART_Init()
Returns
Status
ADI_UART_SUCCESS upon success
ADI_UART_ERR_INVALID_INSTANCE [D] if invalid instance handle is passed
ADI_UART_ERR_NOT_INITIALIZED [D] if driver is not initialized
                   Performs a dummy read if data is present in rx fifo. Also waits for the
                   pending transmit operations to finish. Reset the internal driver buffer
                   entities to their default values.
See Also
adi_UART_Enable
Definition at line 1153 of file uart.c.
ADI_UART_RESULT_TYPE adi_UART_BufRx (ADI_UART_HANDLE const hDevice, const void * pData, int16_t * pSize)
Receives Data from UART.
Parameters
[in] hDevice Handle to the device which is returned through adi_UART_Init()
[out] pData Pointer to the memory where received bytes are stored
[in,out] pSize Pointer to a location where number of bytes to be received is specified.
Returns
Status
ADI_UART_SUCCESS upon success
ADI_UART_ERR_INVALID_PARAMS [D] if invalid parameters are passed
ADI_UART_ERR_INVALID_INSTANCE [D] if invalid instance handle is passed
                   Receives data from the UART. Actual reception of data is dependent on the
                   operational mode of the driver. Applications can se the driver to operate in
                   blocking or non-blocking modes. Driver can be configured to use poll, interrupt
                   or dma in conjuction with the operating modes.
                   Blocked and Non-blocking modes:
                   In blocking mode this api will wait until entire data is obtained. In case of
                   non-blocking mode this api returns immediately by obtaining data completely or
                   partially or with no data. In non-blocking mode pSize will be changed with the
                   number of bytes that are successfully received. In blocking mode pSize parameter
                   is not changed.
                   Both blocking and non-blocking modes can be used in conjuction with interrupt
                   or polling configurations. In case of interrupt mode UART receive interrupt is
                   enabled and upon each receive buffer full interrupt a byte is fetched from the
                   RX FIFO and stored in the internal buffer. Once internal buffer is full any incoming
                   data is discarded. Applications can configure the size of the rx internal buffer using
                   \e pRxBufferData, \e RxBufferSize members of #ADI_UART_INIT_DATA. This data structure is
                   taken as input in #adi_UART_Init call. In interrupt mode data is accumulated in to
                   the internal buffer once UART is enabled. So applications need not explicitly invoke
                   this API to trigger the receive operation. In case of polled configuration internal
                   buffer is not used and data is not accumulated. Applications have to explicitly issue
                   this API inorder to receive data. In polled configuration at mode one byte
                   can be accumulated as the FIFO length is one byte.
                   Applications can use adi_UART_GetNumRxBytes() call to get number of bytes that are
                   available to read. In case of interrupt configuration this API returns the number of
                   bytes avaiable in the internal buffer where as in case of polled  operation it returns
                   the number of bytes in the FIFO.
                   Following sections describe the different operating modes and configurations in detail.
                   Blocked-polling Mode:
                   In blocked-polling mode this API will not return until entire data is completely obtained.
                   In polling configuration devices status register is used to determine the success of the
                   transfer. Internal buffering is not used so application's buffer is directly used to store
                   the incoming data. No memory copies are used in this mode. Data is not accumulated, so
                   active adi_UART_BufRx will read data in to application buffer. UART has one byte FIFO so
                   at most one byte is held if there is no active read.
                   Blocked-interrupt Mode:
                   In blocked interrupt mode this API will not return until entire data is obtained. In
                   interrupt mode UART receive buffr full interrupt is used to get the next byte. Internal
                   buffering is used in interrupt mode so received data gets accumulated as soon as UART is
                   enabled. If internal buffer has greater than or equal to the requested number of bytes then
                   this API immediately returns with the data.Applications has to configure the size of the
                   rx internal buffer using \e pRxBufferData, \e RxBufferSize members of #ADI_UART_INIT_DATA.
                   This data structure is taken as input in #adi_UART_Init call.
                   Nonblocked-polling Mode:
                   In non-blocked polling mode, this API returns immediately by receiving data fully or
                   partially or with no data. pSize parameter is changed reflecting the number of successfully
                   received bytes. Internal buffering is not used in polled mode so at most one byte be received
                   in a single receive call. If data is not available by the time this call is issued pSize is
                   set to zero. In this mode devices status registers are used to determine the success of the
                   operation.
                   NonBlocked-Interrupt Mode:
                   In non-blocked polling mode, this API returns immediately by receiving data fully or
                   partially or with no data. pSize parameter is changed reflecting the number of bytes that
                   are successfully received. In interrupt mode internal buffering is enabled so data can be
                   accumulated once UART is enabled. The data present in the internal buffer is used for the
                   read request.
Note
Applications has to configure the size of the rx internal buffer using pRxBufferData, RxBufferSize members of ADI_UART_INIT_DATA. This data structure is taken as input in adi_UART_Init call. The rx buffer size is dependent on the application requirements and other system latencies. Applications must enable UART using adi_UART_Enable before using this API.
Side-Effects:
In non-blocking mode *pSize parameter is changed with the number of bytes that are actually transmitted.
See Also
adi_UART_Init
adi_UART_BufTx
adi_UART_GetNumRxBytes
Definition at line 1106 of file uart.c.
ADI_UART_RESULT_TYPE adi_UART_BufTx (ADI_UART_HANDLE const hDevice, const void *const pData, int16_t * pSize)
Transmits data on UART.
Parameters
[in] hDevice Handle to the device which is returned through adi_UART_Init()
[in] pData Data pointer which points to the to-be transmitted data.
[in,out] pSize Pointer to a location where number of bytes to be transmitted is specified.
Returns
Status
ADI_UART_SUCCESS upon success
ADI_UART_ERR_INVALID_PARAMS if invalid parameters are passed
ADI_UART_ERR_INVALID_INSTANCE [D] if invalid instance handle is passed
ADI_UART_ERR_NOT_INITIALIZED [D] if device is not initialized
                   Transmits data over UART. Actual data transmission is dependent on the operational
                   mode of the driver. Application can set the driver to operate in blocking or non-blocking
                   modes. Driver can be configured to use poll, interrupt or dma in conjuction with the
                   operating modes.
                   Blocking and Non-Blocking Modes:
                   In blocking mode, this api will not return until entire data is transmitted. In case of
                   non-blocking mode, this api returns immediately by transmitting the data completely
                   or partially or without transmitting any data. In non-blocking mode pSize parameter is modified
                   to reflect the number of bytes successfully transmitted.
                   Both blocking and non-blocking modes can be used in conjuction with interrupt or polling
                   configuration of the driver. In case of interrupt mode UART transmit interrupt is enabled
                   and upon each transmit buffer empty interrupt a byte is fetched from internal driver buffer
                   and transmitted on UART. In interrupt mode application data is copied in to driver's internal
                   buffer.Applications have to carefully configure the tx internal buffer by using \e pTxBufferData
                   and \e TxBufferSize which are members of #ADI_UART_INIT_DATA. This is input parameter for
                   adi_UART_Init API.
                   In interrupt mode applications can not write more than supplied buffer size of data in a
                   single transmit call. As internal buffers are used by the time this call returns entire data
                   might not have been transmitted on UART.
                   In case of polled configuration status bits are used to determine the successful transfer.
                   Internal buffers are not used in polled mode and by the time this API returns entire data is
                   transmitted over UART.
                   Applications can use adi_UART_GetNumTxBytes() call to get number of bytes that can be
                   successfully transmitted.
                   Following sections describe the different operating modes and configurations in detail.
                   Blocked-Polling Mode:
                   In blocked polling mode, this API will not return until entire data is transmitted.
                   In polling mode UART devices status register is used to check success of the transmit.
                   Internal buffering is not used in polling mode so application data buffer is directly
                   by the driver.No memory copies are used in this mode. By the time this API returns
                   entire data is successfully transmitted.
                   Blocked-Interrupt Mode:
                   In blocked interrupt mode, this API will not return until entire data is transmitted.
                   In interrupt mode UART transmit buffer empty interrupt is used to check success of the
                   transmit. Internal buffering is used in this mode.Application data is copied in to
                   internal drivers data buffer and the call is returned. Upon each transmit buffer empty
                   interrupt a byte is sent over UART. Because of the buffering by the time this call returns
                   entire data might not have been sent over UART.Applications can reuse the data buffer as
                   soon as the API returns. In this mode a single transmit operations should not write more
                   than the size of supplied internal buffer.
                   NonBlocked-Polling Mode:
                   In non-blocked polling mode, this API returns immediately by transmitting data fully
                   or partially or none. pSize parameter is changed in this mode reflecting the number of
                   bytes transmitted.Internal buffering is not used in polled mode, so in this mode atmost
                   one byte can be sent in a single transmit call. If transmit FIFO is not empty then the
                   driver can not transmit any data so it returns by setting the pSize to zero. In the
                   polling mode interrupts are not used and devices status registers are used to determine
                   the success of the operation.
                   NonBlocked-Interrupt Mode:
                   In non-blocked interrupt mode, this API returns immediately by transmitting data fully
                   or partially or none. pSize parameter is changed by reflecting the number of bytes
                   transmitted.Internal buffering is used in interrupt mode, so in this application data
                   is copied into internal driver buffer to the extent that is available. If incoming request
                   is larger than available internal space then data is partially copied to the internal buffer.
                   Upon each transmit buffer empty interrupt a byte is sent. pSize parameter is changed
                   according to the number of bytes that are buffered. As internal buffering is used by the
                   time this call returns data might not have been transmitted completely on UART.
                   Applications can re-use its buffer as soon as this call returns.
                   NonBlocked-Interrupt mode is best suited for applications that has parallel receive and
                   transmit operations.
Note
Applications has to carefully configure the transmit buffer size depending on the application requirements and also depending on the other system latencies. Applications must enable UART by calling adi_UART_Enable before using this API.
Side-Effects:
In non-blocking mode *pSize parameter is changed with the number of bytes that are actually transmitted. So in non-blocking mode adviced to set this value each time this API is used.
See Also
adi_UART_Init
adi_UART_GetNumTxBytes
adi_UART_SetInterruptMode
adi_UART_SetBlockingMode
adi_UART_SetDmaMode
adi_UART_Enable
adi_UART_BufRx
Definition at line 981 of file uart.c.
ADI_UART_RESULT_TYPE adi_UART_Enable (ADI_UART_HANDLE const hDevice, const bool_t bFlag)
Enable UART.
Parameters
[in] hDevice Handle to the device which is returned through adi_UART_Init()
[in] bFlag Flag is true then UART is enabled, if it is false then UART is disabled
Returns
Status
ADI_UART_SUCCESS upon success
ADI_UART_ERR_INVALID_INSTANCE [D] if invalid instance handle is passed
See Also
adi_UART_GetEnable
Definition at line 1834 of file uart.c.
uint32_t adi_UART_GetBaudRate (const ADI_UART_HANDLE hDevice)
Get Baudrate.
Parameters
[in] hDevice Handle to the device which is returned through adi_UART_Init()
Returns
Returns current baud rate
                   Returns the current baud rate. The returned value might be different from the
                   value set by adi_UART_SetBaudRate API. This API computes the baud rate from the
                   COMDIV, fractional baud rate register values.
See Also
adi_UART_SetBaudRate
Definition at line 1314 of file uart.c.
Referenced by adi_UART_GetGenericSettings().
bool_t adi_UART_GetBlockingMode (const ADI_UART_HANDLE hDevice)
Get Blocking Mode.
Parameters
[in] hDevice Handle to the device which is returned through adi_UART_Init()
Returns
True if driver is operating in blocking mode False if driver is operating in non-blocking mode
Returns true if driver is operating in blocking mode, false if driver is operating in non-blocking mode.
See Also
adi_UART_SetBlockingMode
Definition at line 2012 of file uart.c.
Referenced by adi_UART_GetGenericSettings().
bool_t adi_UART_GetBreakBit (ADI_UART_HANDLE const hDevice)
Get break bit.
Parameters
[in] hDevice Handle to the device which is returned through adi_UART_Init()
Returns
True if break bit is enabled false otherwise
Returns true if break bit is enabled.
See Also
adi_UART_SetBreakBit
Definition at line 1605 of file uart.c.
bool_t adi_UART_GetDmaMode (const ADI_UART_HANDLE hDevice)
Get DMA Mode.
Parameters
[in] hDevice Handle to the device which is returned through adi_UART_Init()
Returns
True if DMA is enabled False if DMA is disabled
                   Returns true if driver is operating in loopback mode.
See Also
adi_UART_SetDmaMode
Definition at line 1815 of file uart.c.
Referenced by adi_UART_GetGenericSettings().
bool_t adi_UART_GetEnable (const ADI_UART_HANDLE hDevice)
Get Enable.
Parameters
[in] hDevice Handle to the device which is returned through adi_UART_Init()
Returns
True if uart is enabled False if uart is disabled
See Also
adi_UART_Enable
Definition at line 1867 of file uart.c.
ADI_UART_RESULT_TYPE adi_UART_GetGenericSettings (ADI_UART_HANDLE const hDevice, ADI_UART_GENERIC_SETTINGS_TYPE *const pSettings)
Get Generic Settings.
Parameters
[in] hDevice Handle to the device which is returned through adi_UART_Init()
[in] pSettings Pointer to the memory location where the current setting will be returned.
Returns
Status
ADI_UART_SUCCESS upon success
ADI_UART_ERR_INVALID_INSTANCE [D] if invalid instance handle is passed
ADI_UART_ERR_NOT_INITIALIZED [D] if driver is not initialized
ADI_UART_ERR_INVALID_PARAMS [D] if invalid parameters were passed
                   Generic UART settings can be retrieved using this API. The generic settings
                   include baud rate, word length, parity. Driver operating mode could also be
                   retrieved using this API.
Note
Note that this API will not return the enumerated BaudRate but rather computes the actual configured baudrate and returns using ConfiguredBaudRate parameter. BaudRate member will not be set.
See Also
adi_UART_SetGenericSettings
adi_UART_Enable
Definition at line 1422 of file uart.c.
bool_t adi_UART_GetInterruptMode (const ADI_UART_HANDLE hDevice)
Get Interrupt Mode.
Parameters
[in] hDevice Handle to the device which is returned through adi_UART_Init()
Returns
True if driver is operating in interrupt mode False if driver is operating in polled mode (default)
Returns true if driver is operating in interrupt mode, false if driver is operating in polling mode.
See Also
adi_UART_SetInterruptMode
Definition at line 1958 of file uart.c.
Referenced by adi_UART_GetGenericSettings().
bool_t adi_UART_GetLoopback (const ADI_UART_HANDLE hDevice)
Get Loopback.
Parameters
[in] hDevice Handle to the device which is returned through adi_UART_Init()
Returns
True if driver is operating in loopback mode else False is returned.
                   Returns true if driver is operating in loopback mode. False if driver is not
                   operating in loopback mode. In loopback mode transmitted bytes are put on
                   receive channel of the UART.
See Also
adi_UART_SetLoopback
Definition at line 1497 of file uart.c.
uint16_t adi_UART_GetNumRxBytes (const ADI_UART_HANDLE hDevice)
Checks for the data availability.
Parameters
[in] hDevice Handle to the device which is returned through adi_UART_Init()
Returns
0 if no data is availble or number of bytes available
In case of interrupt mode the number of bytes accumulated in the buffer were returned. In case of polling mode at most one byte can present in the receive fifo. So in polling mode this call may return 0 if there is no data in the fifo or 1 if a byte is present in the rx fifo.
See Also
adi_UART_GetNumTxBytes
adi_UART_BufRx
Definition at line 2092 of file uart.c.
uint16_t adi_UART_GetNumTxBytes (const ADI_UART_HANDLE hDevice)
Returns number of bytes that can be transmitted.
Parameters
[in] hDevice Handle to the device which is returned through adi_UART_Init()
Returns
0 if none can be transmitted number of bytes that can be transmitted
Definition at line 2125 of file uart.c.
ADI_UART_PARITY_TYPE adi_UART_GetParityMode (const ADI_UART_HANDLE hDevice)
Get parity mode.
Parameters
hDevice Handle to the device which is returned through adi_UART_Init()
Returns
Returns the enumeration specifying the current parity Valid Parity values are
ADI_UART_PARITY_NONE
ADI_UART_PARITY_ODD
ADI_UART_PARITY_EVEN
See Also
adi_UART_SetParityMode
Definition at line 1687 of file uart.c.
Referenced by adi_UART_GetGenericSettings().
bool_t adi_UART_GetStickParity (const ADI_UART_HANDLE hDevice)
Get stick parity.
Parameters
[in] hDevice Handle to the device which is returned through adi_UART_Init()
Returns
True if stick parity bit is set False if stick parity bit is cleared
Returns true then uart is using even parity (EPS=1 PEN=1 else uart is using odd parity (EPS=0 and PEN = 1)
See Also
adi_UART_SetStickParity
adi_UART_Enable
Definition at line 2069 of file uart.c.
bool_t adi_UART_GetStopBit (ADI_UART_HANDLE const hDevice)
Get Stop bit.
Parameters
[in] hDevice Handle to the device which is returned through adi_UART_Init()
Returns
True if stop bit is enabled false otherwise
Returns true if stop bits are enabled. Number of stop bits is dependent on the word length.
See Also
adi_UART_SetStopBit
Definition at line 1554 of file uart.c.
ADI_UART_WLS_TYPE adi_UART_GetWordLength (const ADI_UART_HANDLE hDevice)
Get Word length.
Parameters
hDevice Handle to the device which is returned through adi_UART_Init()
Returns
WordLength Enumeration value that specifies the number of bits in a word Valid Parity values are
ADI_UART_WLS_5
ADI_UART_WLS_6
ADI_UART_WLS_7
ADI_UART_WLS_8
See Also
adi_UART_SetWordLength
Definition at line 1767 of file uart.c.
Referenced by adi_UART_GetGenericSettings().
ADI_UART_RESULT_TYPE adi_UART_Init (const ADI_UART_DEV_ID_TYPE devID, ADI_UART_HANDLE *const pHandle, ADI_UART_INIT_DATA *const pInitData)
UART Initialization.
Parameters
[in] devID Enumerated UART device identifier. This id is used to open the correct instance of the peripheral. ADI_UART_DEVID_0 is the only allowed value for the systems with a single UART.
[out] pHandle Points to the location where the device handle will be stored upon successful initialization.
[in] pInitData Pointer to the ADI_UART_INIT_DATA stucture. Application uses this structure to supply initialization parameters to the init function. If NULL is passed then UART driver operates in polling mode by polling the status bits. With valid receive and transmit buffers the driver operates in interrupt mode with internal buffering.
Returns
Status
ADI_UART_SUCCESS upon success
ADI_UART_ERR_INVALID_DEVID [D] if invalid device id is passed
ADI_UART_ERR_ALREADY_INITIALIZED [D] if the uart is already initialized
ADI_UART_ERR_INVALID_BUFFER [D] pInitData contains invalid buffer(s)
                   Initializes and configures UART. Upon successful initialization a handle
                   to the device is stored in the supplied pHandle.Applications must use this
                   handle value in all subsequent api calls to this device. Device initialization
                   includes configuring the GPIO pins, setting up UART with default baudrate,word
                   length, parity and stop bits. Two buffers one for receive and one for transmit
                   were also initialized.
                   Init call sets up UART with default initialization values.Default UART values are
                   baud rate -> 9600, word length -> 8, parity -> none, stop bits -> 1.
                   Default initialization values for UART are controlled through the following macros
                   in the UART header file.
                   - #ADI_UART_COMLCR_INITIALIZER   configure word length and stop bits.
                   - #ADI_UART_BAUD_9600            default baud rate
Note
Init call does not enable the UART device. Once configuration and other setup is complete applications has to explicitly enable UART via adi_UART_Enable call. Once UART is enabled changing the UART configuration such as baudrate, wordlength, operating mode (interrupt,poll, or dma) may result in un-desired behavior. Applications must disable UART before changing UART configuration and enable UART after setting the new configuration.
See Also
adi_UART_UnInit
adi_UART_Enable
Definition at line 739 of file uart.c.
ADI_UART_RESULT_TYPE adi_UART_SetBaudRate (ADI_UART_HANDLE const hDevice, const ADI_UART_BAUDRATE_TYPE BaudRateIndex)
Set Baud Rate.
Parameters
[in] hDevice Handle to the device which is returned through adi_UART_Init()
[in] BaudRateIndex Specifies the baud rate index
Returns
Status
ADI_UART_SUCCESS upon success
ADI_UART_ERR_INVALID_INSTANCE [D] if invalid instance handle is passed
ADI_UART_ERR_NOT_INITIALIZED [D] if driver is not initialized
ADI_UART_ERR_INVALID_PARAMS [D] if invalid parameters were passed
                   Configures relevent UART registers pertaining to the given buad rate.
                   ADI_UART_BAUDRATE_TYPE enumeration defines the currently supported baud rates.
Note
Custom baud rate configuration is not supported, direct access to the COMDIV or fractional baud rate registers is not supported. DIVM and DIVN values for the standard baudrates is chosen from the specification. Applications must disable UART prior to changing the baud rate and then re-enable it after setting it. UART can be enabled or disabled using adi_UART_Enable API.
See Also
adi_UART_GetBaudRate
adi_UART_Enable
Definition at line 1207 of file uart.c.
Referenced by adi_UART_Init(), and adi_UART_SetGenericSettings().
ADI_UART_RESULT_TYPE adi_UART_SetBlockingMode (ADI_UART_HANDLE const hDevice, const bool_t bFlag)
Set blocking mode.
Parameters
[in] hDevice Handle to the device which is returned through adi_UART_Init()
[in] bFlag if true driver operates in blocking mode. if false driver operates in non-blocking mode.
Returns
Status
ADI_UART_SUCCESS upon success
ADI_UART_ERR_INVALID_INSTANCE [D] if invalid instance handle is passed
Puts the driver in blocking mode. In Blocking mode receive and transmit APIs will not return until requested data has been received or transmitted.
Note
Applications has to disable UART before changing the blocking mode and re-enable it after changing.
See Also
adi_UART_GetBlockingMode
adi_UART_Enable
Definition at line 1984 of file uart.c.
Referenced by adi_UART_SetGenericSettings().
ADI_UART_RESULT_TYPE adi_UART_SetBreakBit (ADI_UART_HANDLE const hDevice, const bool_t bFlag)
Set Break bit.
Parameters
[in] hDevice Handle to the device which is returned through adi_UART_Init()
[in] bFlag If bFlag is true then break bit is set, if false then break control is disabled
Returns
Status
ADI_UART_SUCCESS upon success
ADI_UART_ERR_INVALID_INSTANCE [D] if invalid instance handle is passed
Set by user to force the TxD to 0. Applications must disable UART before setting the break bit and re-enable after setting it. UART can be enabled or disabled by using adi_UART_Enable API.
See Also
adi_UART_GetBreakBit
adi_UART_Enable
Definition at line 1577 of file uart.c.
ADI_UART_RESULT_TYPE adi_UART_SetDmaMode (ADI_UART_HANDLE const hDevice, const bool_t bFlag)
Enables DMA.
Parameters
[in] hDevice Handle to the device which is returned through adi_UART_Init()
[in] bFlag if bFlag is true then the driver uses DMA to transfer data
Returns
Status
ADI_UART_SUCCESS upon success
ADI_UART_ERR_INVALID_INSTANCE [D] if invalid instance handle is passed
                   Enables DMA with in the driver
See Also
adi_UART_GetDmaMode
adi_UART_Enable
Definition at line 1789 of file uart.c.
ADI_UART_RESULT_TYPE adi_UART_SetGenericSettings (ADI_UART_HANDLE const hDevice, ADI_UART_GENERIC_SETTINGS_TYPE *const pSettings)
Set Generic Settings.
Parameters
[in] hDevice Handle to the device which is returned through adi_UART_Init()
[in] pSettings Pointer to the generic settings
Returns
Status
ADI_UART_SUCCESS upon success
ADI_UART_ERR_INVALID_INSTANCE [D] if invalid instance handle is passed
ADI_UART_ERR_NOT_INITIALIZED [D] if driver is not initialized
ADI_UART_ERR_INVALID_PARAMS [D] if invalid parameters were passed
                   Generic UART settings can be changed using this API. The generic settings
                   include baud rate, word length, parity. Driver operating mode could also be
                   changed using this API. This API has to be called only when UART is disabled and
                   re-enable UART once new settings are set.
Side-Effects: This API uses the passed in values, so all elements of ADI_ADC_DEV_GENERIC_SETTINGS_TYPE
structure must be initialized to the desired values else they may get propaged with un-intended values.
See Also
adi_UART_GetGenericSettings
adi_UART_Enable
Definition at line 1356 of file uart.c.
ADI_UART_RESULT_TYPE adi_UART_SetInterruptMode (ADI_UART_HANDLE const hDevice, const bool_t bFlag)
Set interrupt mode.
Parameters
[in] hDevice Handle to the device which is returned through adi_UART_Init()
[in] bFlag Specifies the driver interrupt mode. If true driver operates in interrupt mode else it operates in polling mode.
Returns
Status
ADI_UART_SUCCESS upon success
ADI_UART_ERR_INVALID_INSTANCE [D] if invalid instance handle is passed
ADI_UART_ERR_INVALID_BUFFER [D] if buffers are not supplied in adi_UART_Init
                   Set interrupt mode API allows applications to change the driver operating mode
                   to interrupt. By default driver operates in polled mode where status registers
                   are used to determine the transfer completion. In interrupt mode interrupts are
                   used for transmitting or receiving data. Transmit and receive operations can be
                   carried out in interrupt mode. The advantage of interrupt mode is data is transmitted
                   or received asynchronously. In case of receive operations, data is accumulated into
                   an internal driver buffer upon each rx interrupt. When application issues BufRx api
                   this data is copied to user buffer.  Similarly, transmitted data is copied to drivers
                   internal data buffer and upon each transmit empty interrupt another byte is sent across.
                   Interrupt mode is more efficient as it reduces the processor loading. Applications can
                   use either interrupt mode or polled mode. Both transmit and receive operations will use
                   the same mode, i.e either polling mode or interrupt mode.
Note
Applications has to disable UART before changing the interrupt mode and re-enable it after changing.
See Also
adi_UART_GetInterruptMode
adi_UART_Enable
Definition at line 1905 of file uart.c.
Referenced by adi_UART_SetGenericSettings().
ADI_UART_RESULT_TYPE adi_UART_SetLoopback (ADI_UART_HANDLE const hDevice, const bool_t bFlag)
Set Loopback.
Parameters
[in] hDevice Handle to the device which is returned through adi_UART_Init()
[in] bFlag True then the driver operates in loopback mode
Returns
Status
ADI_UART_SUCCESS upon success
ADI_UART_ERR_INVALID_INSTANCE [D] if invalid instance handle is passed
                   Sets the driver to operate in loopback mode. This mode can be used with
                   out a UART cable connected to host pc or hyperterminal. Applications must
                   disable UART prior to changing the loopback mode and re-enable it after
                   setting the value. UART can be enabled or disabled using adi_UART_Enable API.
See Also
adi_UART_GetLoopback
adi_UART_Enable
Definition at line 1466 of file uart.c.
ADI_UART_RESULT_TYPE adi_UART_SetParityMode (ADI_UART_HANDLE const hDevice, const ADI_UART_PARITY_TYPE Parity)
Set parity mode.
Parameters
[in] hDevice Handle to the device which is returned through adi_UART_Init()
[in] Parity Enumeration value that specifies the parity that needs to be set
                   Valid Parity values are
                   - #ADI_UART_PARITY_NONE
                   - #ADI_UART_PARITY_ODD
                   - #ADI_UART_PARITY_EVEN
Returns
Status
ADI_UART_SUCCESS upon success
ADI_UART_ERR_INVALID_INSTANCE [D] if invalid instance handle is passed
                   API is used to set the parity. Supported parity values are enumerated using the
                   ADI_UART_PARITY_TYPE. If odd or even parity is selected parity is automatically
                   enabled. This api does not force the parity,i.e stick parity bit of COMLCR is not
                   changed by this API. Applications has to disable UART prior to setting the parity
                   mode and re-enable UART after setting the parity mode. UART can be enabled or disabled
                   by adi_UART_Enable API.
See Also
adi_UART_GetParityMode
adi_UART_Enable
Definition at line 1638 of file uart.c.
Referenced by adi_UART_SetGenericSettings().
ADI_UART_RESULT_TYPE adi_UART_SetStickParity (ADI_UART_HANDLE const hDevice, const bool_t bFlag)
Set Stick parity.
Parameters
[in] hDevice Handle to the device which is returned through adi_UART_Init()
[in] bFlag If true stick parity bit is set, else stick parity is cleared.
Returns
Status
ADI_UART_SUCCESS upon success
ADI_UART_ERR_INVALID_INSTANCE if invalid instance handle is passed
                   Stick parity (SP) bit of COMLCR forces the parity to the defined values
                   SP is 1 if EPS = 1 and PEN = 1  (Even parity )
                   SP is 0 if EPS = 0 and PEN = 1  (Odd  parity )
Note
Applications and issue transmit and receive only after UART is enabled.
See Also
adi_UART_GetStickParity
adi_UART_Enable
Definition at line 2038 of file uart.c.
ADI_UART_RESULT_TYPE adi_UART_SetStopBit (ADI_UART_HANDLE const hDevice, const bool_t bFlag)
Set Stop Bit.
Parameters
[in] hDevice Handle to the device which is returned through adi_UART_Init()
[in] bFlag If bFlag is true then STOP bit is enabled, if false then stop bit is disabled
Returns
Status
ADI_UART_SUCCESS upon success
ADI_UART_ERR_INVALID_INSTANCE [D] if invalid instance handle is passed
                   Enables or disables stop bit. Number of stop bits used depends on the word length (WL)
                   # WL of 5 bits - 1.5 stop bits
                   # WL of 6,7,8 bits - 2 stop bits
Note
Hardware generates the required number of stop bits depending on the word length when stop enable bit is set in comlcr. Applications must disable UART prior to setting the stop bit and re-enable it after setting. UART can be enabled or disabled using adi_UART_Enable API.
See Also
adi_UART_GetStopBit
Definition at line 1525 of file uart.c.
ADI_UART_RESULT_TYPE adi_UART_SetWordLength (ADI_UART_HANDLE const hDevice, const ADI_UART_WLS_TYPE WordLength)
Set word length.
Parameters
hDevice Handle to the device which is returned through adi_UART_Init()
WordLength Enumeration value that specifies the number of bits in a word Valid Parity values are
ADI_UART_WLS_5
ADI_UART_WLS_6
ADI_UART_WLS_7
ADI_UART_WLS_8
Returns
Status
ADI_UART_SUCCESS upon success
ADI_UART_ERR_INVALID_INSTANCE [D] if invalid instance handle is passed
ADI_UART_ERR_INVALID_PARAMS [D] if invalid parameter is passed
             set word length select bits.
See Also
adi_UART_GetWordLength
Definition at line 1721 of file uart.c.
Referenced by adi_UART_SetGenericSettings().
ADI_UART_RESULT_TYPE adi_UART_UnInit (ADI_UART_HANDLE const hDevice)
Un-Initialize UART.
Parameters
[in] hDevice Handle to the device which is returned through adi_UART_Init()
Returns
Status
ADI_UART_SUCCESS upon success
ADI_UART_ERR_INVALID_INSTANCE [D] if invalid instance handle is passed
ADI_UART_ERR_NOT_INITIALIZED [D] if device is not initialized
                   Closes UART device and resets it's internal structures. After closing
                   the device it can be initialized again. Uninit disables UART interrupt.
                   This call also puts UART in unknown state.Transmit and receive operations
                   will result in error after UART is un-initialized.
See Also
adi_UART_Init
adi_UART_Enable
Definition at line 844 of file uart.c.