ADuCM350BBCZ Device Drivers API Reference Manual: CT_Driver
CT_Driver
Data Structures
struct ADI_CT_AVERAGE_TYPE
struct ADI_CT_BASELINE_TYPE
struct ADI_CT_C2V_TIMING_TYPE
struct ADI_CT_GENERIC_SETTINGS_TYPE
struct ADI_CT_PK2PK_TYPE
struct ADI_CT_TOUCH_AND_RELEASE_TYPE
struct ADI_STAGE_TYPE
Macros
#define ADI_CT_INTERRUPT_MASK
#define ADI_CT_STATUS_BIT_A (1 << 0)
#define ADI_CT_STATUS_BIT_B (1 << 1)
#define ADI_CT_STATUS_BIT_C (1 << 2)
#define ADI_CT_STATUS_BIT_D (1 << 3)
#define ADI_CT_STATUS_BIT_E (1 << 4)
#define ADI_CT_STATUS_BIT_F (1 << 5)
#define ASSERT_ADI_MISRA_SUPPRESSIONS
Typedefs
typedef void(* ADI_CT_CALLBACK_TYPE)(ADI_CT_INTERRUPT_TYPE const statusBits)
ADI_CT_CALLBACK_TYPE.
typedef struct
ADI_CT_DEV_DATA_TYPE * ADI_CT_DEV_HANDLE
ADI_CT_DEV_HANDLE.
Enumerations
enum ADI_CT_AUTOZERODUTY_TYPE {
ADI_CT_AUTOZERO_DUTY_2us,
ADI_CT_AUTOZERO_DUTY_3us,
ADI_CT_AUTOZERO_DUTY_4us,
ADI_CT_AUTOZERO_DUTY_5us,
ADI_CT_AUTOZERO_DUTY_6us,
ADI_CT_AUTOZERO_DUTY_7us,
ADI_CT_AUTOZERO_DUTY_8us,
ADI_CT_AUTOZERO_DUTY_9us
}
enum ADI_CT_AVG_OUTPUT_TYPE {
ADI_CT_AVG_OUTPUT_NO_AVG,
ADI_CT_AVG_OUTPUT_GROUP1,
ADI_CT_AVG_OUTPUT_GROUP2,
ADI_CT_AVG_OUTPUT_GROUP1_2
}
enum ADI_CT_AVG_SAMPLES_TYPE {
ADI_CT_AVG_SAMPLES_NO_AVG,
ADI_CT_AVG_SAMPLES_2_SAMPLES,
ADI_CT_AVG_SAMPLES_4_SAMPLES,
ADI_CT_AVG_SAMPLES_8_SAMPLES,
ADI_CT_AVG_SAMPLES_16_SAMPLES,
ADI_CT_AVG_SAMPLES_32_SAMPLES
}
enum ADI_CT_BASELINE_CAL_DELAY_TYPE {
ADI_CT_BASELINE_CAL_DELAY_FAST_FILTER_UPDATE_8,
ADI_CT_BASELINE_CAL_DELAY_FAST_FILTER_UPDATE_16,
ADI_CT_BASELINE_CAL_DELAY_FAST_FILTER_UPDATE_24,
ADI_CT_BASELINE_CAL_DELAY_FAST_FILTER_UPDATE_32,
ADI_CT_BASELINE_CAL_DELAY_FAST_FILTER_UPDATE_40,
ADI_CT_BASELINE_CAL_DELAY_FAST_FILTER_UPDATE_48,
ADI_CT_BASELINE_CAL_DELAY_FAST_FILTER_UPDATE_56,
ADI_CT_BASELINE_CAL_DELAY_FAST_FILTER_UPDATE_64
}
enum ADI_CT_C2V_BIAS_TYPE {
ADI_CT_C2V_BIAS_6UA,
ADI_CT_C2V_BIAS_7UA,
ADI_CT_C2V_BIAS_8UA,
ADI_CT_C2V_BIAS_9UA,
ADI_CT_C2V_BIAS_10UA,
ADI_CT_C2V_BIAS_11UA,
ADI_CT_C2V_BIAS_12UA,
ADI_CT_C2V_BIAS_13UA
}
enum ADI_CT_C2VRANGE_TYPE {
ADI_CT_C2VRANGE_0_58pF,
ADI_CT_C2VRANGE_1_17pF,
ADI_CT_C2VRANGE_1_75pF,
ADI_CT_C2VRANGE_2_33pF,
ADI_CT_C2VRANGE_2_91pF,
ADI_CT_C2VRANGE_3_49pF,
ADI_CT_C2VRANGE_4_07pF,
ADI_CT_C2VRANGE_4_65pF,
ADI_CT_C2VRANGE_5_23pF,
ADI_CT_C2VRANGE_5_81pF,
ADI_CT_C2VRANGE_6_39pF,
ADI_CT_C2VRANGE_6_97pF,
ADI_CT_C2VRANGE_7_55pF,
ADI_CT_C2VRANGE_8_13pF,
ADI_CT_C2VRANGE_8_74pF,
ADI_CT_C2VRANGE_9_32pF
}
enum ADI_CT_CDC_RESULT_TYPE {
ADI_CT_CDC_RESULT_VALUE,
ADI_CT_CDC_BASELINE_DIFFERENCE_VALUE
}
enum ADI_CT_DEV_ID_TYPE {
ADI_CT_DEV_ID_0 =0,
ADI_CT_DEV_ID_MAXNUM
}
enum ADI_CT_DRV_STATE_TYPE {
ADI_CT_DRV_STATE_UNKNOWN = 0,
ADI_CT_DRV_STATE_INITIALIZED,
ADI_CT_DRV_STATE_READY
}
enum ADI_CT_FAST_FILTER_UPDATE_TYPE {
ADI_CT_FAST_FILTER_UPDATE_2ND_CONVERSION_CYCLE,
ADI_CT_FAST_FILTER_UPDATE_4TH_CONVERSION_CYCLE,
ADI_CT_FAST_FILTER_UPDATE_6TH_CONVERSION_CYCLE,
ADI_CT_FAST_FILTER_UPDATE_8TH_CONVERSION_CYCLE,
ADI_CT_FAST_FILTER_UPDATE_10TH_CONVERSION_CYCLE,
ADI_CT_FAST_FILTER_UPDATE_12TH_CONVERSION_CYCLE,
ADI_CT_FAST_FILTER_UPDATE_14TH_CONVERSION_CYCLE,
ADI_CT_FAST_FILTER_UPDATE_16TH_CONVERSION_CYCLE
}
enum ADI_CT_INDIVIDUAL_THR_ENABLE_TYPE {
ADI_CT_INDIVIDUAL_SENSOR_THR_CFGx_DISABLE,
ADI_CT_INDIVIDUAL_SENSOR_THR_CFGx_ENABLE
}
enum ADI_CT_INPUT_TYPE {
ADI_CT_INPUT_A = 0,
ADI_CT_INPUT_B = 1,
ADI_CT_INPUT_C = 2,
ADI_CT_INPUT_D = 3,
ADI_CT_INPUT_E = 4,
ADI_CT_INPUT_F = 5
}
enum ADI_CT_INT_BUFFER_BIAS_TYPE {
ADI_CT_INT_BUFFER_BIAS_2_5UA,
ADI_CT_INT_BUFFER_BIAS_3UA,
ADI_CT_INT_BUFFER_BIAS_3_5UA,
ADI_CT_INT_BUFFER_BIAS_4UA
}
enum ADI_CT_INTCYCLES_TYPE {
ADI_CT_INT_CYCLES_1,
ADI_CT_INT_CYCLES_2,
ADI_CT_INT_CYCLES_4,
ADI_CT_INT_CYCLES_8,
ADI_CT_INT_CYCLES_16
}
enum ADI_CT_INTERRUPT_TYPE {
ADI_CT_INTERRUPT_NONE,
ADI_CT_INTERRUPT_CONV_SET_COMPLETE = 1 << BITP_CT_CT_IEN_CONV_SET_COMPLETE_IEN,
ADI_CT_INTERRUPT_STATUS_GT_THRESHOLD = 1 << BITP_CT_CT_IEN_STATUS_GT_THRESHOLD_IEN,
ADI_CT_INTERRUPT_PROX_DETECTED = 1 << BITP_CT_CT_IEN_PROX_DETECTED_IEN,
ADI_CT_INTERRUPT_TOUCH_DETECTED = 1 << BITP_CT_CT_IEN_TOUCH_DETECTED_IEN,
ADI_CT_INTERRUPT_RELEASE_DETECTED = 1 << BITP_CT_CT_IEN_RELEASE_DETECTED_IEN
}
enum ADI_CT_PGA_BIAS_TYPE {
ADI_CT_PGA_BIAS_3UA,
ADI_CT_PGA_BIAS_3_5UA,
ADI_CT_PGA_BIAS_4UA,
ADI_CT_PGA_BIAS_4_5UA,
ADI_CT_PGA_BIAS_5UA,
ADI_CT_PGA_BIAS_5_5UA,
ADI_CT_PGA_BIAS_6UA,
ADI_CT_PGA_BIAS_6_5UA
}
enum ADI_CT_PGA_GAIN_TYPE {
ADI_CT_PGA_GAIN_2,
ADI_CT_PGA_GAIN_4,
ADI_CT_PGA_GAIN_8,
ADI_CT_PGA_GAIN_16
}
enum ADI_CT_PK2PK_AVG_TYPE {
ADI_CT_PK2PK_AVG_2_SAMPLES,
ADI_CT_PK2PK_AVG_4_SAMPLES,
ADI_CT_PK2PK_AVG_8_SAMPLES,
ADI_CT_PK2PK_AVG_16_SAMPLES,
ADI_CT_PK2PK_AVG_32_SAMPLES
}
enum ADI_CT_PK2PK_NUM_TYPE {
ADI_CT_PK2PK_NUM_4_SAMPLES,
ADI_CT_PK2PK_NUM_8_SAMPLES,
ADI_CT_PK2PK_NUM_16_SAMPLES,
ADI_CT_PK2PK_NUM_32_SAMPLES
}
enum ADI_CT_RANKING_TYPE {
ADI_CT_RANKING_NO_RANKING,
ADI_CT_RANKING_4_SAMPLES,
ADI_CT_RANKING_8_SAMPLES,
ADI_CT_RANKING_16_SAMPLES,
ADI_CT_RANKING_32_SAMPLES
}
enum ADI_CT_RESULT_TYPE {
ADI_CT_RESULT_SUCCESS = 0,
ADI_CT_RESULT_ERR = ADI_DEV_CT_ERROR_OFFSET,
ADI_CT_RESULT_ERR_CALLBACK_OVERWRITE,
ADI_CT_RESULT_ERR_TCH_REL_NOT_ENABLE
}
enum ADI_CT_STAGE_BIT_TYPE {
ADI_CT_STAGE0_BIT = 1 << ADI_CT_STAGE0_NUMBER,
ADI_CT_STAGE1_BIT = 1 << ADI_CT_STAGE1_NUMBER,
ADI_CT_STAGE2_BIT = 1 << ADI_CT_STAGE2_NUMBER,
ADI_CT_STAGE3_BIT = 1 << ADI_CT_STAGE3_NUMBER,
ADI_CT_STAGE4_BIT = 1 << ADI_CT_STAGE4_NUMBER,
ADI_CT_STAGE5_BIT = 1 << ADI_CT_STAGE5_NUMBER,
ADI_CT_STAGE6_BIT = 1 << ADI_CT_STAGE6_NUMBER,
ADI_CT_STAGE7_BIT = 1 << ADI_CT_STAGE7_NUMBER,
ADI_CT_STAGE8_BIT = 1 << ADI_CT_STAGE8_NUMBER,
ADI_CT_STAGE9_BIT = 1 << ADI_CT_STAGE9_NUMBER,
ADI_CT_STAGE10_BIT = 1 << ADI_CT_STAGE10_NUMBER,
ADI_CT_STAGE11_BIT = 1 << ADI_CT_STAGE11_NUMBER,
ADI_CT_STAGE12_BIT = 1 << ADI_CT_STAGE12_NUMBER,
ADI_CT_STAGE13_BIT = 1 << ADI_CT_STAGE13_NUMBER,
ADI_CT_STAGE14_BIT = 1 << ADI_CT_STAGE14_NUMBER,
ADI_CT_STAGE15_BIT = 1 << ADI_CT_STAGE15_NUMBER
}
enum ADI_CT_STAGE_NUMBER_TYPE {
ADI_CT_STAGE0_NUMBER,
ADI_CT_STAGE1_NUMBER,
ADI_CT_STAGE2_NUMBER,
ADI_CT_STAGE3_NUMBER,
ADI_CT_STAGE4_NUMBER,
ADI_CT_STAGE5_NUMBER,
ADI_CT_STAGE6_NUMBER,
ADI_CT_STAGE7_NUMBER,
ADI_CT_STAGE8_NUMBER,
ADI_CT_STAGE9_NUMBER,
ADI_CT_STAGE10_NUMBER,
ADI_CT_STAGE11_NUMBER,
ADI_CT_STAGE12_NUMBER,
ADI_CT_STAGE13_NUMBER,
ADI_CT_STAGE14_NUMBER,
ADI_CT_STAGE15_NUMBER,
ADI_CT_STAGE_NON_VALID_STAGE
}
enum ADI_CT_TCH_REL_EVENT_ON_HIGH_INPUT_TYPE {
ADI_CT_TCH_REL_EVENT_ON_HIGH_INPUT_INA_INB_DIFF_LESSER_THR,
ADI_CT_TCH_REL_EVENT_ON_HIGH_INPUT_INA_INB_DIFF_GREATER_THR
}
enum ADI_CT_TCH_REL_INPUT_TYPE {
ADI_CT_TCH_REL_INPUT_ALL_ZEROS,
ADI_CT_TCH_REL_INPUT_CDC_VALUE,
ADI_CT_TCH_REL_INPUT_SLOW_FILTER_OUTPUT,
ADI_CT_TCH_REL_INPUT_FAST_FILTER_OUTPUT,
ADI_CT_TCH_REL_INPUT_AMBIENT_VALUE
}
enum ADI_CT_UNMATCHED_PADS_TYPE {
ADI_CT_UNMATCHED_PADS_AC_DRV,
ADI_CT_UNMATCHED_PADS_DC_DRV,
ADI_CT_UNMATCHED_PADS_GND,
ADI_CT_UNMATCHED_PADS_FLOATED
}
Functions
ADI_CT_RESULT_TYPE adi_CT_ClearInterruptFlag (ADI_CT_DEV_HANDLE const hDevice)
Clear the Interrupt Flag.
ADI_CT_RESULT_TYPE adi_CT_GetAverageCfg (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_AVERAGE_TYPE *AverageSettings)
Get the Average Filter Settings.
ADI_CT_RESULT_TYPE adi_CT_GetBaselineCfg (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_BASELINE_TYPE *BaselineSettings)
Get the Baseline Settings.
ADI_CT_RESULT_TYPE adi_CT_GetBaselineValue (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, uint16_t *BaselineResult)
Read the Baseline value of a Stage.
ADI_CT_RESULT_TYPE adi_CT_GetByPassGain (ADI_CT_DEV_HANDLE const hDevice, bool_t *Status)
Bypass the gain for all stages.
ADI_CT_RESULT_TYPE adi_CT_GetC2VBiasCurrent (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_C2V_BIAS_TYPE *C2VBias)
Get the C2V Bias Current.
ADI_CT_RESULT_TYPE adi_CT_GetC2VLowPassFilterEnable (ADI_CT_DEV_HANDLE const hDevice, bool_t *Status)
Get the C2V Low Pass Filter Status.
ADI_CT_RESULT_TYPE adi_CT_GetCDCResultFormat (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_CDC_RESULT_TYPE *ResSel)
Get the Value stored in the CDC_RES register.
ADI_CT_RESULT_TYPE adi_CT_GetCDCValue (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, uint16_t *CDCResult)
Read the CDC value of a Stage.
ADI_CT_RESULT_TYPE adi_CT_GetEnable (ADI_CT_DEV_HANDLE const hDevice, bool_t *Status)
Get the Captouch Pins Status.
ADI_CT_RESULT_TYPE adi_CT_GetFastFilterValue (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, uint16_t *FastFilterResult)
Read the Fast Filter value of a Stage.
ADI_CT_RESULT_TYPE adi_CT_GetFProxStatus (ADI_CT_DEV_HANDLE const hDevice, uint16_t *FProxStatus)
Get the Fast Proximity Status.
ADI_CT_RESULT_TYPE adi_CT_GetIIRFilterEnable (ADI_CT_DEV_HANDLE const hDevice, bool_t *Status)
Get the IIR Filter Status.
ADI_CT_RESULT_TYPE adi_CT_GetIIRFilterWeight (ADI_CT_DEV_HANDLE const hDevice, uint8_t *IIRWeight)
Get the IIR Filter Weight.
ADI_CT_RESULT_TYPE adi_CT_GetIntBufferBiasCurrent (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_INT_BUFFER_BIAS_TYPE *IntBufferBias)
Get the Internal Buffer Bias Current.
ADI_CT_RESULT_TYPE adi_CT_GetIntCycles (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_INTCYCLES_TYPE *IntCycles)
Get the Number of Integration Cycles.
ADI_CT_RESULT_TYPE adi_CT_GetInterruptFlag (ADI_CT_DEV_HANDLE const hDevice, bool_t *EventFlag)
Get the Interrupt Flag.
ADI_CT_RESULT_TYPE adi_CT_GetInterruptsEnable (ADI_CT_DEV_HANDLE const hDevice, uint8_t *CaptouchInterrupts)
Get the CT Interrupt.
ADI_CT_RESULT_TYPE adi_CT_GetInterruptStatus (ADI_CT_DEV_HANDLE const hDevice, uint8_t *EventType)
Get the Interrupt Status.
ADI_CT_RESULT_TYPE adi_CT_GetOffsHStatus (ADI_CT_DEV_HANDLE const hDevice, uint16_t *OffsHStatus)
Get the Offset High Status.
ADI_CT_RESULT_TYPE adi_CT_GetOffsLStatus (ADI_CT_DEV_HANDLE const hDevice, uint16_t *OffsLStatus)
Get the Offset Low Status.
ADI_CT_RESULT_TYPE adi_CT_GetPGABiasCurrent (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_PGA_BIAS_TYPE *PGABias)
Get the PGA Bias Current.
ADI_CT_RESULT_TYPE adi_CT_GetPK2PKCfg (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_PK2PK_TYPE *PK2PK_Settings)
Get the Peak to Peak Parameters.
ADI_CT_RESULT_TYPE adi_CT_GetPK2PKValue (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, uint16_t *PK2PKResult)
Read the Peak to Peak value of a Stage.
ADI_CT_RESULT_TYPE adi_CT_GetPowerStatus (ADI_CT_DEV_HANDLE const hDevice, bool_t *Status)
Get Power Captouch Status.
ADI_CT_RESULT_TYPE adi_CT_GetProxStatus (ADI_CT_DEV_HANDLE const hDevice, uint16_t *ProxStatus)
Get the Slow Proximity Status.
ADI_CT_RESULT_TYPE adi_CT_GetReleaseCfg (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_TOUCH_AND_RELEASE_TYPE *ReleaseSettings)
Get the Release Detection Settings.
ADI_CT_RESULT_TYPE adi_CT_GetReleaseEnable (ADI_CT_DEV_HANDLE const hDevice, bool_t *Status)
Get the Release Detection Status.
ADI_CT_RESULT_TYPE adi_CT_GetSelfTimerEnable (ADI_CT_DEV_HANDLE const hDevice, bool_t *Status)
Get the Self Timer Status.
ADI_CT_RESULT_TYPE adi_CT_GetSelfTimerValue (ADI_CT_DEV_HANDLE const hDevice, uint16_t *SelfTimerWait)
Get the Self Timer Value.
ADI_CT_RESULT_TYPE adi_CT_GetStageByPassPGA (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, bool_t *Status)
Get Bypass PGA Status.
ADI_CT_RESULT_TYPE adi_CT_GetStageC2VRange (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, ADI_CT_C2VRANGE_TYPE *C2VRange)
Get the C2V Range.
ADI_CT_RESULT_TYPE adi_CT_GetStageCAPDACEnable (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, bool_t *Status)
Get the CAPDAC Status for each Stage.
ADI_CT_RESULT_TYPE adi_CT_GetStageCAPDACValue (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, uint8_t *MAIN_DAC_Value, uint8_t *SUB_DAC_Value)
Get the CAPDAC values for each Stage.
ADI_CT_RESULT_TYPE adi_CT_GetStageFreqHoppingEnable (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, bool_t *Status)
Get the signal excitation status.
ADI_CT_RESULT_TYPE adi_CT_GetStageGenericCfg (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, ADI_CT_INPUT_TYPE *CDCInput, ADI_STAGE_TYPE *const pStageType)
Get the Stage Configuration.
ADI_CT_RESULT_TYPE adi_CT_GetStagePGAGain (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, ADI_CT_PGA_GAIN_TYPE *PGA_Gain)
Get the PGA Gain.
ADI_CT_RESULT_TYPE adi_CT_GetStagePK2PKEnable (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, bool_t *Status)
Get the Noise Peak to Peak Measurements status.
ADI_CT_RESULT_TYPE adi_CT_GetStagesCalibrationEnable (ADI_CT_DEV_HANDLE const hDevice, uint16_t *Stages)
Get the Calibration Status for one or more specific Stages.
ADI_CT_RESULT_TYPE adi_CT_GetStageSelectInput (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, ADI_CT_INPUT_TYPE *CDCInput)
Get the CDC Input.
ADI_CT_RESULT_TYPE adi_CT_GetStagesEnable (ADI_CT_DEV_HANDLE const hDevice, uint16_t *Stages)
Get Enable CT Stages.
ADI_CT_RESULT_TYPE adi_CT_GetStageSensorThreshold (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, uint16_t *SensorThreshold)
Get the Sensor Threshold.
ADI_CT_RESULT_TYPE adi_CT_GetTchAndRelAlgorithmStatus (ADI_CT_DEV_HANDLE const hDevice, uint8_t *ButtonStatus)
Get the Touch And Release Algorithm Status.
ADI_CT_RESULT_TYPE adi_CT_GetTimingsCfg (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_C2V_TIMING_TYPE *TimingSettings)
Get the Conversion Timings Parameters.
ADI_CT_RESULT_TYPE adi_CT_GetTouchCfg (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_TOUCH_AND_RELEASE_TYPE *TouchSettings)
Get the Touch Detection Settings.
ADI_CT_RESULT_TYPE adi_CT_GetTouchEnable (ADI_CT_DEV_HANDLE const hDevice, bool_t *Status)
Get the Touch Detection Status.
ADI_CT_RESULT_TYPE adi_CT_GetUnmatchedPads (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_UNMATCHED_PADS_TYPE *UnmatchedPads)
Get the Number of Integration Cycles.
ADI_CT_RESULT_TYPE adi_CT_Init (ADI_CT_DEV_ID_TYPE const devID, ADI_CT_DEV_HANDLE *const phDevice)
Initialize and allocate an CT device.
ADI_CT_RESULT_TYPE adi_CT_RegisterCallback (ADI_CT_DEV_HANDLE hDevice, ADI_CALLBACK cbFunc, ADI_CT_INTERRUPT_TYPE const cbWatch)
CT Application callback registration API.
ADI_CT_RESULT_TYPE adi_CT_SetAutoForceBaselineCal (ADI_CT_DEV_HANDLE const hDevice)
Force the Automatically Baseline Calibration.
ADI_CT_RESULT_TYPE adi_CT_SetAverageCfg (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_AVERAGE_TYPE *const pAverageSettings)
Set the Average Filter Settings.
ADI_CT_RESULT_TYPE adi_CT_SetBaselineCfg (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_BASELINE_TYPE *const pBaselineSettings)
Set the Baseline Settings.
ADI_CT_RESULT_TYPE adi_CT_SetByPassGain (ADI_CT_DEV_HANDLE const hDevice, bool_t const ByPassGain)
Bypass the gain for all stages.
ADI_CT_RESULT_TYPE adi_CT_SetC2VBiasCurrent (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_C2V_BIAS_TYPE const C2VBias)
Set the C2V Bias Current.
ADI_CT_RESULT_TYPE adi_CT_SetC2VLowPassFilterEnable (ADI_CT_DEV_HANDLE const hDevice, bool_t const Enable)
Enable/Disable the C2V Low Pass Filter.
ADI_CT_RESULT_TYPE adi_CT_SetCDCResultFormat (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_CDC_RESULT_TYPE const ResSel)
Set the Value stored in the CDC_RES register.
ADI_CT_RESULT_TYPE adi_CT_SetEnable (ADI_CT_DEV_HANDLE const hDevice, bool_t const Enable)
Enable the Captouch Pins.
ADI_CT_RESULT_TYPE adi_CT_SetGenericSettings (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_GENERIC_SETTINGS_TYPE *const pGenericSettings)
Set the Generic Settings.
ADI_CT_RESULT_TYPE adi_CT_SetIIRFilterEnable (ADI_CT_DEV_HANDLE const hDevice, bool_t const Enable)
Enable/Disable the IIR Filter.
ADI_CT_RESULT_TYPE adi_CT_SetIIRFilterWeight (ADI_CT_DEV_HANDLE const hDevice, uint8_t const IIRWeight)
Set the IIR Filter Weight.
ADI_CT_RESULT_TYPE adi_CT_SetIntBufferBiasCurrent (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_INT_BUFFER_BIAS_TYPE const IntBufferBias)
Set the Internal Buffer Bias Current.
ADI_CT_RESULT_TYPE adi_CT_SetIntCycles (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_INTCYCLES_TYPE const IntCycles)
Set the Number of Integration Cycles.
ADI_CT_RESULT_TYPE adi_CT_SetInterruptFlag (ADI_CT_DEV_HANDLE const hDevice)
Set the Interrupt Flag.
ADI_CT_RESULT_TYPE adi_CT_SetInterruptsEnable (ADI_CT_DEV_HANDLE const hDevice, uint8_t const CaptouchInterrupts, bool_t const enable)
Enable the CT Interrupts.
ADI_CT_RESULT_TYPE adi_CT_SetPGABiasCurrent (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_PGA_BIAS_TYPE const PGABias)
Set the PGA Bias Current.
ADI_CT_RESULT_TYPE adi_CT_SetPK2PKCfg (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_PK2PK_TYPE *const pPK2PK_Settings)
Set the Peak to Peak Parameters.
ADI_CT_RESULT_TYPE adi_CT_SetPowerStatus (ADI_CT_DEV_HANDLE const hDevice, bool_t const Enable)
Power Up/Down the Captouch.
ADI_CT_RESULT_TYPE adi_CT_SetReleaseCfg (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_TOUCH_AND_RELEASE_TYPE *const pReleaseSettings)
Set the Release Detection Settings.
ADI_CT_RESULT_TYPE adi_CT_SetReleaseEnable (ADI_CT_DEV_HANDLE const hDevice, bool_t const Enable)
Enable the Release Detection.
ADI_CT_RESULT_TYPE adi_CT_SetSelfTimerEnable (ADI_CT_DEV_HANDLE const hDevice, bool_t const Enable)
Enable/Disable the Self Timer.
ADI_CT_RESULT_TYPE adi_CT_SetSelfTimerValue (ADI_CT_DEV_HANDLE const hDevice, uint16_t const SelfTimerWait)
Set the Self Timer Value.
ADI_CT_RESULT_TYPE adi_CT_SetStageByPassPGA (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, bool_t const ByPassPGA)
Bypass the PGA.
ADI_CT_RESULT_TYPE adi_CT_SetStageC2VRange (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, ADI_CT_C2VRANGE_TYPE const C2VRange)
Set the C2V Range.
ADI_CT_RESULT_TYPE adi_CT_SetStageCAPDACEnable (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, bool_t const Enable)
Enable the CAPDAC for each Stage.
ADI_CT_RESULT_TYPE adi_CT_SetStageCAPDACValue (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, uint8_t const MAIN_DAC_Value, uint8_t const SUB_DAC_Value)
Set the CAPDAC values for each Stage.
ADI_CT_RESULT_TYPE adi_CT_SetStageFreqHoppingEnable (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, bool_t const Enable)
Set the system ready to start a Frequency Hopping Algorithm.
ADI_CT_RESULT_TYPE adi_CT_SetStageGenericCfg (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, ADI_CT_INPUT_TYPE const CDCInput, ADI_STAGE_TYPE *const pStageType)
Set the Stage Configuration.
ADI_CT_RESULT_TYPE adi_CT_SetStagePGAGain (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, ADI_CT_PGA_GAIN_TYPE PGA_Gain)
Set the PGA Gain.
ADI_CT_RESULT_TYPE adi_CT_SetStagePK2PKEnable (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, bool_t const Enable)
Enables the Noise Peak to Peak Measurements.
ADI_CT_RESULT_TYPE adi_CT_SetStagesCalibrationEnable (ADI_CT_DEV_HANDLE const hDevice, uint16_t const Stages, bool_t const enable)
Enable the Calibration for one or more specific Stages.
ADI_CT_RESULT_TYPE adi_CT_SetStageSelectInput (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, ADI_CT_INPUT_TYPE const CDCInput)
Set the CDC Input.
ADI_CT_RESULT_TYPE adi_CT_SetStagesEnable (ADI_CT_DEV_HANDLE const hDevice, uint16_t const Stages, bool_t const enable)
Set Enable CT Stages.
ADI_CT_RESULT_TYPE adi_CT_SetStageSensorThreshold (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, uint16_t const SensorThreshold)
Set the Sensor Threshold.
ADI_CT_RESULT_TYPE adi_CT_SetStartSingleSequence (ADI_CT_DEV_HANDLE const hDevice)
Starts a single C2V conversion sequence.
ADI_CT_RESULT_TYPE adi_CT_SetTimingsCfg (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_C2V_TIMING_TYPE *const pTimingSettings)
Set the Conversion Timings Parameters.
ADI_CT_RESULT_TYPE adi_CT_SetTouchCfg (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_TOUCH_AND_RELEASE_TYPE *const pTouchSettings)
Set the Touch Detection Settings.
ADI_CT_RESULT_TYPE adi_CT_SetTouchEnable (ADI_CT_DEV_HANDLE const hDevice, bool_t const Enable)
Enable the Touch Detection.
ADI_CT_RESULT_TYPE adi_CT_SetUnmatchedPads (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_UNMATCHED_PADS_TYPE const UnmatchedPads)
Set the Unmatched Pads Configuration.
ADI_CT_RESULT_TYPE adi_CT_UnInit (ADI_CT_DEV_HANDLE const hDevice)
Uninitialize the CT device.
ADI_INT_HANDLER (CapTouch_Int_Handler)
Detailed Description
Macro Definition Documentation
#define ADI_CT_INTERRUPT_MASK
Value:
(ADI_CT_INTERRUPT_CONV_SET_COMPLETE      \
                                       | ADI_CT_INTERRUPT_STATUS_GT_THRESHOLD   \
                                       | ADI_CT_INTERRUPT_PROX_DETECTED         \
                                       | ADI_CT_INTERRUPT_TOUCH_DETECTED        \
                                       | ADI_CT_INTERRUPT_RELEASE_DETECTED      \
interrupt status mask
Definition at line 117 of file captouch.h.
#define ADI_CT_STATUS_BIT_A (1 << 0)
Button A
Definition at line 37 of file captouch.h.
Referenced by adi_CT_GetTchAndRelAlgorithmStatus().
#define ADI_CT_STATUS_BIT_B (1 << 1)
Button B
Definition at line 38 of file captouch.h.
Referenced by adi_CT_GetTchAndRelAlgorithmStatus().
#define ADI_CT_STATUS_BIT_C (1 << 2)
Button C
Definition at line 39 of file captouch.h.
Referenced by adi_CT_GetTchAndRelAlgorithmStatus().
#define ADI_CT_STATUS_BIT_D (1 << 3)
Button D
Definition at line 40 of file captouch.h.
Referenced by adi_CT_GetTchAndRelAlgorithmStatus().
#define ADI_CT_STATUS_BIT_E (1 << 4)
Button E
Definition at line 41 of file captouch.h.
Referenced by adi_CT_GetTchAndRelAlgorithmStatus().
#define ADI_CT_STATUS_BIT_F (1 << 5)
Button F
Definition at line 42 of file captouch.h.
Referenced by adi_CT_GetTchAndRelAlgorithmStatus().
#define ASSERT_ADI_MISRA_SUPPRESSIONS
Apply ADI MISRA Suppressions
Definition at line 25 of file captouch.c.
Typedef Documentation
typedef void(* ADI_CT_CALLBACK_TYPE)(ADI_CT_INTERRUPT_TYPE const statusBits)
ADI_CT_CALLBACK_TYPE.
CT callback type
Definition at line 751 of file captouch.h.
typedef struct ADI_CT_DEV_DATA_TYPE* ADI_CT_DEV_HANDLE
ADI_CT_DEV_HANDLE.
CT device handle
Definition at line 744 of file captouch.h.
Enumeration Type Documentation
enum ADI_CT_AUTOZERODUTY_TYPE
CT Autozero Duty Type. Used to set the Autozero Duty Time in C2V conversion. This type of data is included in the ADI_CT_C2V_TIMING_TYPE struct, which is used to configure the C2V conversion Timing. It is used with adi_CT_SetTimingsCfg() API.
Enumerator
ADI_CT_AUTOZERO_DUTY_2us
2us
ADI_CT_AUTOZERO_DUTY_3us
3us
ADI_CT_AUTOZERO_DUTY_4us
4us
ADI_CT_AUTOZERO_DUTY_5us
5us
ADI_CT_AUTOZERO_DUTY_6us
6us
ADI_CT_AUTOZERO_DUTY_7us
7us
ADI_CT_AUTOZERO_DUTY_8us
8us
ADI_CT_AUTOZERO_DUTY_9us
9us
Definition at line 269 of file captouch.h.
enum ADI_CT_AVG_OUTPUT_TYPE
CT Average Output Type. Used to select the final average value. This type of data is included in the ADI_CT_AVERAGE_TYPE struct, which is used to configure the Average Filter Block. It is used with adi_CT_SetAverageCfg() API.
Enumerator
ADI_CT_AVG_OUTPUT_NO_AVG
No Averaging
ADI_CT_AVG_OUTPUT_GROUP1
Average of Group 1
ADI_CT_AVG_OUTPUT_GROUP2
Average of Group 2
ADI_CT_AVG_OUTPUT_GROUP1_2
Average of average of Group 1 and average of Group 2
Definition at line 417 of file captouch.h.
enum ADI_CT_AVG_SAMPLES_TYPE
CT Average Samples Type. Used to set the number of samples in Average Group 1 and Average Group 2. This type of data is included in the ADI_CT_AVERAGE_TYPE struct, which is used to configure the Average Filter Block. It is used with adi_CT_SetAverageCfg() API.
Enumerator
ADI_CT_AVG_SAMPLES_NO_AVG
No Samples
ADI_CT_AVG_SAMPLES_2_SAMPLES
2 Samples
ADI_CT_AVG_SAMPLES_4_SAMPLES
4 Samples
ADI_CT_AVG_SAMPLES_8_SAMPLES
8 Samples
ADI_CT_AVG_SAMPLES_16_SAMPLES
16 Samples
ADI_CT_AVG_SAMPLES_32_SAMPLES
32 Samples
Definition at line 435 of file captouch.h.
enum ADI_CT_BASELINE_CAL_DELAY_TYPE
CT Baseline Calibration Delay Type. Used to set the time to update the baseline once the proximity is cleared. This type of data is included in the ADI_CT_BASELINE_TYPE struct, which is used to configure the Baseline Features. It is used with adi_CT_SetBaselineCfg() API.
Enumerator
ADI_CT_BASELINE_CAL_DELAY_FAST_FILTER_UPDATE_8
8 x FAST FILTER UPDATE RATE
ADI_CT_BASELINE_CAL_DELAY_FAST_FILTER_UPDATE_16
16 x FAST FILTER UPDATE RATE
ADI_CT_BASELINE_CAL_DELAY_FAST_FILTER_UPDATE_24
24 x FAST FILTER UPDATE RATE
ADI_CT_BASELINE_CAL_DELAY_FAST_FILTER_UPDATE_32
32 x FAST FILTER UPDATE RATE
ADI_CT_BASELINE_CAL_DELAY_FAST_FILTER_UPDATE_40
40 x FAST FILTER UPDATE RATE
ADI_CT_BASELINE_CAL_DELAY_FAST_FILTER_UPDATE_48
48 x FAST FILTER UPDATE RATE
ADI_CT_BASELINE_CAL_DELAY_FAST_FILTER_UPDATE_56
56 x FAST FILTER UPDATE RATE
ADI_CT_BASELINE_CAL_DELAY_FAST_FILTER_UPDATE_64
64 x FAST FILTER UPDATE RATE
Definition at line 455 of file captouch.h.
enum ADI_CT_C2V_BIAS_TYPE
CT C2V Conversion Bias Current Type. Used to set the C2V Conversion Bias Current.It is used with adi_CT_SetC2VBiasCurrent() API.
Enumerator
ADI_CT_C2V_BIAS_6UA
6uA
ADI_CT_C2V_BIAS_7UA
7uA
ADI_CT_C2V_BIAS_8UA
8uA
ADI_CT_C2V_BIAS_9UA
9uA
ADI_CT_C2V_BIAS_10UA
10uA
ADI_CT_C2V_BIAS_11UA
11uA
ADI_CT_C2V_BIAS_12UA
12uA
ADI_CT_C2V_BIAS_13UA
13uA
Definition at line 536 of file captouch.h.
enum ADI_CT_C2VRANGE_TYPE
CT C2V Range Type. Used to set the C2V Conversion Range for each Stage. It is used with adi_CT_SetStageC2VRange() API.
Enumerator
ADI_CT_C2VRANGE_0_58pF
0.58pF
ADI_CT_C2VRANGE_1_17pF
1.17pF
ADI_CT_C2VRANGE_1_75pF
1.75pF
ADI_CT_C2VRANGE_2_33pF
2.33pF
ADI_CT_C2VRANGE_2_91pF
2.91pF
ADI_CT_C2VRANGE_3_49pF
3.49pF
ADI_CT_C2VRANGE_4_07pF
4.07pF
ADI_CT_C2VRANGE_4_65pF
4.65pF
ADI_CT_C2VRANGE_5_23pF
5.23pF
ADI_CT_C2VRANGE_5_81pF
5.81pF
ADI_CT_C2VRANGE_6_39pF
6.39pF
ADI_CT_C2VRANGE_6_97pF
6.97pF
ADI_CT_C2VRANGE_7_55pF
7.55pF
ADI_CT_C2VRANGE_8_13pF
8.13pF
ADI_CT_C2VRANGE_8_74pF
8.74pF
ADI_CT_C2VRANGE_9_32pF
9.32pF
Definition at line 308 of file captouch.h.
enum ADI_CT_CDC_RESULT_TYPE
CT CDC Result Type. Used to set the CDC value format stored in CT_CDC_RESx registers. It is used with adi_CT_SetCDCResultFormat() API.
Enumerator
ADI_CT_CDC_RESULT_VALUE
CDC Value
ADI_CT_CDC_BASELINE_DIFFERENCE_VALUE
CDC Value - Baseline Value
Definition at line 219 of file captouch.h.
enum ADI_CT_DEV_ID_TYPE
CT device identifiers
Enumerator
ADI_CT_DEV_ID_0
CT Device ID 0
Definition at line 61 of file captouch.h.
enum ADI_CT_DRV_STATE_TYPE
CT driver state
Enumerator
ADI_CT_DRV_STATE_UNKNOWN
CT is not initialized
ADI_CT_DRV_STATE_INITIALIZED
CT driver initialized
ADI_CT_DRV_STATE_READY
CT driver is ready
Definition at line 74 of file captouch.h.
enum ADI_CT_FAST_FILTER_UPDATE_TYPE
CT Fast Filter Update Type. Used to set the update rate for the baseline calculation fast filter. This type of data is included in the ADI_CT_BASELINE_TYPE struct, which is used to configure the Baseline Features. It is used with adi_CT_SetBaselineCfg() API.
Enumerator
ADI_CT_FAST_FILTER_UPDATE_2ND_CONVERSION_CYCLE
New data every 2nd conversion cycle
ADI_CT_FAST_FILTER_UPDATE_4TH_CONVERSION_CYCLE
New data every 4th conversion cycle
ADI_CT_FAST_FILTER_UPDATE_6TH_CONVERSION_CYCLE
New data every 6th conversion cycle
ADI_CT_FAST_FILTER_UPDATE_8TH_CONVERSION_CYCLE
New data every 8th conversion cycle
ADI_CT_FAST_FILTER_UPDATE_10TH_CONVERSION_CYCLE
New data every 10th conversion cycle
ADI_CT_FAST_FILTER_UPDATE_12TH_CONVERSION_CYCLE
New data every 12th conversion cycle
ADI_CT_FAST_FILTER_UPDATE_14TH_CONVERSION_CYCLE
New data every 14th conversion cycle
ADI_CT_FAST_FILTER_UPDATE_16TH_CONVERSION_CYCLE
New data every 16th conversion cycle
Definition at line 477 of file captouch.h.
enum ADI_CT_INDIVIDUAL_THR_ENABLE_TYPE
CT Individual Threshold Type. Used to select which register is used to set the Thresholds in the Touch and Release Detection Algorithm. The user can select between a positive or a negative difference. This type of data is included in the ADI_CT_TOUCH_AND_RELEASE_TYPE struct, which is used to configure the Touch and Release Detection Algorithm. It is used with adi_CT_SetTouchCfg() and adi_CT_SetReleaseCfg() API.
Enumerator
ADI_CT_INDIVIDUAL_SENSOR_THR_CFGx_DISABLE
Use CT_SENSOR_THR_CFGx for sensor Threshold
ADI_CT_INDIVIDUAL_SENSOR_THR_CFGx_ENABLE
Use CT_TOUCH_CFG1 and CT_RELEASE_CFG1 for sensor Threshold
Definition at line 379 of file captouch.h.
enum ADI_CT_INPUT_TYPE
CT Input select. Used to connect a specific button (input) to a specific stage. It is used with adi_CT_SetStageSelectInput() API.
Enumerator
ADI_CT_INPUT_A
Button A
ADI_CT_INPUT_B
Button B
ADI_CT_INPUT_C
Button C
ADI_CT_INPUT_D
Button D
ADI_CT_INPUT_E
Button E
ADI_CT_INPUT_F
Button F
Definition at line 200 of file captouch.h.
enum ADI_CT_INT_BUFFER_BIAS_TYPE
CT Internal Buffer Bias Current Type. Used to set the Internal Buffer Bias Current. It is used with adi_CT_SetIntBufferBiasCurrent() API.
Enumerator
ADI_CT_INT_BUFFER_BIAS_2_5UA
2.5uA
ADI_CT_INT_BUFFER_BIAS_3UA
3uA
ADI_CT_INT_BUFFER_BIAS_3_5UA
3.5uA
ADI_CT_INT_BUFFER_BIAS_4UA
4uA
Definition at line 498 of file captouch.h.
enum ADI_CT_INTCYCLES_TYPE
CT Integration Cycles Type. Used to set the number of Integration Cycles in the C2V conversion. It is used with adi_CT_SetStageC2VRange() API.
Enumerator
ADI_CT_INT_CYCLES_1
1 Integration Cycle
ADI_CT_INT_CYCLES_2
2 Integration Cycles
ADI_CT_INT_CYCLES_4
4 Integration Cycles
ADI_CT_INT_CYCLES_8
8 Integration Cycles
ADI_CT_INT_CYCLES_16
16 Integration Cycles
Definition at line 234 of file captouch.h.
enum ADI_CT_INTERRUPT_TYPE
CT Interrupt Types
Enumerator
ADI_CT_INTERRUPT_NONE
No Interrupt
ADI_CT_INTERRUPT_CONV_SET_COMPLETE
Conversion Complete Interrupt
ADI_CT_INTERRUPT_STATUS_GT_THRESHOLD
Thresholds Interrupt
ADI_CT_INTERRUPT_PROX_DETECTED
Proximity Interrupt
ADI_CT_INTERRUPT_TOUCH_DETECTED
Touch Interrupt
ADI_CT_INTERRUPT_RELEASE_DETECTED
Release Interrupt
Definition at line 106 of file captouch.h.
enum ADI_CT_PGA_BIAS_TYPE
CT PGA Bias Current Type. Used to set the PGA Bias Current. It is used with adi_CT_SetPGABiasCurrent() API.
Enumerator
ADI_CT_PGA_BIAS_3UA
3uA
ADI_CT_PGA_BIAS_3_5UA
3.5uA
ADI_CT_PGA_BIAS_4UA
4uA
ADI_CT_PGA_BIAS_4_5UA
4.5uA
ADI_CT_PGA_BIAS_5UA
5uA
ADI_CT_PGA_BIAS_5_5UA
5.5uA
ADI_CT_PGA_BIAS_6UA
6uA
ADI_CT_PGA_BIAS_6_5UA
6.5uA
Definition at line 515 of file captouch.h.
enum ADI_CT_PGA_GAIN_TYPE
CT PGA Type. Used to set the PGA GAIN. It is used with adi_CT_SetCDCResultFormat() API.
Enumerator
ADI_CT_PGA_GAIN_2
GAIN of 2
ADI_CT_PGA_GAIN_4
GAIN of 4
ADI_CT_PGA_GAIN_8
GAIN of 8
ADI_CT_PGA_GAIN_16
GAIN of 16
Definition at line 291 of file captouch.h.
enum ADI_CT_PK2PK_AVG_TYPE
CT PK2PK AVG Samples Type. Used to set number of samples to be averaged when calculating CDC Value during Peak-to-Peak noise measurements stages. This type of data is included in the ADI_CT_PK2PK_TYPE struct, which is used to configure the PK2PK measurements Features. It is used with adi_CT_SetPK2PKCfg() API.
Enumerator
ADI_CT_PK2PK_AVG_2_SAMPLES
2 samples
ADI_CT_PK2PK_AVG_4_SAMPLES
4 samples
ADI_CT_PK2PK_AVG_8_SAMPLES
8 samples
ADI_CT_PK2PK_AVG_16_SAMPLES
16 samples
ADI_CT_PK2PK_AVG_32_SAMPLES
32 samples
Definition at line 559 of file captouch.h.
enum ADI_CT_PK2PK_NUM_TYPE
CT PK2PK Number of Samples Type. Used to set number of samples for Peak-to-Peak noise calculations. This type of data is included in the ADI_CT_PK2PK_TYPE struct, which is used to configure the PK2PK measurements Features. It is used with adi_CT_SetPK2PKCfg() API.
Enumerator
ADI_CT_PK2PK_NUM_4_SAMPLES
4 samples
ADI_CT_PK2PK_NUM_8_SAMPLES
8 samples
ADI_CT_PK2PK_NUM_16_SAMPLES
16 samples
ADI_CT_PK2PK_NUM_32_SAMPLES
32 samples
Definition at line 578 of file captouch.h.
enum ADI_CT_RANKING_TYPE
CT Raking Type. Used to set the number of samples used in the Ranking Filter block. This type of data is included in the ADI_CT_AVERAGE_TYPE struct, which is used to configure the Average Filter Block. It is used with adi_CT_SetAverageCfg() API.
Enumerator
ADI_CT_RANKING_NO_RANKING
No Ranking
ADI_CT_RANKING_4_SAMPLES
4 samples
ADI_CT_RANKING_8_SAMPLES
8 samples
ADI_CT_RANKING_16_SAMPLES
16 samples
ADI_CT_RANKING_32_SAMPLES
32 samples
Definition at line 397 of file captouch.h.
enum ADI_CT_RESULT_TYPE
CT result codes
Enumerator
ADI_CT_RESULT_SUCCESS
generic success
ADI_CT_RESULT_ERR
generic error
ADI_CT_RESULT_ERR_CALLBACK_OVERWRITE
Callback Overwrite
ADI_CT_RESULT_ERR_TCH_REL_NOT_ENABLE
Touch And Release Detection not enable
Definition at line 88 of file captouch.h.
enum ADI_CT_STAGE_BIT_TYPE
CT Stage Bit Type. Used in functions whose task is to select an specific stage to be enabled,disabled or calibrated. It is used with adi_CT_SetStagesEnable() and adi_CT_SetStagesCalibrationEnable() API.
Enumerator
ADI_CT_STAGE0_BIT
Stage 0
ADI_CT_STAGE1_BIT
Stage 1
ADI_CT_STAGE2_BIT
Stage 2
ADI_CT_STAGE3_BIT
Stage 3
ADI_CT_STAGE4_BIT
Stage 4
ADI_CT_STAGE5_BIT
Stage 5
ADI_CT_STAGE6_BIT
Stage 6
ADI_CT_STAGE7_BIT
Stage 7
ADI_CT_STAGE8_BIT
Stage 8
ADI_CT_STAGE9_BIT
Stage 9
ADI_CT_STAGE10_BIT
Stage 10
ADI_CT_STAGE11_BIT
Stage 11
ADI_CT_STAGE12_BIT
Stage 12
ADI_CT_STAGE13_BIT
Stage 13
ADI_CT_STAGE14_BIT
Stage 14
ADI_CT_STAGE15_BIT
Stage 15
Definition at line 170 of file captouch.h.
enum ADI_CT_STAGE_NUMBER_TYPE
CT Stage Number Type
Used to select the stage number to set or get each Stage parameter through the adi_CT_SetStage*() or adi_CT_GetStage*() API. It can be also used with the read data functions like adi_CT_GetCDCValue().
Enumerator
ADI_CT_STAGE0_NUMBER
Stage 0
ADI_CT_STAGE1_NUMBER
Stage 1
ADI_CT_STAGE2_NUMBER
Stage 2
ADI_CT_STAGE3_NUMBER
Stage 3
ADI_CT_STAGE4_NUMBER
Stage 4
ADI_CT_STAGE5_NUMBER
Stage 5
ADI_CT_STAGE6_NUMBER
Stage 6
ADI_CT_STAGE7_NUMBER
Stage 7
ADI_CT_STAGE8_NUMBER
Stage 8
ADI_CT_STAGE9_NUMBER
Stage 9
ADI_CT_STAGE10_NUMBER
Stage 10
ADI_CT_STAGE11_NUMBER
Stage 11
ADI_CT_STAGE12_NUMBER
Stage 12
ADI_CT_STAGE13_NUMBER
Stage 13
ADI_CT_STAGE14_NUMBER
Stage 14
ADI_CT_STAGE15_NUMBER
Stage 15
ADI_CT_STAGE_NON_VALID_STAGE
Non valid stage
Definition at line 137 of file captouch.h.
enum ADI_CT_TCH_REL_EVENT_ON_HIGH_INPUT_TYPE
CT Touch And Release Rising Edge Detection Type. Used to select the type of Rising Edge Detection type. The user can select between a positive or a negative difference. This type of data is included in the ADI_CT_TOUCH_AND_RELEASE_TYPE struct, which is used to configure the Touch and Release Detection Algorithm. It is used with adi_CT_SetTouchCfg() and adi_CT_SetReleaseCfg() API.
Enumerator
ADI_CT_TCH_REL_EVENT_ON_HIGH_INPUT_INA_INB_DIFF_LESSER_THR
Active if inA-inB < Thrld for a MinDuration
ADI_CT_TCH_REL_EVENT_ON_HIGH_INPUT_INA_INB_DIFF_GREATER_THR
Active if inA-inB > Thrld for a MinDuration
Definition at line 360 of file captouch.h.
enum ADI_CT_TCH_REL_INPUT_TYPE
CT Touch And Release Input Type. Used to select the Inputs in the Touch and Release Detection Algorithm. This type of data is included in the ADI_CT_TOUCH_AND_RELEASE_TYPE struct, which is used to configure the Touch and Release Detection Algorithm. It is used with adi_CT_SetTouchCfg() and adi_CT_SetReleaseCfg() API.
Enumerator
ADI_CT_TCH_REL_INPUT_ALL_ZEROS
Load All Zeros
ADI_CT_TCH_REL_INPUT_CDC_VALUE
CDC Value
ADI_CT_TCH_REL_INPUT_SLOW_FILTER_OUTPUT
Slow Filter Output
ADI_CT_TCH_REL_INPUT_FAST_FILTER_OUTPUT
Fast Filter Output
ADI_CT_TCH_REL_INPUT_AMBIENT_VALUE
Load Ambient Value
Definition at line 340 of file captouch.h.
enum ADI_CT_UNMATCHED_PADS_TYPE
CT Unmatched Pads Type. Used to set the configuration of the Unmatched Pads. It is used with adi_CT_SetCDCResultFormat() API.
Enumerator
ADI_CT_UNMATCHED_PADS_AC_DRV
Pads to AC drive
ADI_CT_UNMATCHED_PADS_DC_DRV
Pads to DC drive
ADI_CT_UNMATCHED_PADS_GND
Pads to GND
ADI_CT_UNMATCHED_PADS_FLOATED
Pads Floated
Definition at line 251 of file captouch.h.
Function Documentation
ADI_CT_RESULT_TYPE adi_CT_ClearInterruptFlag (ADI_CT_DEV_HANDLE const hDevice)
Clear the Interrupt Flag.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The Interrupt Flag variable is defined in ADI_CT_DEV_HANDLE. This function must be used by the main program to notify that it managed the Interrupt and it is ready to be notify of new events.
Definition at line 4218 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_GetAverageCfg (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_AVERAGE_TYPE * AverageSettings)
Get the Average Filter Settings.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[out] AverageSettings Struct which includes the different Average Settings
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The Average Settings are get by AverageSettings. AverageSettings will get as a ADI_CT_AVERAGE_TYPE struct which includes: RankFilt Number of samples to be ranked. ADI_CT_RANKING_TYPE AvgType Final Average Value. ADI_CT_AVG_OUTPUT_TYPE AvgGroup1 Number of Samples in Average Group 1. ADI_CT_AVG_SAMPLES_TYPE AvgGroup2 Number of Samples in Average Group 2. ADI_CT_AVG_SAMPLES_TYPE AvgMinGroup1 Minimum Rank Position to be averaged in Group1 (5bits) AvgMinGroup2 Minimum Rank Position to be averaged in Group2 (5bits)
Definition at line 2178 of file captouch.c.
Referenced by adi_CT_NoiseMeasurement().
ADI_CT_RESULT_TYPE adi_CT_GetBaselineCfg (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_BASELINE_TYPE * BaselineSettings)
Get the Baseline Settings.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[out] BaselineSettings Struct which includes the different Average Settings
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The Baseline Settings are get by BaselineSettings. BaselineSettings will be get as a ADI_CT_BASELINE_TYPE struct which includes: BaselineCalDelay Delay before updating the Baseline. ADI_CT_BASELINE_CAL_DELAY_TYPE FastFilterUpdate Update for the fast filter. ADI_CT_FAST_FILTER_UPDATE_TYPE FastProx Fast Proximity Value. uint8_t SlowProx Slow Proximity Value. uint8_t BL_Coeff Slow Filter new sample Weight. uint8_t CDC_Coeff Fast Filter new sample Weight. uint8_t
Definition at line 2308 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_GetBaselineValue (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, uint16_t * BaselineResult)
Read the Baseline value of a Stage.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] StageNumber Stage to Read
[out] BaselineResult Baseline Value
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The function reads the Baseline value of the selected stage. It is recommended to use the ADI_CT_STAGE_NUMBER_TYPE type to select the Stage to configure.
Definition at line 3968 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_GetByPassGain (ADI_CT_DEV_HANDLE const hDevice, bool_t * Status)
Bypass the gain for all stages.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[out] Status PGA Gain Status
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The function gets PGA gain status for all stages, independently the set value in each stage. True -> Override False -> Not Override
Definition at line 1362 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_GetC2VBiasCurrent (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_C2V_BIAS_TYPE * C2VBias)
Get the C2V Bias Current.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[out] C2VBias C2V Bias Current
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The C2V Bias Current is get by C2VBias. C2VBias must be a ADI_CT_C2V_BIAS_TYPE variable
Definition at line 1614 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_GetC2VLowPassFilterEnable (ADI_CT_DEV_HANDLE const hDevice, bool_t * Status)
Get the C2V Low Pass Filter Status.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[out] Status C2V Low Pass Filter Status
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The function gets the C2V Low Pass Filter Status True -> Enable False -> Disable
Definition at line 1807 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_GetCDCResultFormat (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_CDC_RESULT_TYPE * ResSel)
Get the Value stored in the CDC_RES register.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[out] ResSel CDC_RESULT_VALUE/CDC_BASELINE_DIFFERENCE_VALUE
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The Value stored in the CDC_RES register is Get by ResSel. ResSel will be get as a ADI_CT_CDC_RESULT_TYPE variable -CDC_RESULT_VALUE -> CDC Value -CDC_BASELINE_DIFFERENCE_VALUE -> CDC Value - Baseline Value
Definition at line 1890 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_GetCDCValue (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, uint16_t * CDCResult)
Read the CDC value of a Stage.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] StageNumber Stage to Read
[out] CDCResult CDC Value
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The function reads the CDC value of the selected stage. It is recommended to use the ADI_CT_STAGE_NUMBER_TYPE type to select the Stage to configure.
Definition at line 3916 of file captouch.c.
Referenced by adi_CT_NoiseMeasurement(), and adi_CT_Stage_AutoCAPDAC_Adjustment().
ADI_CT_RESULT_TYPE adi_CT_GetEnable (ADI_CT_DEV_HANDLE const hDevice, bool_t * Status)
Get the Captouch Pins Status.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[out] Status Captouch Enable Status().
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The function indicates if the Captouch Inputs are enable True -> Enable False -> Disable
Definition at line 688 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_GetFastFilterValue (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, uint16_t * FastFilterResult)
Read the Fast Filter value of a Stage.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] StageNumber Stage to Read
[out] FastFilterResult Fast Filter Value
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The function reads the Fast Filter value of the selected stage. It is recommended to use the ADI_CT_STAGE_NUMBER_TYPE type to select the Stage to configure.
Definition at line 4010 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_GetFProxStatus (ADI_CT_DEV_HANDLE const hDevice, uint16_t * FProxStatus)
Get the Fast Proximity Status.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[out] FProxStatus Fast Proximity Status
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
This function gets the current Status of the Fast Proximity Status Register
Definition at line 4436 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_GetIIRFilterEnable (ADI_CT_DEV_HANDLE const hDevice, bool_t * Status)
Get the IIR Filter Status.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[out] Status IIR Filter Status
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The function gets the IIR Filter Status True -> Enable False -> Disable
Definition at line 1983 of file captouch.c.
Referenced by adi_CT_NoiseMeasurement(), and adi_CT_Stage_AutoCAPDAC_Adjustment().
ADI_CT_RESULT_TYPE adi_CT_GetIIRFilterWeight (ADI_CT_DEV_HANDLE const hDevice, uint8_t * IIRWeight)
Get the IIR Filter Weight.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[out] IIRWeight IIR order [0-15]
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The IIR Filter Weight will be get as an uint8_t
Definition at line 2065 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_GetIntBufferBiasCurrent (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_INT_BUFFER_BIAS_TYPE * IntBufferBias)
Get the Internal Buffer Bias Current.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[out] IntBufferBias Int Buffer Bias Current
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The Internal Buffer Bias Current is get by IntBufferBias. IntBufferBias must be a ADI_CT_INT_BUFFER_BIAS_TYPE variable
Definition at line 1446 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_GetIntCycles (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_INTCYCLES_TYPE * IntCycles)
Get the Number of Integration Cycles.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[out] IntCycles Number Of Integration Cycles().
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The Number of Integration Cycles is get by IntCycles. IntCycles must be a ADI_CT_INTCYCLES_TYPE variable
Definition at line 913 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_GetInterruptFlag (ADI_CT_DEV_HANDLE const hDevice, bool_t * EventFlag)
Get the Interrupt Flag.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[out] EventFlag bool_t
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The Interrupt Flag variable is defined in ADI_CT_DEV_HANDLE. This function will return the current status of this Flag.
Definition at line 4256 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_GetInterruptsEnable (ADI_CT_DEV_HANDLE const hDevice, uint8_t * CaptouchInterrupts)
Get the CT Interrupt.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[out] CaptouchInterrupts Enabled Interrupt
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
If the bit associated to the Interrupt is 1, this interrupt is activated.
Definition at line 4148 of file captouch.c.
Referenced by adi_CT_Stage_AutoCAPDAC_Adjustment().
ADI_CT_RESULT_TYPE adi_CT_GetInterruptStatus (ADI_CT_DEV_HANDLE const hDevice, uint8_t * EventType)
Get the Interrupt Status.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[out] EventType Captouch Interrrupt Status Register
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
This function gets the current Status of the Captouch Interrupt Register
Definition at line 4291 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_GetOffsHStatus (ADI_CT_DEV_HANDLE const hDevice, uint16_t * OffsHStatus)
Get the Offset High Status.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[out] OffsHStatus Offset High Status Register
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
This function gets the current Status of the Captouch Offset High Status Register
Definition at line 4329 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_GetOffsLStatus (ADI_CT_DEV_HANDLE const hDevice, uint16_t * OffsLStatus)
Get the Offset Low Status.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[out] OffsLStatus Offset Low Status Register
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
This function gets the current Status of the Offset Low Status Register
Definition at line 4365 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_GetPGABiasCurrent (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_PGA_BIAS_TYPE * PGABias)
Get the PGA Bias Current.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[out] PGABias PGA Bias Current
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The PGA Bias Current is get by PGABias. PGABias must be a ADI_CT_PGA_BIAS_TYPE variable
Definition at line 1529 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_GetPK2PKCfg (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_PK2PK_TYPE * PK2PK_Settings)
Get the Peak to Peak Parameters.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[out] PK2PK_Settings Struct which includes the different PK2PK parameters
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The Peak to Peak Settings are get by PK2PK_Settings. PK2PK_Settings will be get as a ADI_CT_PK2PK_TYPE struct which includes:
PK2PKAvg Number of Samples to be averaged
PK2PKAvgMin Minimum rank position for averaging
PK2PKSubset Subset of Number of Samples to be used for the calculations
PK2PKNumSamples Number of Samples to be used for the calculations
Definition at line 1716 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_GetPK2PKValue (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, uint16_t * PK2PKResult)
Read the Peak to Peak value of a Stage.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] StageNumber Stage to Read
[out] PK2PKResult Peak to Peak Value
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The function reads the Peak to Peak value of the selected stage. It is recommended to use the ADI_CT_STAGE_NUMBER_TYPE type to select the Stage to configure.
Definition at line 4052 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_GetPowerStatus (ADI_CT_DEV_HANDLE const hDevice, bool_t * Status)
Get Power Captouch Status.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[out] Status Captouch Power Status.
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The function gets the power Captouch status True -> Enable False -> Disable
Definition at line 771 of file captouch.c.
Referenced by adi_CT_Stage_AutoCAPDAC_Adjustment().
ADI_CT_RESULT_TYPE adi_CT_GetProxStatus (ADI_CT_DEV_HANDLE const hDevice, uint16_t * ProxStatus)
Get the Slow Proximity Status.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[out] ProxStatus Slow Proximity Status
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
This function gets the current Status of the Slow Proximity Status Register
Definition at line 4401 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_GetReleaseCfg (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_TOUCH_AND_RELEASE_TYPE * ReleaseSettings)
Get the Release Detection Settings.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[out] ReleaseSettings Struct which includes the different Release Settings
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The Release Settings are get by ReleaseSettings. ReleaseSettings will be get as a ADI_CT_TCH_REL_INPUT_TYPE struct which includes: InputA Source A InputB Source B UpperThreshold Upper Thershold LowerThreshold Lower Thershold MinDuration Minimum touch Duration
Definition at line 3859 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_GetReleaseEnable (ADI_CT_DEV_HANDLE const hDevice, bool_t * Status)
Get the Release Detection Status.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[out] Status Status of Release Detection
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The function gets the Release Detection Enable Status True -> Enable False -> Disable
Definition at line 3622 of file captouch.c.
Referenced by adi_CT_GetTchAndRelAlgorithmStatus().
ADI_CT_RESULT_TYPE adi_CT_GetSelfTimerEnable (ADI_CT_DEV_HANDLE const hDevice, bool_t * Status)
Get the Self Timer Status.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[out] Status SelfTimer status
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The function gets the Self Timer status True -> Enable False -> Disable
Definition at line 1193 of file captouch.c.
Referenced by adi_CT_NoiseMeasurement(), and adi_CT_Stage_AutoCAPDAC_Adjustment().
ADI_CT_RESULT_TYPE adi_CT_GetSelfTimerValue (ADI_CT_DEV_HANDLE const hDevice, uint16_t * SelfTimerWait)
Get the Self Timer Value.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[out] SelfTimerWait Digital Self Timer Value.
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The Self Timer Value configuration is get by SelfTimerWait. Each LSB corresponds to 1.95ms. Range [0-998]ms.
Definition at line 1278 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_GetStageByPassPGA (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, bool_t * Status)
Get Bypass PGA Status.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] StageNumber Stage to configure
[out] Status BYPASS Gain Status
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The function gets the PGA gain status for a specific stage. True -> Override False -> Not Override
Definition at line 2697 of file captouch.c.
Referenced by adi_CT_GetStageGenericCfg().
ADI_CT_RESULT_TYPE adi_CT_GetStageC2VRange (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, ADI_CT_C2VRANGE_TYPE * C2VRange)
Get the C2V Range.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] StageNumber Stage to configure
[out] C2VRange C2V Range
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The C2V Range is get by C2VRange. C2VRange will be get as a ADI_CT_C2VRANGE_TYPE variable. It is recommended to use the ADI_CT_STAGE_NUMBER_TYPE type to select the Stage to configure.
Definition at line 2883 of file captouch.c.
Referenced by adi_CT_GetStageGenericCfg().
ADI_CT_RESULT_TYPE adi_CT_GetStageCAPDACEnable (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, bool_t * Status)
Get the CAPDAC Status for each Stage.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] StageNumber Stage to configure
[out] Status Enable the CAPDAC
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The function sets CAPDAC status for a specific stage. True->Enable False->Disable It is recommended to use the ADI_CT_STAGE_NUMBER_TYPE type to select the Stage to configure.
Definition at line 3161 of file captouch.c.
Referenced by adi_CT_GetStageGenericCfg().
ADI_CT_RESULT_TYPE adi_CT_GetStageCAPDACValue (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, uint8_t * MAIN_DAC_Value, uint8_t * SUB_DAC_Value)
Get the CAPDAC values for each Stage.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] StageNumber Stage to configure
[out] MAIN_DAC_Value MAIN DAC Value (7 bits)
[out] SUB_DAC_Value SUB DAC Value (3 bits)
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The MAIN_DAC_Value is a 7 bits value and the SUB_DAC_Value is a 3 bits. It is recommended to use the ADI_CT_STAGE_NUMBER_TYPE type to select the Stage to configure.
Definition at line 3263 of file captouch.c.
Referenced by adi_CT_GetStageGenericCfg().
ADI_CT_RESULT_TYPE adi_CT_GetStageFreqHoppingEnable (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, bool_t * Status)
Get the signal excitation status.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] StageNumber Stage to configure
[out] Status Fsignal excitation status
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error.
True->Disable the signal excitation False->Enable the signal excitation (normal operation) It is recommended to use the ADI_CT_STAGE_NUMBER_TYPE type to select the Stage to configure.
Definition at line 3070 of file captouch.c.
Referenced by adi_CT_GetStageGenericCfg().
ADI_CT_RESULT_TYPE adi_CT_GetStageGenericCfg (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, ADI_CT_INPUT_TYPE * CDCInput, ADI_STAGE_TYPE *const pStageType)
Get the Stage Configuration.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] StageNumber Stage to configure
[out] CDCInput Selected Input
[out] pStageType Stage Configuration
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The Stage Configuration is get by StageType. StageType must be a ADI_STAGE_TYPE struct. The CDC Input is get by CDCInput. CDCInput must be a ADI_CT_INPUT_TYPE variable It is recommended to use the ADI_CT_STAGE_NUMBER_TYPE type to select the Stage to configure.
Definition at line 2419 of file captouch.c.
Referenced by adi_CT_NoiseMeasurement().
ADI_CT_RESULT_TYPE adi_CT_GetStagePGAGain (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, ADI_CT_PGA_GAIN_TYPE * PGA_Gain)
Get the PGA Gain.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] StageNumber Stage to configure
[out] PGA_Gain PGA Gain
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The PGA Gain is get by PGA_Gain. PGA_Gain will be get as a ADI_CT_PGA_GAIN_TYPE variable. It is recommended to use the ADI_CT_STAGE_NUMBER_TYPE type to select the Stage to configure.
Definition at line 2791 of file captouch.c.
Referenced by adi_CT_GetStageGenericCfg().
ADI_CT_RESULT_TYPE adi_CT_GetStagePK2PKEnable (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, bool_t * Status)
Get the Noise Peak to Peak Measurements status.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] StageNumber Stage to configure
[out] Status Peak to Peak Measurements Status
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The function gets the Peak to Peak Measurements status for a specific stage. True -> Enable False -> Disable It is recommended to use the ADI_CT_STAGE_NUMBER_TYPE type to select the Stage to configure.
Definition at line 2976 of file captouch.c.
Referenced by adi_CT_GetStageGenericCfg().
ADI_CT_RESULT_TYPE adi_CT_GetStagesCalibrationEnable (ADI_CT_DEV_HANDLE const hDevice, uint16_t * Stages)
Get the Calibration Status for one or more specific Stages.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[out] Stages Stages to Enable the Calibration
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
If the associated bit to the Stage is 1 will indicate that this Stage is configured with the Calibration enable
Definition at line 2507 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_GetStageSelectInput (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, ADI_CT_INPUT_TYPE * CDCInput)
Get the CDC Input.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] StageNumber Stage to configure
[out] CDCInput Selected Input
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The CDC Input is get by CDCInput. CDCInput will be get as a ADI_CT_INPUT_TYPE variable. It is recommended to use the ADI_CT_STAGE_NUMBER_TYPE type to select the Stage to configure.
Definition at line 2611 of file captouch.c.
Referenced by adi_CT_GetStageGenericCfg().
ADI_CT_RESULT_TYPE adi_CT_GetStagesEnable (ADI_CT_DEV_HANDLE const hDevice, uint16_t * Stages)
Get Enable CT Stages.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[out] Stages Stages to Enable
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
If the associated bit to the Stage is 1 will indicate that this Stage is configured with the Calibration enable
Definition at line 3348 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_GetStageSensorThreshold (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, uint16_t * SensorThreshold)
Get the Sensor Threshold.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] StageNumber Stage to Configure
[out] SensorThreshold Digital Self Timer Value
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
SensorThreshold is a 14 bit value. It is recommended to use the ADI_CT_STAGE_BIT_TYPE type.
Definition at line 3451 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_GetTchAndRelAlgorithmStatus (ADI_CT_DEV_HANDLE const hDevice, uint8_t * ButtonStatus)
Get the Touch And Release Algorithm Status.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[out] ButtonStatus Button Status
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
ADI_CT_RESULT_ERR_TCH_REL_NOT_ENABLE Error: The Touch and Release feature is not enable.
This function gets the current Button Status. Each bit represents a button. To use this function is necessary to enable the Touch and Release feature: adi_CT_SetTouchEnable() and adi_CT_SetReleaseEnable(); bit 0 –> Input A bit 1 –> Input B bit 2 –> Input C bit 3 –> Input D bit 4 –> Input E bit 5 –> Input F
1 -> Button is touched 0 -> Button is released
Definition at line 4699 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_GetTimingsCfg (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_C2V_TIMING_TYPE * TimingSettings)
Get the Conversion Timings Parameters.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[out] TimingSettings Struct which includes the different timings values
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The Timing configuration is get by TimingSettings. TimingSettings will be get as a ADI_CT_C2V_TIMING_TYPE struct which includes: AutozeroDuty ADI_CT_AUTOZERODUTY_TYPE C2VHoldTime Capaticitance to Voltage Time. 5 bits, each LSB represents 0.25us, range [0.25-8]us. Phase13 Phase13 Time. 5 bits, each LSB represents 0.25us, range [0.25-8]us. Phase24 Phase24 Time. 8 bits, each LSB represents 0.25us, range [0.0625-16]us.
Definition at line 1103 of file captouch.c.
Referenced by adi_CT_FrequencyHoppingAlgorithm().
ADI_CT_RESULT_TYPE adi_CT_GetTouchCfg (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_TOUCH_AND_RELEASE_TYPE * TouchSettings)
Get the Touch Detection Settings.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[out] TouchSettings Struct which includes the different Touch Settings
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The Touch Settings are get by TouchSettings. TouchSettings will be get as a ADI_CT_TOUCH_AND_RELEASE_TYPE struct which includes: InputA Source A InputB Source B UpperThreshold Upper Thershold LowerThreshold Lower Thershold MinDuration Minimum touch Duration
Definition at line 3733 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_GetTouchEnable (ADI_CT_DEV_HANDLE const hDevice, bool_t * Status)
Get the Touch Detection Status.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[out] Status Status of Touch Detection
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The function gets the Touch Detection Enable Status True -> Enable False -> Disable
Definition at line 3543 of file captouch.c.
Referenced by adi_CT_GetTchAndRelAlgorithmStatus(), and adi_CT_Stage_AutoCAPDAC_Adjustment().
ADI_CT_RESULT_TYPE adi_CT_GetUnmatchedPads (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_UNMATCHED_PADS_TYPE * UnmatchedPads)
Get the Number of Integration Cycles.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[out] UnmatchedPads Unmatched Pads configuration
Returns
Status
ADI_CT_UNMATCHED_PADS_TYPE Number of Integration Cycles
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The Unmatched Pads Configuration is get by UnmatchedPads. UnmatchedPads must be a ADI_CT_UNMATCHED_PADS_TYPE variable
Definition at line 993 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_Init (ADI_CT_DEV_ID_TYPE const devID, ADI_CT_DEV_HANDLE *const phDevice)
Initialize and allocate an CT device.
Parameters
[in] devID ADI_CT_DEV_ID_TYPE specifying the instance of the CT to use.
[in] phDevice Pointer to a location the device handle will be written upon successful driver initialization.
Returns
Status
               - #ADI_CT_RESULT_SUCCESS                        Call completed successfully.
No other CT APIs may be called until the device init function is called. Initialize an CT device using internal default configuration settings and allocate the device for use. The caller's device handle is written with the device instance data pointer. The returned device handle is required to be passed to all subsequent calls to convey which device instance to operate on.
Note
The contents of phDevice will be set to NULL upon failure.
Definition at line 480 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_RegisterCallback (ADI_CT_DEV_HANDLE hDevice, ADI_CALLBACK cbFunc, ADI_CT_INTERRUPT_TYPE const cbWatch)
CT Application callback registration API.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] cbFunc Application callback address; the function to call.
[in] cbWatch The interrupts to watch, controlling which interrupts Status in a callback.
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init()
Note
Registers an application-provided callback function. Callbacks are made in response to CT interrupts, depending on whether they are enabled and whether the corresponding callback watch bits are set. This allosw the application to control which interrupts it wants to be called back on.
The callback to the application is made in context of the originating interrupt, so extended processing is discouraged soas to not lock out lower-priority interrupts.
Definition at line 4859 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_SetAutoForceBaselineCal (ADI_CT_DEV_HANDLE const hDevice)
Force the Automatically Baseline Calibration.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
This function writes in the register to Calibrate automatically the Baseline
Definition at line 4617 of file captouch.c.
Referenced by adi_CT_Stage_AutoCAPDAC_Adjustment().
ADI_CT_RESULT_TYPE adi_CT_SetAverageCfg (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_AVERAGE_TYPE *const pAverageSettings)
Set the Average Filter Settings.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] pAverageSettings Struct which includes the different Average Settings
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The Average Settings are set by pAverageSettings. pAverageSettings must be a ADI_CT_AVERAGE_TYPE struct which includes: RankFilt Number of samples to be ranked. ADI_CT_RANKING_TYPE AvgType Final Average Value. ADI_CT_AVG_OUTPUT_TYPE AvgGroup1 Number of Samples in Average Group 1. ADI_CT_AVG_SAMPLES_TYPE AvgGroup2 Number of Samples in Average Group 2. ADI_CT_AVG_SAMPLES_TYPE AvgMinGroup1 Minimum Rank Position to be averaged in Group1 (5bits) AvgMinGroup2 Minimum Rank Position to be averaged in Group2 (5bits)
Definition at line 2110 of file captouch.c.
Referenced by adi_CT_NoiseMeasurement(), and adi_CT_SetGenericSettings().
ADI_CT_RESULT_TYPE adi_CT_SetBaselineCfg (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_BASELINE_TYPE *const pBaselineSettings)
Set the Baseline Settings.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] pBaselineSettings Struct which includes the different Average Settings
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The Baseline Settings are set by pBaselineSettings. pBaselineSettings must be a ADI_CT_BASELINE_TYPE struct which includes: BaselineCalDelay Delay before updating the Baseline. ADI_CT_BASELINE_CAL_DELAY_TYPE FastFilterUpdate Update for the fast filter. ADI_CT_FAST_FILTER_UPDATE_TYPE FastProx Fast Proximity Value. uint8_t SlowProx Slow Proximity Value. uint8_t BL_Coeff Slow Filter new sample Weight. uint8_t CDC_Coeff Fast Filter new sample Weight. uint8_t
Definition at line 2236 of file captouch.c.
Referenced by adi_CT_SetGenericSettings().
ADI_CT_RESULT_TYPE adi_CT_SetByPassGain (ADI_CT_DEV_HANDLE const hDevice, bool_t const ByPassGain)
Bypass the gain for all stages.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] ByPassGain By Pass the PGA Gain
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The function bypasses the gain for all stages, independently the set value in each stage. True -> Override False -> Not Override
Definition at line 1316 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_SetC2VBiasCurrent (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_C2V_BIAS_TYPE const C2VBias)
Set the C2V Bias Current.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] C2VBias C2V Bias Current
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The C2V Bias Current is set by C2VBias. C2VBias must be a ADI_CT_C2V_BIAS_TYPE variable
Definition at line 1566 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_SetC2VLowPassFilterEnable (ADI_CT_DEV_HANDLE const hDevice, bool_t const Enable)
Enable/Disable the C2V Low Pass Filter.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] Enable Enable the C2V Low Pass Filter
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The function enables the C2V Low Pass Filter True -> Enable False -> Disable
Definition at line 1762 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_SetCDCResultFormat (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_CDC_RESULT_TYPE const ResSel)
Set the Value stored in the CDC_RES register.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] ResSel CDC_RESULT_VALUE/CDC_BASELINE_DIFFERENCE_VALUE
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The Value stored in the CDC_RES register is set by ResSel. ResSel must be a ADI_CT_CDC_RESULT_TYPE variable -CDC_RESULT_VALUE -> CDC Value -CDC_BASELINE_DIFFERENCE_VALUE -> CDC Value - Baseline Value
Definition at line 1845 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_SetEnable (ADI_CT_DEV_HANDLE const hDevice, bool_t const Enable)
Enable the Captouch Pins.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] Enable True or False, to enable or disable the Captouch
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The function programs the CT bits to enable the Captouch signals. True -> Enable False -> Disable
Definition at line 633 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_SetGenericSettings (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_GENERIC_SETTINGS_TYPE *const pGenericSettings)
Set the Generic Settings.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] pGenericSettings Generic Captouch Settings: ADI_CT_C2V_TIMING_TYPE ADI_CT_PK2PK_TYPE ADI_CT_AVERAGE_TYPE ADI_CT_BASELINE_TYPE ADI_CT_TOUCH_AND_RELEASE_TYPE
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
Alternative way to configure the generic captouch settings. Includes the C2V_timing, PK2PK, Average, Baseline and Touch and Release Setteings. Each of them can be configured using its own set function.
Definition at line 812 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_SetIIRFilterEnable (ADI_CT_DEV_HANDLE const hDevice, bool_t const Enable)
Enable/Disable the IIR Filter.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] Enable Enable the IIR Filter
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The function sets the IIR Filter Status True -> Enable False -> Disable
Definition at line 1938 of file captouch.c.
Referenced by adi_CT_NoiseMeasurement(), and adi_CT_Stage_AutoCAPDAC_Adjustment().
ADI_CT_RESULT_TYPE adi_CT_SetIIRFilterWeight (ADI_CT_DEV_HANDLE const hDevice, uint8_t const IIRWeight)
Set the IIR Filter Weight.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] IIRWeight IIR order [0-15]
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The IIR Filter Weight must be an uint8_t
Definition at line 2019 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_SetIntBufferBiasCurrent (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_INT_BUFFER_BIAS_TYPE const IntBufferBias)
Set the Internal Buffer Bias Current.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] IntBufferBias Int Buffer Bias Current
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The Internal Buffer Bias Current is set by IntBufferBias. IntBufferBias must be a ADI_CT_INT_BUFFER_BIAS_TYPE variable
Definition at line 1398 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_SetIntCycles (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_INTCYCLES_TYPE const IntCycles)
Set the Number of Integration Cycles.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] IntCycles Number of Integration Cycles
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The number of Integration Cycle is set by IntCycles. IntCycles must be a ADI_CT_INTCYCLES_TYPE variable
Definition at line 865 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_SetInterruptFlag (ADI_CT_DEV_HANDLE const hDevice)
Set the Interrupt Flag.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The Interrupt Flag variable is defined in ADI_CT_DEV_HANDLE. Setting this variable, the main program will be notified that an Interrupt has been generated.
Definition at line 4184 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_SetInterruptsEnable (ADI_CT_DEV_HANDLE const hDevice, uint8_t const CaptouchInterrupts, bool_t const enable)
Enable the CT Interrupts.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] CaptouchInterrupts Interrupt Status
[in] enable Status
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
To enable a specific Interrupt, the bit associated to that Interrupt must be 1. It is recommended to use the ADI_CT_INTERRUPT_TYPE type.
Definition at line 4103 of file captouch.c.
Referenced by adi_CT_NoiseMeasurement(), and adi_CT_Stage_AutoCAPDAC_Adjustment().
ADI_CT_RESULT_TYPE adi_CT_SetPGABiasCurrent (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_PGA_BIAS_TYPE const PGABias)
Set the PGA Bias Current.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] PGABias PGA Bias Current
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The PGA Bias Current is set by PGABias. PGABias must be a ADI_CT_PGA_BIAS_TYPE variable
Definition at line 1482 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_SetPK2PKCfg (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_PK2PK_TYPE *const pPK2PK_Settings)
Set the Peak to Peak Parameters.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] pPK2PK_Settings Struct which includes the different PK2PK parameters
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The Peak to Peak Settings are set by pPK2PK_Settings. pPK2PK_Settings must be a ADI_CT_PK2PK_TYPE structs which includes:
PK2PKAvg Number of Samples to be averaged
PK2PKAvgMin Minimum rank position for averaging
PK2PKSubset Subset of Number of Samples to be used for the calculations
PK2PKNumSamples Number of Samples to be used for the calculations
Definition at line 1655 of file captouch.c.
Referenced by adi_CT_SetGenericSettings().
ADI_CT_RESULT_TYPE adi_CT_SetPowerStatus (ADI_CT_DEV_HANDLE const hDevice, bool_t const Enable)
Power Up/Down the Captouch.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] Enable True or False, to power up or down the Captouch
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The function sets the power Captouch status True -> Enable False-> Disable
Definition at line 725 of file captouch.c.
Referenced by adi_CT_NoiseMeasurement(), and adi_CT_Stage_AutoCAPDAC_Adjustment().
ADI_CT_RESULT_TYPE adi_CT_SetReleaseCfg (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_TOUCH_AND_RELEASE_TYPE *const pReleaseSettings)
Set the Release Detection Settings.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] pReleaseSettings Struct which includes the different Release Settings
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The Release Settings are set by pReleaseSettings. pReleaseSettings must be a ADI_CT_TOUCH_AND_RELEASE_TYPE struct which includes: InputA Source A InputB Source B UpperThreshold Upper Thershold LowerThreshold Lower Thershold MinDuration Minimum touch Duration
Definition at line 3788 of file captouch.c.
Referenced by adi_CT_SetGenericSettings().
ADI_CT_RESULT_TYPE adi_CT_SetReleaseEnable (ADI_CT_DEV_HANDLE const hDevice, bool_t const Enable)
Enable the Release Detection.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] Enable Status of Release Detection
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The function enables the Release Detection True -> Enable False -> Disable
Definition at line 3579 of file captouch.c.
Referenced by adi_CT_Stage_AutoCAPDAC_Adjustment().
ADI_CT_RESULT_TYPE adi_CT_SetSelfTimerEnable (ADI_CT_DEV_HANDLE const hDevice, bool_t const Enable)
Enable/Disable the Self Timer.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] Enable SelfTimer status
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The function sets the Self Timer status True -> Enable False -> Disable
Definition at line 1147 of file captouch.c.
Referenced by adi_CT_NoiseMeasurement(), and adi_CT_Stage_AutoCAPDAC_Adjustment().
ADI_CT_RESULT_TYPE adi_CT_SetSelfTimerValue (ADI_CT_DEV_HANDLE const hDevice, uint16_t const SelfTimerWait)
Set the Self Timer Value.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] SelfTimerWait Digital Self Timer Value.
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The Self Timer Value configuration is set by SelfTimerWait. Each LSB corresponds to 1.95ms. Range [0-998]ms.
Definition at line 1230 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_SetStageByPassPGA (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, bool_t const ByPassPGA)
Bypass the PGA.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] StageNumber Stage to configure
[in] ByPassPGA BYPASS Gain Status
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The function sets the PGA gain status for a specific stage. True -> Override False -> Not Override
Definition at line 2650 of file captouch.c.
Referenced by adi_CT_SetStageGenericCfg().
ADI_CT_RESULT_TYPE adi_CT_SetStageC2VRange (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, ADI_CT_C2VRANGE_TYPE const C2VRange)
Set the C2V Range.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] StageNumber Stage to configure
[in] C2VRange C2V Range
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The C2V Range is set by C2VRange. C2VRange must be a ADI_CT_C2VRANGE_TYPE variable. It is recommended to use the ADI_CT_STAGE_NUMBER_TYPE type to select the Stage to configure.
Definition at line 2831 of file captouch.c.
Referenced by adi_CT_SetStageGenericCfg().
ADI_CT_RESULT_TYPE adi_CT_SetStageCAPDACEnable (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, bool_t const Enable)
Enable the CAPDAC for each Stage.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] StageNumber Stage to configure
[in] Enable Enable the CAPDAC
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The function sets CAPDAC status for a specific stage. True -> Enable False -> Disable It is recommended to use the ADI_CT_STAGE_NUMBER_TYPE type to select the Stage to configure.
Definition at line 3111 of file captouch.c.
Referenced by adi_CT_NoiseMeasurement(), and adi_CT_SetStageGenericCfg().
ADI_CT_RESULT_TYPE adi_CT_SetStageCAPDACValue (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, uint8_t const MAIN_DAC_Value, uint8_t const SUB_DAC_Value)
Set the CAPDAC values for each Stage.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] StageNumber Stage to configure
[in] MAIN_DAC_Value MAIN DAC Value (7 bits)
[in] SUB_DAC_Value SUB DAC Value (3 bits)
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The MAIN_DAC_Value is a 7 bits value and the SUB_DAC_Value is a 3 bits. It is recommended to use the ADI_CT_STAGE_NUMBER_TYPE type to select the Stage to configure.
Definition at line 3201 of file captouch.c.
Referenced by adi_CT_SetStageGenericCfg().
ADI_CT_RESULT_TYPE adi_CT_SetStageFreqHoppingEnable (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, bool_t const Enable)
Set the system ready to start a Frequency Hopping Algorithm.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] StageNumber Stage to configure
[in] Enable Frequency Hopping Algorithm Condition (disable the excitation)
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
True -> Disable the signal excitation False -> Enable the signal excitation (normal operation) It is recommended to use the ADI_CT_STAGE_NUMBER_TYPE type to select the Stage to configure.
Definition at line 3018 of file captouch.c.
Referenced by adi_CT_NoiseMeasurement(), and adi_CT_SetStageGenericCfg().
ADI_CT_RESULT_TYPE adi_CT_SetStageGenericCfg (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, ADI_CT_INPUT_TYPE const CDCInput, ADI_STAGE_TYPE *const pStageType)
Set the Stage Configuration.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] StageNumber Stage to configure
[in] CDCInput Selected Input
[in] pStageType Stage Configuration
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The Stage Configuration is set by pStageType. pStageType must be a ADI_STAGE_TYPE struct. The CDC Input is set by CDCInput. CDCInput must be a ADI_CT_INPUT_TYPE variable. It is recommended to use the ADI_CT_STAGE_NUMBER_TYPE type to select the Stage to configure.
Definition at line 2365 of file captouch.c.
Referenced by adi_CT_NoiseMeasurement().
ADI_CT_RESULT_TYPE adi_CT_SetStagePGAGain (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, ADI_CT_PGA_GAIN_TYPE PGA_Gain)
Set the PGA Gain.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] StageNumber Stage to configure
[in] PGA_Gain PGA Gain
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The PGA Gain is set by PGA_Gain. PGA_Gain must be a ADI_CT_PGA_GAIN_TYPE variable. It is recommended to use the ADI_CT_STAGE_NUMBER_TYPE type to select the Stage to configure.
Definition at line 2739 of file captouch.c.
Referenced by adi_CT_SetStageGenericCfg().
ADI_CT_RESULT_TYPE adi_CT_SetStagePK2PKEnable (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, bool_t const Enable)
Enables the Noise Peak to Peak Measurements.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] StageNumber Stage to configure
[in] Enable Peak to Peak Measurements Enable
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The function sets the Peak to Peak Measurements status for a specific stage. True -> Enable False -> Disable It is recommended to use the ADI_CT_STAGE_NUMBER_TYPE type to select the Stage to configure.
Definition at line 2924 of file captouch.c.
Referenced by adi_CT_SetStageGenericCfg().
ADI_CT_RESULT_TYPE adi_CT_SetStagesCalibrationEnable (ADI_CT_DEV_HANDLE const hDevice, uint16_t const Stages, bool_t const enable)
Enable the Calibration for one or more specific Stages.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] Stages Stages to Enable the Calibration
[in] enable Status
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
To enable the Calibratrion of a specific Stage, the bit associated to that Stage must be 1. It is recommended to use the ADI_CT_STAGE_BIT_TYPE type to select the Stages to enable/disable.
Definition at line 2462 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_SetStageSelectInput (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, ADI_CT_INPUT_TYPE const CDCInput)
Set the CDC Input.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] StageNumber Stage to configure
[in] CDCInput Selected Input
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The CDC Input is set by CDCInput. CDCInput must be a ADI_CT_INPUT_TYPE variable. It is recommended to use the ADI_CT_STAGE_NUMBER_TYPE type to select the Stage to configure.
Definition at line 2549 of file captouch.c.
Referenced by adi_CT_SetStageGenericCfg().
ADI_CT_RESULT_TYPE adi_CT_SetStagesEnable (ADI_CT_DEV_HANDLE const hDevice, uint16_t const Stages, bool_t const enable)
Set Enable CT Stages.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] Stages Stages to Enable
[in] enable Status
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
To enable a specific Stage, the bit associated to that Stage must be 1. It is recommended to use the ADI_CT_STAGE_BIT_TYPE type.
Definition at line 3304 of file captouch.c.
Referenced by adi_CT_NoiseMeasurement().
ADI_CT_RESULT_TYPE adi_CT_SetStageSensorThreshold (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_STAGE_NUMBER_TYPE const StageNumber, uint16_t const SensorThreshold)
Set the Sensor Threshold.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] StageNumber Stage to Configure
[in] SensorThreshold Digital Self Timer Value
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
SensorThreshold is a 14 bit value. It is recommended to use the ADI_CT_STAGE_BIT_TYPE type.
Definition at line 3385 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_SetStartSingleSequence (ADI_CT_DEV_HANDLE const hDevice)
Starts a single C2V conversion sequence.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
This function forces a single C2V conversion
Definition at line 4650 of file captouch.c.
Referenced by adi_CT_NoiseMeasurement(), and adi_CT_Stage_AutoCAPDAC_Adjustment().
ADI_CT_RESULT_TYPE adi_CT_SetTimingsCfg (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_C2V_TIMING_TYPE *const pTimingSettings)
Set the Conversion Timings Parameters.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] pTimingSettings Struct which includes the different timings values
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error.
The Timing configuration is set by pTimingSettings. pTimingSettings must be a ADI_CT_C2V_TIMING_TYPE structs which includes: AutozeroDuty ADI_CT_AUTOZERODUTY_TYPE C2VHoldTime Capaticitance to Voltage Time. 5 bits, each LSB represents 0.25us, range [0.25-8]us. Phase13 Phase13 Time. 5 bits, each LSB represents 0.25us, range [0.25-8]us. Phase24 Phase24 Time. 8 bits, each LSB represents 0.25us, range [0.0625-16]us.
Definition at line 1035 of file captouch.c.
Referenced by adi_CT_FrequencyHoppingAlgorithm(), and adi_CT_SetGenericSettings().
ADI_CT_RESULT_TYPE adi_CT_SetTouchCfg (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_TOUCH_AND_RELEASE_TYPE *const pTouchSettings)
Set the Touch Detection Settings.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] pTouchSettings Struct which includes the different Touch Settings
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The Touch Settings are set by pTouchSettings. pTouchSettings must be a ADI_CT_TOUCH_AND_RELEASE_TYPE struct which includes: InputA Source A InputB Source B UpperThreshold Upper Thershold LowerThreshold Lower Thershold MinDuration Minimum touch Duration
Definition at line 3664 of file captouch.c.
Referenced by adi_CT_SetGenericSettings().
ADI_CT_RESULT_TYPE adi_CT_SetTouchEnable (ADI_CT_DEV_HANDLE const hDevice, bool_t const Enable)
Enable the Touch Detection.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] Enable Status of Touch Detection
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The function enables the Touch Detection True -> Enable False -> Disable
Definition at line 3499 of file captouch.c.
Referenced by adi_CT_Stage_AutoCAPDAC_Adjustment().
ADI_CT_RESULT_TYPE adi_CT_SetUnmatchedPads (ADI_CT_DEV_HANDLE const hDevice, ADI_CT_UNMATCHED_PADS_TYPE const UnmatchedPads)
Set the Unmatched Pads Configuration.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
[in] UnmatchedPads Unmatched Pads configuration
Returns
Status
ADI_CT_RESULT_SUCCESS Call completed successfully.
ADI_CT_RESULT_ERR Error: Device has not been initialized for use, see adi_CT_Init().
The Unmatched Pads Configuration is set by UnmatchedPads. UnmatchedPads must be a ADI_CT_UNMATCHED_PADS_TYPE variable
Definition at line 948 of file captouch.c.
ADI_CT_RESULT_TYPE adi_CT_UnInit (ADI_CT_DEV_HANDLE const hDevice)
Uninitialize the CT device.
Parameters
[in] hDevice Device handle obtained from adi_CT_Init().
Returns
Status
              - #ADI_CT_RESULT_SUCCESS                        Call completed successfully.
              - #ADI_CT_RESULT_ERR                            Error: Device has not been initialized for use, see #adi_CT_Init().
Definition at line 579 of file captouch.c.