ADuCM350BBCZ Device Drivers API Reference Manual: WUT Driver
WUT Driver
Macros
#define ADI_WUT_TARGET_MASK
#define ASSERT_ADI_MISRA_SUPPRESSIONS
#define REVERT_ADI_MISRA_SUPPRESSIONS
Typedefs
typedef struct
ADI_WUT_DEV_DATA_TYPE ADI_WUT_DEV_DATA_TYPE
typedef struct
ADI_WUT_DEV_DATA_TYPE * ADI_WUT_DEV_HANDLE
Enumerations
enum ADI_WUT_CLOCK_SOURCE_TYPE {
ADI_WUT_CLK_PCLK = 0,
ADI_WUT_CLK_LFXTAL,
ADI_WUT_CLK_LFOSC
}
enum ADI_WUT_DEV_ID_TYPE {
ADI_WUT_DEVID_0 = 0,
ADI_WUT_MAX_DEVID
}
enum ADI_WUT_MODE_TYPE {
ADI_WUT_MODE_FREERUNNING,
ADI_WUT_MODE_PERIODIC
}
enum ADI_WUT_PRESCALER_TYPE {
ADI_WUT_PRE_DIV1 = T2CON_PRE_DIV1,
ADI_WUT_PRE_DIV16 = T2CON_PRE_DIV16,
ADI_WUT_PRE_DIV256 = T2CON_PRE_DIV256,
ADI_WUT_PRE_DIV32768 = T2CON_PRE_DIV32768
}
enum ADI_WUT_RESULT_TYPE {
ADI_WUT_SUCCESS = 0,
ADI_WUT_ERR_UNKNOWN = ADI_DEV_WUT_ERROR_OFFSET,
ADI_WUT_ERR_ALREADY_INITIALIZED,
ADI_WUT_ERR_BAD_DEV_HANDLE,
ADI_WUT_ERR_BAD_DEV_ID,
ADI_WUT_ERR_FUNCTION_FAILED,
ADI_WUT_ERR_NOT_INITIALIZED,
ADI_WUT_ERR_NULL_DATA_POINTER,
ADI_WUT_ERR_PARAM_OUT_OF_RANGE
}
enum ADI_WUT_STATE_TYPE {
ADI_WUT_STATE_UNINITIALIZED = 0,
ADI_WUT_STATE_INITIALIZED
}
enum ADI_WUT_TARGET_TYPE {
ADI_WUT_COMPA = (1 << BITP_WUT_T2IEN_WUFA),
ADI_WUT_COMPB = (1 << BITP_WUT_T2IEN_WUFB),
ADI_WUT_COMPC = (1 << BITP_WUT_T2IEN_WUFC),
ADI_WUT_COMPD = (1 << BITP_WUT_T2IEN_WUFD),
ADI_WUT_ROLL = (1 << BITP_WUT_T2IEN_ROLL)
}
Functions
ADI_INT_HANDLER (WakeUp_Int_Handler)
WUT device driver interrupt handler. Overrides weakly-bound default interrupt handler in startup.c.
ADI_WUT_RESULT_TYPE adi_WUT_ClearInterruptFlag (ADI_WUT_DEV_HANDLE const hDevice, const ADI_WUT_TARGET_TYPE target)
Clear one of the Wakeup Timer interrupt flag.
ADI_WUT_CLOCK_SOURCE_TYPE adi_WUT_GetClockSelect (ADI_WUT_DEV_HANDLE const hDevice)
Get the Wakeup Timer clock source.
uint32_t adi_WUT_GetComparator (ADI_WUT_DEV_HANDLE const hDevice, const ADI_WUT_TARGET_TYPE target)
Get one of the Wakeup Timer comparators.
uint32_t adi_WUT_GetCurrentCount (ADI_WUT_DEV_HANDLE const hDevice)
Get the current Wakeup Timer count value.
bool_t adi_WUT_GetFreezeEnable (ADI_WUT_DEV_HANDLE const hDevice)
Get the Wakeup Timer Freeze mode for timer value readbacks.
bool_t adi_WUT_GetInterruptEnable (ADI_WUT_DEV_HANDLE const hDevice, const ADI_WUT_TARGET_TYPE target)
Read the Wakeup Timer interrupt enable state.
uint16_t adi_WUT_GetIntervalA (ADI_WUT_DEV_HANDLE const hDevice)
Get the Wakeup Timer Interval register.
ADI_WUT_PRESCALER_TYPE adi_WUT_GetPrescaler (ADI_WUT_DEV_HANDLE const hDevice)
Get the Wakeup Timer clock input prescaler.
uint16_t adi_WUT_GetStatusRegister (ADI_WUT_DEV_HANDLE const hDevice)
Get the value of Status register.
bool_t adi_WUT_GetTimerEnable (ADI_WUT_DEV_HANDLE const hDevice)
Get the Wakeup Timer enable mode.
ADI_WUT_MODE_TYPE adi_WUT_GetTimerMode (ADI_WUT_DEV_HANDLE const hDevice)
Get the Wakeup Timer mode.
bool_t adi_WUT_GetWakeUpEnable (ADI_WUT_DEV_HANDLE const hDevice)
Get the Wakeup enable.
ADI_WUT_RESULT_TYPE adi_WUT_Init (ADI_WUT_DEV_ID_TYPE const devID, ADI_WUT_DEV_HANDLE *const phDevice)
Initialize and allocate the Wakeup Timer.
ADI_WUT_RESULT_TYPE adi_WUT_RegisterCallback (ADI_WUT_DEV_HANDLE const hDevice, ADI_CALLBACK const cbFunc, uint32_t const cbWatch)
WUT Application callback registration API.
ADI_WUT_RESULT_TYPE adi_WUT_SetClockSelect (ADI_WUT_DEV_HANDLE const hDevice, const ADI_WUT_CLOCK_SOURCE_TYPE ClockSource)
Set the Wakeup Timer clock source.
ADI_WUT_RESULT_TYPE adi_WUT_SetComparator (ADI_WUT_DEV_HANDLE const hDevice, const ADI_WUT_TARGET_TYPE target, const uint32_t value)
Set Wakeup Timer comparator value(s).
ADI_WUT_RESULT_TYPE adi_WUT_SetFreezeEnable (ADI_WUT_DEV_HANDLE const hDevice, const bool_t bEnable)
Set the Wakeup Timer Freeze mode for timer value readbacks.
ADI_WUT_RESULT_TYPE adi_WUT_SetInterruptEnable (ADI_WUT_DEV_HANDLE const hDevice, const ADI_WUT_TARGET_TYPE target, const bool_t bEnable)
Set/clear Wakeup Timer interrupt enables.
ADI_WUT_RESULT_TYPE adi_WUT_SetIntervalA (ADI_WUT_DEV_HANDLE const hDevice, const uint16_t value)
Set the Wakeup Timer Interval register.
ADI_WUT_RESULT_TYPE adi_WUT_SetPrescaler (ADI_WUT_DEV_HANDLE const hDevice, const ADI_WUT_PRESCALER_TYPE PreScaler)
Set the Wakeup Timer clock input prescaler.
ADI_WUT_RESULT_TYPE adi_WUT_SetTimerEnable (ADI_WUT_DEV_HANDLE const hDevice, const bool_t bEnable)
Set the Wakeup Timer enable mode.
ADI_WUT_RESULT_TYPE adi_WUT_SetTimerMode (ADI_WUT_DEV_HANDLE const hDevice, const ADI_WUT_MODE_TYPE Mode)
Set the Wakeup Timer mode.
ADI_WUT_RESULT_TYPE adi_WUT_SetWakeUpEnable (ADI_WUT_DEV_HANDLE const hDevice, const bool_t bEnable)
Set the Wakeup enable.
ADI_WUT_RESULT_TYPE adi_WUT_UnInit (ADI_WUT_DEV_HANDLE const hDevice)
Uninitialize and deallocate the Wakeup Timer.
Detailed Description
Macro Definition Documentation
#define ADI_WUT_TARGET_MASK
Value:
(ADI_WUT_COMPA  \
                             | ADI_WUT_COMPB  \
                             | ADI_WUT_COMPC  \
                             | ADI_WUT_COMPD  \
                             | ADI_WUT_ROLL)
target mask value
Definition at line 106 of file wut.h.
Referenced by ADI_INT_HANDLER(), adi_WUT_ClearInterruptFlag(), adi_WUT_GetInterruptEnable(), adi_WUT_RegisterCallback(), and adi_WUT_SetInterruptEnable().
#define ASSERT_ADI_MISRA_SUPPRESSIONS
Apply ADI MISRA Suppressions
Definition at line 23 of file wut.c.
#define REVERT_ADI_MISRA_SUPPRESSIONS
Revert ADI MISRA Suppressions
Definition at line 1084 of file wut.c.
Typedef Documentation
typedef struct ADI_WUT_DEV_DATA_TYPE* ADI_WUT_DEV_HANDLE
WUT Device instance data handle typedef
Definition at line 114 of file wut.h.
Enumeration Type Documentation
enum ADI_WUT_CLOCK_SOURCE_TYPE
WUT clock sources.
Enumerator
ADI_WUT_CLK_PCLK
WUT clock selector for internal PCLK.
ADI_WUT_CLK_LFXTAL
WUT clock selector for external 32k crystal.
ADI_WUT_CLK_LFOSC
WUT clock selector for internal 32k oscillator.
Definition at line 70 of file wut.h.
enum ADI_WUT_DEV_ID_TYPE
WUT device ID.
Enumerator
ADI_WUT_DEVID_0
The one and only wakeup timer instance.
Definition at line 37 of file wut.h.
enum ADI_WUT_MODE_TYPE
WUT run modes.
Enumerator
ADI_WUT_MODE_FREERUNNING
Set WUT to free-running mode.
ADI_WUT_MODE_PERIODIC
set WUT to periodic mode.
Definition at line 79 of file wut.h.
enum ADI_WUT_PRESCALER_TYPE
WUT clock dividers.
Enumerator
ADI_WUT_PRE_DIV1
Set prescaler to clock/1.
ADI_WUT_PRE_DIV16
Set prescaler to clock/16.
ADI_WUT_PRE_DIV256
Set prescaler to clock/256.
ADI_WUT_PRE_DIV32768
Set prescaler to clock/32767.
Definition at line 87 of file wut.h.
enum ADI_WUT_RESULT_TYPE
WUT device error codes.
Enumerator
ADI_WUT_SUCCESS
Generic success.
ADI_WUT_ERR_UNKNOWN
Generic error/
ADI_WUT_ERR_ALREADY_INITIALIZED
WUT device is already initialized.
ADI_WUT_ERR_BAD_DEV_HANDLE
Invalid device handle.
ADI_WUT_ERR_BAD_DEV_ID
Invalid device ID.
ADI_WUT_ERR_FUNCTION_FAILED
generic app error.
ADI_WUT_ERR_NOT_INITIALIZED
WUT device is uninitialized.
ADI_WUT_ERR_NULL_DATA_POINTER
NULL data pointer not allowed.
ADI_WUT_ERR_PARAM_OUT_OF_RANGE
Parameter is out of range.
Definition at line 45 of file wut.h.
enum ADI_WUT_STATE_TYPE
WUT device initialization status.
Enumerator
ADI_WUT_STATE_UNINITIALIZED
WUT is not initialized.
ADI_WUT_STATE_INITIALIZED
WUT driver initialized.
Definition at line 62 of file wut.h.
enum ADI_WUT_TARGET_TYPE
WUT comparator designations.
Enumerator
ADI_WUT_COMPA
Primary FieldA comparator designation.
ADI_WUT_COMPB
Secondary FieldB comparator designation.
ADI_WUT_COMPC
Secondary FieldC comparator designation.
ADI_WUT_COMPD
Secondary FieldD comparator designation.
ADI_WUT_ROLL
Rollover interrupt designation.
Definition at line 97 of file wut.h.
Function Documentation
ADI_WUT_RESULT_TYPE adi_WUT_ClearInterruptFlag (ADI_WUT_DEV_HANDLE const hDevice, const ADI_WUT_TARGET_TYPE target)
Clear one of the Wakeup Timer interrupt flag.
Parameters
[in] hDevice Device handle obtained from adi_WUT_Init().
[in] target Target comparator.
Returns
Status
ADI_WUT_ERR_BAD_DEV_HANDLE [D] Invalid device handle parameter.
ADI_WUT_ERR_NOT_INITIALIZED [D] Device has not been previously configured for use.
ADI_WUT_ERR_PARAM_OUT_OF_RANGE [D] Invalid parameter.
ADI_WUT_SUCCESS Call completed successfully.
Clear either the rollover (free-running mode only) or one of the comparator interrupt flags. Uses a write-once-to-clear logic, self-clears the bit and is not readable.
Definition at line 891 of file wut.c.
Referenced by ADI_INT_HANDLER().
ADI_WUT_CLOCK_SOURCE_TYPE adi_WUT_GetClockSelect (ADI_WUT_DEV_HANDLE const hDevice)
Get the Wakeup Timer clock source.
Parameters
[in] hDevice Device handle obtained from adi_WUT_Init().
Returns
One of the ADI_WUT_CLOCK_SOURCE_TYPE enumeration values, indicating the currently active clock select.
Get the currently selected clock source for driving the wakeup timer's 32-bit up counter.
See Also
adi_WUT_GetClockSelect().
adi_WUT_SetPrescaler().
Definition at line 295 of file wut.c.
uint32_t adi_WUT_GetComparator (ADI_WUT_DEV_HANDLE const hDevice, const ADI_WUT_TARGET_TYPE target)
Get one of the Wakeup Timer comparators.
Parameters
[in] hDevice Device handle obtained from adi_WUT_Init().
[in] target Target comparator.
Returns
Value of comparator designated by the ADI_WUT_TARGET_TYPE parameter.
Get one of the three, 32-bit comparator values: COMPB, COMPC, COMPD. Both the upper and lower 16-bit comparator registers are read for the target comparator. Returns zero for invalid or zero-valued comparators. ADI_WUT_TARGET_TYPE types may not be combined, as only the last valid target type will prevail.
Note
: ADI_WUT_TARGET_TYPE types ADI_WUT_COMPA and ADI_WUT_ROLL are excluded from this API. These target types generate the ADI_WUT_ERR_PARAM_OUT_OF_RANGE return code in debug mode. These target types generate the ADI_WUT_SUCCESS return code in non-debug mode, but no action is performed.
See Also
adi_WUT_SetComparator().
Definition at line 421 of file wut.c.
uint32_t adi_WUT_GetCurrentCount (ADI_WUT_DEV_HANDLE const hDevice)
Get the current Wakeup Timer count value.
Parameters
[in] hDevice Device handle obtained from adi_WUT_Init().
Returns
Timer value.
Get the 32-bit current Wakeup Time count value. Forces the "freeze" mode to insure both upper 16-bits and lower 16-bits reads are atomic. Restores freeze mode before exit.
Definition at line 856 of file wut.c.
bool_t adi_WUT_GetFreezeEnable (ADI_WUT_DEV_HANDLE const hDevice)
Get the Wakeup Timer Freeze mode for timer value readbacks.
Parameters
[in] hDevice Device handle obtained from adi_WUT_Init().
Returns
Returns the current state of the Wakeup Timer Freeze mode.
true Wakeup Timer Freeze mode is set.
false Wakeup Timer Freeze mode is cleared.
Gets the freeze mode for timer value readbacks.
See Also
adi_WUT_SetFreezeEnable().
Definition at line 499 of file wut.c.
Referenced by adi_WUT_GetCurrentCount().
bool_t adi_WUT_GetInterruptEnable (ADI_WUT_DEV_HANDLE const hDevice, const ADI_WUT_TARGET_TYPE target)
Read the Wakeup Timer interrupt enable state.
Parameters
[in] hDevice Device handle obtained from adi_WUT_Init().
[in] target Target comparator or rollover interrupt.
Returns
Returns the interrupt enable status of a target comparator.
true Interrupt(s) is(are) enabled.
false Interrupt(s) is(are) disabled.
Returns a boolean value indicating if the set of #ADI_WUT_TARGET_TYPEs are enabled or not. May be used to query singular or multiple enables.
See Also
adi_WUT_SetInterruptEnable().
Definition at line 575 of file wut.c.
Referenced by adi_WUT_SetComparator().
uint16_t adi_WUT_GetIntervalA (ADI_WUT_DEV_HANDLE const hDevice)
Get the Wakeup Timer Interval register.
Parameters
[in] hDevice Device handle obtained from adi_WUT_Init().
Returns
Returns the 12-bit Wakeup Timer Interval register value.
See Also
adi_WUT_SetIntervalA().
Definition at line 652 of file wut.c.
ADI_WUT_PRESCALER_TYPE adi_WUT_GetPrescaler (ADI_WUT_DEV_HANDLE const hDevice)
Get the Wakeup Timer clock input prescaler.
Parameters
[in] hDevice Device handle obtained from adi_WUT_Init().
Returns
Currently active clock prescaler.
Get the Wakeup Timer clock prescaler.
See Also
adi_WUT_SetPrescaler().
Definition at line 717 of file wut.c.
uint16_t adi_WUT_GetStatusRegister (ADI_WUT_DEV_HANDLE const hDevice)
Get the value of Status register.
Parameters
[in] hDevice Device handle obtained from adi_WUT_Init().
Returns
Wakeup Timer Status register value.
Definition at line 924 of file wut.c.
bool_t adi_WUT_GetTimerEnable (ADI_WUT_DEV_HANDLE const hDevice)
Get the Wakeup Timer enable mode.
Parameters
[in] hDevice Device handle obtained from adi_WUT_Init().
Returns
Returns the timer enable status.
true Timer is enabled.
false Timer is disabled.
Gets the current Wakeup Timer enablement state.
See Also
adi_WUT_SetTimerEnable().
Definition at line 772 of file wut.c.
Referenced by adi_WUT_SetComparator(), and adi_WUT_SetIntervalA().
ADI_WUT_MODE_TYPE adi_WUT_GetTimerMode (ADI_WUT_DEV_HANDLE const hDevice)
Get the Wakeup Timer mode.
Parameters
[in] hDevice Device handle obtained from adi_WUT_Init().
Returns
Returns the timer mode.
ADI_WUT_MODE_FREERUNNING Timer is in freerunning mode.
ADI_WUT_MODE_PERIODIC Timer is in periodic mode.
Get the Wakeup Timer operational mode.
See Also
adi_WUT_SetTimerMode().
Definition at line 838 of file wut.c.
bool_t adi_WUT_GetWakeUpEnable (ADI_WUT_DEV_HANDLE const hDevice)
Get the Wakeup enable.
Parameters
[in] hDevice Device handle obtained from adi_WUT_Init().
Returns
Returns the WakeUp enable status.
true To enable the wake up timer even when the core clock is off.
false To disable the wake up timer even when the core clock is off.
Get the enable/disable status of the Wakeup timer when the core clock is off.
See Also
adi_WUT_SetWakeUpEnable().
Definition at line 943 of file wut.c.
ADI_WUT_RESULT_TYPE adi_WUT_Init (ADI_WUT_DEV_ID_TYPE const devID, ADI_WUT_DEV_HANDLE *const phDevice)
Initialize and allocate the Wakeup Timer.
Parameters
[in] devID Zero-based device index designating which device to initialize.
[out] phDevice The caller's device handle pointer for storing the initialized device instance data.
Returns
Status
ADI_WUT_ERR_ALREADY_INITIALIZED [D] Specified device has already been initialized.
ADI_WUT_ERR_BAD_DEV_ID [D] Invalid device index.
ADI_WUT_SUCCESS Call completed successfully.
Initialize the WUT device using default internal configuration settings and allocate the device for use. The caller's device handle is written with the device instance data pointer. The returned device handle is required to be passed to all subsequent device driver API calls to convey which device instance to operate on.
Note
The contents of phDevice will be set to NULL upon failure.
See Also
adi_WUT_UnInit().
Definition at line 129 of file wut.c.
ADI_WUT_RESULT_TYPE adi_WUT_RegisterCallback (ADI_WUT_DEV_HANDLE const hDevice, ADI_CALLBACK const cbFunc, uint32_t const cbWatch)
WUT Application callback registration API.
Parameters
[in] hDevice Device handle obtained from adi_WUT_Init().
[in] cbFunc Application callback address; the function to call on the interrupt.
[in] cbWatch Bitfield indicating which WUT interrupts to watch, resulting a callback.
Returns
Status
ADI_WUT_SUCCESS Success: The callback is successfully registered.
ADI_WUT_ERR_BAD_DEV_HANDLE [D] Error: Invalid device handle parameter.
ADI_WUT_ERR_NOT_INITIALIZED [D] Error: Device has not been initialized for use, see adi_WUT_Init().
ADI_WUT_ERR_PARAM_OUT_OF_RANGE [D] Error: The specified watch bits are out of range.
Registers an application-defined callback cbFunc function address of type ADI_CALLBACK with the WUT device driver. Callbacks are made in response to WUT interrupts, depending on whether they are enabled and whether the corresponding callback watch bits are set. This allows the application to control which interrupts it wants to be called back on.
The callback to the application is made in context of the originating interrupt, so extended processing is discouraged soas to not lock out lower-priority interrupts.
Note
CALLBACKS: Callbacks are disabled by default during WUT device driver initialization (adi_WUT_Init()). The application may use the adi_WUT_RegisterCallback() API to register an application-provided callback function with the WUT device driver. The callback registration API takes an interrupt target mask (of type ADI_WUT_TARGET_TYPE) to designate which interrupts to watch. When any of the watched interrupts occur, the WUT device driver will make the callback to the application for interrupt handling. The application callback should avoid extended processing within the callback as the callback is made context of the initiating interrupt and will block lower-priority interrupts. If extended interrupt processing is required, the application should schedule it for the main application loop and exit the callback as soon as possible.
See Also
adi_WUT_Init().
adi_WUT_SetInterruptEnable().
adi_WUT_ClearInterruptFlag().
Definition at line 1032 of file wut.c.
ADI_WUT_RESULT_TYPE adi_WUT_SetClockSelect (ADI_WUT_DEV_HANDLE const hDevice, const ADI_WUT_CLOCK_SOURCE_TYPE ClockSource)
Set the Wakeup Timer clock source.
Parameters
[in] hDevice Device handle obtained from adi_WUT_Init().
[in] ClockSource Desired clock source; one of the ADI_WUT_CLOCK_SOURCE_TYPE enumeration values.
Returns
Status
ADI_WUT_ERR_BAD_DEV_HANDLE [D] Invalid device handle parameter.
ADI_WUT_ERR_NOT_INITIALIZED [D] Device has not been previously configured for use.
ADI_WUT_ERR_PARAM_OUT_OF_RANGE [D] Invalid parameter.
ADI_WUT_SUCCESS Call completed successfully.
Select the clock source to drive the wakeup timer's 32-bit up counter. The selected clock is divided by the current clock prescaler value, as set by adi_WUT_SetPrescaler().
Note
If selecting the external clock source, #ADI_WUT_CLK_EXTCLK, the external crystal oscillator circuit must be physically present and specifically enabled via the Power Device Driver.
If and when disabeling the "External Clock" source, make sure it is not also being used as a system clock mutplixer input by some other system resource.
See Also
adi_WUT_GetClockSelect().
adi_WUT_SetPrescaler().
Definition at line 255 of file wut.c.
ADI_WUT_RESULT_TYPE adi_WUT_SetComparator (ADI_WUT_DEV_HANDLE const hDevice, const ADI_WUT_TARGET_TYPE target, const uint32_t value)
Set Wakeup Timer comparator value(s).
Parameters
[in] hDevice Device handle obtained from adi_WUT_Init().
[in] target Target comparator(s).
[in] value Comparator value.
Returns
Status
ADI_WUT_ERR_BAD_DEV_HANDLE [D] Invalid device handle parameter.
ADI_WUT_ERR_NOT_INITIALIZED [D] Device has not been previously configured for use.
ADI_WUT_ERR_PARAM_OUT_OF_RANGE [D] Invalid parameter.
ADI_WUT_SUCCESS Call completed successfully.
Set any set of the three, writable 32-bit comparator registers: B, C or D. Both the upper and lower 16-bit comparator registers are set for the target comparator(s). Disables the timer and timer interrupts on entry, restores on exit. May set multiple comparators to the same value.
Note
: ADI_WUT_TARGET_TYPE types ADI_WUT_COMPA and ADI_WUT_ROLL are excluded from this API. These target types generate the ADI_WUT_ERR_PARAM_OUT_OF_RANGE return code in debug mode. These target types generate the ADI_WUT_SUCCESS return code in non-debug mode, but no action is performed.
See Also
adi_WUT_GetComparator().
adi_WUT_SetIntervalA().
Definition at line 333 of file wut.c.
ADI_WUT_RESULT_TYPE adi_WUT_SetFreezeEnable (ADI_WUT_DEV_HANDLE const hDevice, const bool_t bEnable)
Set the Wakeup Timer Freeze mode for timer value readbacks.
Parameters
[in] hDevice Device handle obtained from adi_WUT_Init().
[in] bEnable Enable/disable.
Returns
Status
ADI_WUT_ERR_BAD_DEV_HANDLE [D] Invalid device handle parameter.
ADI_WUT_ERR_NOT_INITIALIZED [D] Device has not been previously configured for use.
ADI_WUT_SUCCESS Call completed successfully.
Guarantees an atomic readback of both upper and lower timer registers. Sets the freeze mode for timer value readback, insuring no carry occurs between the upper and lower halfs of 32-bit timer value register while timer reads are performed. When freeze mode is set, the upper 16-bits (T2VAL1) of the 32-bit timer value are locked following a read of the lower 16-bits (T2TVAL0). The lock is automatically released after the read of the the upper 16-bits (T2VAL1). When freeze mode is cleared, an atomic read of the two 16-bit halfs comprising the 32-bit timer value is not guaranteed, i.e., a carry may propagate across the two 16-bit registers between reading the upper and lower halfs.
See Also
adi_WUT_GetFreezeEnable().
Definition at line 465 of file wut.c.
Referenced by adi_WUT_GetCurrentCount().
ADI_WUT_RESULT_TYPE adi_WUT_SetInterruptEnable (ADI_WUT_DEV_HANDLE const hDevice, const ADI_WUT_TARGET_TYPE target, const bool_t bEnable)
Set/clear Wakeup Timer interrupt enables.
Parameters
[in] hDevice Device handle obtained from adi_WUT_Init().
[in] target Target comparator(s).
[in] bEnable Interrupt enable flag.
Returns
Status
ADI_WUT_ERR_BAD_DEV_HANDLE [D] Invalid device handle parameter.
ADI_WUT_ERR_NOT_INITIALIZED [D] Device has not been previously configured for use.
ADI_WUT_ERR_PARAM_OUT_OF_RANGE [D] Invalid parameter.
ADI_WUT_SUCCESS Call completed successfully.
Enable or disable any set of Wakeup Timer interrupts. Causes the Wakeup Timer interrupt to fire: when the Wakeup Timer counter reaches the designated target comparator value or, in the case of the rollover interrupt (used only in "free running" mode), when the timer counter has rolled over from full-scale to zero.
See Also
adi_WUT_GetInterruptEnable().
Definition at line 526 of file wut.c.
Referenced by adi_WUT_SetComparator().
ADI_WUT_RESULT_TYPE adi_WUT_SetIntervalA (ADI_WUT_DEV_HANDLE const hDevice, const uint16_t value)
Set the Wakeup Timer Interval register.
Parameters
[in] hDevice Device handle obtained from adi_WUT_Init().
[in] value New 12-bit interval value.
Returns
Status
ADI_WUT_ERR_BAD_DEV_HANDLE [D] Invalid device handle parameter.
ADI_WUT_ERR_NOT_INITIALIZED [D] Device has not been previously configured for use.
ADI_WUT_ERR_PARAM_OUT_OF_RANGE [D] Invalid parameter.
ADI_WUT_SUCCESS Call completed successfully.
Sets a new 12-bit interval value, stored in the Wakeup Timer T2INC internal register. Also loads bits 16:5 of 32-bit ComparatorA (T2WUFA) with this same value (left-shifted by 5). During normal timer operation, ComparatorA is auto-incremented by the interval value when the timer counter reaches the ComparatorA threshold. If the auto-increment overflows 0xffffffff (timer full-scale) in free-running mode – or the ComparatorD (T2WUFD) value in periodic mode – the modified ComparatorA value is reduced by 0xffffffff or ComparatorD, respectively.
Note
The timer is halted while setting a new value for the interval register, which may affect timer accuracy. If the timer was runing prior to the call, it is resumed before exiting this function.
See Also
adi_WUT_GetIntervalA().
Definition at line 611 of file wut.c.
ADI_WUT_RESULT_TYPE adi_WUT_SetPrescaler (ADI_WUT_DEV_HANDLE const hDevice, const ADI_WUT_PRESCALER_TYPE PreScaler)
Set the Wakeup Timer clock input prescaler.
Parameters
[in] hDevice Device handle obtained from adi_WUT_Init().
[in] PreScaler Clock prescaler enum.
Returns
Status
ADI_WUT_ERR_BAD_DEV_HANDLE [D] Invalid device handle parameter.
ADI_WUT_ERR_NOT_INITIALIZED [D] Device has not been previously configured for use.
ADI_WUT_ERR_PARAM_OUT_OF_RANGE [D] Invalid parameter.
ADI_WUT_SUCCESS Call completed successfully.
Set the Wakeup Timer clock prescaler. The clock input is divided by the prescaler factor, resulting in the Wakeup Timer being incremented once every N clock ticks, where N is one of 1, 16, 256 or 32,768, i.e., one of the clock ADI_WUT_PRESCALER_TYPE enumeration values.
See Also
adi_WUT_SetClockSelect().
adi_WUT_GetPrescaler().
Definition at line 677 of file wut.c.
ADI_WUT_RESULT_TYPE adi_WUT_SetTimerEnable (ADI_WUT_DEV_HANDLE const hDevice, const bool_t bEnable)
Set the Wakeup Timer enable mode.
Parameters
[in] hDevice Device handle obtained from adi_WUT_Init().
[in] bEnable Enable/disable.
Returns
Status
ADI_WUT_ERR_BAD_DEV_HANDLE [D] Invalid device handle parameter.
ADI_WUT_ERR_NOT_INITIALIZED [D] Device has not been previously configured for use.
ADI_WUT_SUCCESS Call completed successfully.
Enables or disables the Wakeup Timer for operation.
See Also
adi_WUT_GetTimerEnable().
Definition at line 738 of file wut.c.
Referenced by adi_WUT_SetComparator(), adi_WUT_SetIntervalA(), and adi_WUT_UnInit().
ADI_WUT_RESULT_TYPE adi_WUT_SetTimerMode (ADI_WUT_DEV_HANDLE const hDevice, const ADI_WUT_MODE_TYPE Mode)
Set the Wakeup Timer mode.
Parameters
[in] hDevice Device handle obtained from adi_WUT_Init().
[in] Mode Timer mode enum.
Returns
Status
ADI_WUT_ERR_BAD_DEV_HANDLE [D] Invalid device handle parameter.
ADI_WUT_ERR_NOT_INITIALIZED [D] Device has not been previously configured for use.
ADI_WUT_ERR_PARAM_OUT_OF_RANGE [D] Invalid parameter.
ADI_WUT_SUCCESS Call completed successfully.
Sets the Wakeup Timer operational mode to either freerunning or periodic.
Note
In periodic mode, the timer automatically resets to zero after reaching the ComparatorD value.
See Also
adi_WUT_GetTimerMode().
Definition at line 796 of file wut.c.
ADI_WUT_RESULT_TYPE adi_WUT_SetWakeUpEnable (ADI_WUT_DEV_HANDLE const hDevice, const bool_t bEnable)
Set the Wakeup enable.
Parameters
[in] hDevice Device handle obtained from adi_WUT_Init().
[in] bEnable Enable/disable.
Returns
Status
ADI_WUT_ERR_BAD_DEV_HANDLE [D] Invalid device handle parameter.
ADI_WUT_ERR_NOT_INITIALIZED [D] Device has not been previously configured for use.
ADI_WUT_SUCCESS Call completed successfully.
Enables or disables the Wakeup timer when the core clock is off.
See Also
adi_WUT_GetWakeUpEnable().
Definition at line 964 of file wut.c.
ADI_WUT_RESULT_TYPE adi_WUT_UnInit (ADI_WUT_DEV_HANDLE const hDevice)
Uninitialize and deallocate the Wakeup Timer.
Parameters
[in] hDevice Device handle obtained from adi_WUT_Init().
Returns
Status
ADI_WUT_ERR_BAD_DEV_HANDLE [D] Invalid device handle parameter.
ADI_WUT_ERR_NOT_INITIALIZED [D] Device has not been previously configured for use.
ADI_WUT_SUCCESS Call completed successfully.
Uninitialize and release the allocated WUT device for other use.
See Also
adi_WUT_Init().
Definition at line 204 of file wut.c.