ADuCM350BBCZ Device Drivers API Reference Manual: SPI Driver
SPI Driver
Data Structures
struct ADI_SPI_CHIP_SELECT_TYPE
struct ADI_SPI_DEV_GENERIC_SETTINGS_TYPE
struct ADI_SPI_TRANSCEIVE_TYPE
Macros
#define ADI_SPI_BITRATE_INITIALIZER 250000 /* depends on processor */
#define ADI_SPI_DMA_INITIALIZER 0
#define ADI_SPI_MASTERCON_INITIALIZER SPICON_MASEN | SPICON_ENABLE
#define ADI_SPI_MAX_TRANSFER_SIZE 256
#define ADI_SPI_SLAVECON_INITIALIZER
#define REVERT_ADI_MISRA_SUPPRESSIONS
Typedefs
typedef struct
ADI_SPI_DEV_DATA_TYPE * ADI_SPI_DEV_HANDLE
Enumerations
enum ADI_SPI_DEV_ID_TYPE {
ADI_SPI_DEVID_0 = 0,
ADI_SPI_DEVID_1,
ADI_SPI_DEVID_H,
ADI_SPI_MAX_DEVID
}
enum ADI_SPI_EVENT { ADI_SPI_EVENT_BUFFER_PROCESSED = 0 }
enum ADI_SPI_IRQ_MODE_TYPE {
ADI_SPI_IRQMODE_T1R1 = 0,
ADI_SPI_IRQMODE_T2R2,
ADI_SPI_IRQMODE_T3R3,
ADI_SPI_IRQMODE_T4R4
}
enum ADI_SPI_RESULT_TYPE {
ADI_SPI_SUCCESS = 0,
ADI_SPI_ERR_UNKNOWN = ADI_DEV_SPI_ERROR_OFFSET,
ADI_SPI_ERR_ALREADY_INITIALIZED = ADI_DEV_SPI_ERROR_OFFSET+1,
ADI_SPI_ERR_BAD_DEV_HANDLE = ADI_DEV_SPI_ERROR_OFFSET+2,
ADI_SPI_ERR_BAD_DEV_ID = ADI_DEV_SPI_ERROR_OFFSET+3,
ADI_SPI_ERR_BAD_DMA_CONFIG = ADI_DEV_SPI_ERROR_OFFSET+4,
ADI_SPI_ERR_BAD_GPIO_CONFIG = ADI_DEV_SPI_ERROR_OFFSET+5,
ADI_SPI_ERR_DMA_ALREADY_IN_USE = ADI_DEV_SPI_ERROR_OFFSET+6,
ADI_SPI_ERR_NO_DMA_FOR_DEVICE = ADI_DEV_SPI_ERROR_OFFSET+7,
ADI_SPI_ERR_NOT_INITIALIZED = ADI_DEV_SPI_ERROR_OFFSET+8,
ADI_SPI_ERR_NULL_DATA_POINTER = ADI_DEV_SPI_ERROR_OFFSET+9,
ADI_SPI_ERR_PARAM_OUT_OF_RANGE = ADI_DEV_SPI_ERROR_OFFSET+10,
ADI_SPI_ERR_UNSUPPORTED_MODE = ADI_DEV_SPI_ERROR_OFFSET+11,
ADI_SPI_ERR_SEMAPHORE_FAILED = ADI_DEV_SPI_ERROR_OFFSET+12
}
enum ADI_SPI_STATE_TYPE {
ADI_SPI_STATE_UNINITIALIZED = 0,
ADI_SPI_STATE_INITIALIZING,
ADI_SPI_STATE_MASTER,
ADI_SPI_STATE_SLAVE
}
Functions
ADI_INT_HANDLER (SPI0_Int_Handler)
SPI0 Interrupt Handler.
ADI_INT_HANDLER (SPI1_Int_Handler)
SPI1 Interrupt Handler.
ADI_INT_HANDLER (SPIH_Int_Handler)
SPIH Interrupt Handler.
ADI_INT_HANDLER (DMA_SPI0_TX_Int_Handler)
SPI0 DMA Transmit Interrupt Handler.
ADI_INT_HANDLER (DMA_SPI0_RX_Int_Handler)
SPI0 DMA Receive Interrupt Handler.
ADI_INT_HANDLER (DMA_SPI1_TX_Int_Handler)
SPI1 DMA Transmit Interrupt Handler.
ADI_INT_HANDLER (DMA_SPI1_RX_Int_Handler)
SPI1 DMA Receive Interrupt Handler.
ADI_INT_HANDLER (DMA_SPIH_TX_Int_Handler)
SPIH DMA Transmit Interrupt Handler.
ADI_INT_HANDLER (DMA_SPIH_RX_Int_Handler)
SPIH DMA Receive Interrupt Handler.
uint32_t adi_SPI_GetBitrate (ADI_SPI_DEV_HANDLE const hDevice)
Get the SPI serial clock frequency.
bool_t adi_SPI_GetBlockingMode (ADI_SPI_DEV_HANDLE const hDevice)
Get the blocking mode.
ADI_SPI_CHIP_SELECT_TYPE adi_SPI_GetChipSelect (ADI_SPI_DEV_HANDLE const hDevice)
Get the currently designated chip select.
bool_t adi_SPI_GetClockPhase (ADI_SPI_DEV_HANDLE const hDevice)
Get the clock phase.
bool_t adi_SPI_GetClockPolarity (ADI_SPI_DEV_HANDLE const hDevice)
Get the clock polarity.
bool_t adi_SPI_GetContinousMode (ADI_SPI_DEV_HANDLE const hDevice)
Get the continuous transfer mode.
bool_t adi_SPI_GetDmaMode (ADI_SPI_DEV_HANDLE const hDevice)
Get the DMA mode.
bool_t adi_SPI_GetDmaRxComplete (ADI_SPI_DEV_HANDLE const hDevice)
Get receive DMA completion status.
bool_t adi_SPI_GetDmaTxComplete (ADI_SPI_DEV_HANDLE const hDevice)
Get transmit DMA completion status.
bool_t adi_SPI_GetFifoRxFlush (ADI_SPI_DEV_HANDLE const hDevice)
Get the SPI receive FIFO flush mode.
bool_t adi_SPI_GetFifoTxFlush (ADI_SPI_DEV_HANDLE const hDevice)
Get the SPI transmit FIFO flush mode.
ADI_SPI_RESULT_TYPE adi_SPI_GetGenericSettings (ADI_SPI_DEV_HANDLE const hDevice, ADI_SPI_DEV_GENERIC_SETTINGS_TYPE *const pSettings)
Get generic SPI settings.
ADI_SPI_IRQ_MODE_TYPE adi_SPI_GetInterruptMode (ADI_SPI_DEV_HANDLE const hDevice)
Get SPI IRQ mode.
bool_t adi_SPI_GetLoopback (ADI_SPI_DEV_HANDLE const hDevice)
Get the SPI loopback control bit.
bool_t adi_SPI_GetLsbFirst (ADI_SPI_DEV_HANDLE const hDevice)
Get SPI LSB or MSB first transfer mode.
bool_t adi_SPI_GetMasterMode (ADI_SPI_DEV_HANDLE const hDevice)
Get SPI Master-Mode operation.
bool_t adi_SPI_GetMisoOutput (ADI_SPI_DEV_HANDLE const hDevice)
Get SPI Slave-Mode MISO output enable.
bool_t adi_SPI_GetReceiveOverflow (ADI_SPI_DEV_HANDLE const hDevice)
Get the SPI receive FIFO overflow mode.
bool_t adi_SPI_GetTransferInitiateMode (ADI_SPI_DEV_HANDLE const hDevice)
Get SPI transfer initiate and interrupt mode.
bool_t adi_SPI_GetTransmitUnderflow (ADI_SPI_DEV_HANDLE const hDevice)
Get the SPI transmit FIFO underflow mode.
bool_t adi_SPI_GetWiredOrMode (ADI_SPI_DEV_HANDLE const hDevice)
Get the SPI "Wired-OR" output mode.
bool_t adi_SPI_MasterComplete (ADI_SPI_DEV_HANDLE const hDevice)
Get the SPI transaction completion status.
ADI_SPI_RESULT_TYPE adi_SPI_MasterInit (ADI_SPI_DEV_ID_TYPE const devID, ADI_SPI_DEV_HANDLE *const phDevice)
Initialize and allocate an SPI device for use in Master Mode.
ADI_SPI_RESULT_TYPE adi_SPI_MasterTransfer (ADI_SPI_DEV_HANDLE const hDevice, ADI_SPI_TRANSCEIVE_TYPE *const pXfr)
Submit data buffers for SPI Master-Mode transaction.
ADI_SPI_RESULT_TYPE adi_SPI_RegisterCallback (ADI_SPI_DEV_HANDLE const hDevice, ADI_CALLBACK const pfCallback, void *const pCBParam)
Register or unregister the callback.
ADI_SPI_RESULT_TYPE adi_SPI_SetBitrate (ADI_SPI_DEV_HANDLE const hDevice, const uint32_t Hertz)
Set the SPI serial clock frequency.
ADI_SPI_RESULT_TYPE adi_SPI_SetBlockingMode (ADI_SPI_DEV_HANDLE const hDevice, const bool_t bFlag)
Set the blocking mode.
ADI_SPI_RESULT_TYPE adi_SPI_SetChipSelect (ADI_SPI_DEV_HANDLE const hDevice, const ADI_GPIO_PORT_TYPE Port, const ADI_GPIO_DATA_TYPE Pin)
Designate the chip select port and pin.
ADI_SPI_RESULT_TYPE adi_SPI_SetClockPhase (ADI_SPI_DEV_HANDLE const hDevice, const bool_t bFlag)
Set the clock phase.
ADI_SPI_RESULT_TYPE adi_SPI_SetClockPolarity (ADI_SPI_DEV_HANDLE const hDevice, const bool_t bFlag)
Set the clock polarity.
ADI_SPI_RESULT_TYPE adi_SPI_SetContinousMode (ADI_SPI_DEV_HANDLE const hDevice, const bool_t bFlag)
Set the continuous transfer mode.
ADI_SPI_RESULT_TYPE adi_SPI_SetDmaMode (ADI_SPI_DEV_HANDLE const hDevice, const bool_t bFlag)
Set the DMA mode.
ADI_SPI_RESULT_TYPE adi_SPI_SetFifoRxFlush (ADI_SPI_DEV_HANDLE const hDevice, const bool_t bFlag)
Set the SPI receive FIFO flush mode.
ADI_SPI_RESULT_TYPE adi_SPI_SetFifoTxFlush (ADI_SPI_DEV_HANDLE const hDevice, const bool_t bFlag)
Set the SPI transmit FIFO flush mode.
ADI_SPI_RESULT_TYPE adi_SPI_SetGenericSettings (ADI_SPI_DEV_HANDLE const hDevice, ADI_SPI_DEV_GENERIC_SETTINGS_TYPE *const pSettings)
Set generic SPI settings.
ADI_SPI_RESULT_TYPE adi_SPI_SetHWChipSelect (ADI_SPI_DEV_HANDLE const hDevice, const bool_t bFlag)
Turn HW Chip Select on or off.
ADI_SPI_RESULT_TYPE adi_SPI_SetInterruptMode (ADI_SPI_DEV_HANDLE const hDevice, const ADI_SPI_IRQ_MODE_TYPE Mode)
Set SPI IRQ mode.
ADI_SPI_RESULT_TYPE adi_SPI_SetLoopback (ADI_SPI_DEV_HANDLE const hDevice, const bool_t bFlag)
Set the internal loopback mode.
ADI_SPI_RESULT_TYPE adi_SPI_SetLsbFirst (ADI_SPI_DEV_HANDLE const hDevice, const bool_t bFlag)
Set SPI LSB or MSB first transfer mode.
ADI_SPI_RESULT_TYPE adi_SPI_SetMasterMode (ADI_SPI_DEV_HANDLE const hDevice, const bool_t bFlag)
Set SPI Master-Mode operation.
ADI_SPI_RESULT_TYPE adi_SPI_SetMisoOutput (ADI_SPI_DEV_HANDLE const hDevice, const bool_t bFlag)
Set SPI Slave-Mode MISO output enable.
ADI_SPI_RESULT_TYPE adi_SPI_SetReceiveOverflow (ADI_SPI_DEV_HANDLE const hDevice, const bool_t bFlag)
Set the SPI receive FIFO overflow mode.
ADI_SPI_RESULT_TYPE adi_SPI_SetTransferInitiateMode (ADI_SPI_DEV_HANDLE const hDevice, const bool_t bFlag)
Set SPI transfer initiate and interrupt mode.
ADI_SPI_RESULT_TYPE adi_SPI_SetTransmitUnderflow (ADI_SPI_DEV_HANDLE const hDevice, const bool_t bFlag)
Set the SPI transmit FIFO underflow mode.
ADI_SPI_RESULT_TYPE adi_SPI_SetWiredOrMode (ADI_SPI_DEV_HANDLE const hDevice, const bool_t bFlag)
Set the SPI "Wired-OR" output mode.
bool_t adi_SPI_SlaveComplete (ADI_SPI_DEV_HANDLE const hDevice)
Get the SPI slave transaction completion status.
ADI_SPI_RESULT_TYPE adi_SPI_SlaveInit (ADI_SPI_DEV_ID_TYPE const devID, ADI_SPI_DEV_HANDLE *const phDevice)
Initialize and allocate an SPI device for use in Slave Mode.
ADI_SPI_RESULT_TYPE adi_SPI_SlaveTransfer (ADI_SPI_DEV_HANDLE const hDevice, ADI_SPI_TRANSCEIVE_TYPE *const pXfr)
Submit data buffers for SPI Slave-Mode transaction.
ADI_SPI_RESULT_TYPE adi_SPI_UnInit (ADI_SPI_DEV_HANDLE const hDevice)
Uninitialize and deallocate an SPI device.
Detailed Description
Macro Definition Documentation
#define ADI_SPI_BITRATE_INITIALIZER 250000 /* depends on processor */
SPI Bitrate Initializer. Sets a default serial clockrate for the SPI channel.
Definition at line 55 of file spi.h.
#define ADI_SPI_DMA_INITIALIZER 0
SPI DMA Enable Register Initializer. Sets default DMA enablement to disabled. Use the adi_SPI_SetDmaMode() API to enable DMA-based transactions.
Definition at line 79 of file spi.h.
#define ADI_SPI_MASTERCON_INITIALIZER SPICON_MASEN | SPICON_ENABLE
SPI0/SPI1 Control Register Initializer. This macro configures default settings for the SPI configuration control register when operated in Master-mode.
Definition at line 63 of file spi.h.
#define ADI_SPI_MAX_TRANSFER_SIZE 256
Maximum SPI DMA chunk size. Note this is limited by the SPI controller's 8-bit SPICNT byte count register to 256. Previous implimentations of the SPI driver did not use the SPI count register and so were not limited to this 8-bit count. For DMA transfers that fit within a single DMA descriptor, the SPICNT register provides for stopping the SPI controller at the exact byte count, after which the DMA engine continues to drain pending bytes still in the receive FIFO. For larger transfers that span multiple DMA descriptors, the singular SPICNT is not used and so extra "garbage" bytes will be clocked after the end of the real transfer while the DMA engine drains the receive FIFO, but the extra bytes will be ignored and not appear in the user's receive buffer.
Definition at line 48 of file spi.h.
Referenced by adi_SPI_MasterTransfer(), and adi_SPI_SlaveTransfer().
#define ADI_SPI_SLAVECON_INITIALIZER
Value:
SPICON_OEN           \
                                     | SPICON_ZEN           \
                                     | SPICON_ENABLE
SPI0/SPI1 Control Register Initializer. This macro configures default settings for the SPI configuration control register when operated in Slave-mode.
Definition at line 70 of file spi.h.
#define REVERT_ADI_MISRA_SUPPRESSIONS
Revert ADI MISRA Suppressions
Definition at line 3494 of file spi.c.
Typedef Documentation
typedef struct ADI_SPI_DEV_DATA_TYPE* ADI_SPI_DEV_HANDLE
SPI Device instance private data handle typedef.
Definition at line 210 of file spi.h.
Enumeration Type Documentation
enum ADI_SPI_DEV_ID_TYPE
SPI device IDs. Depending on device configuration there may be one or more physical controllers. In the case of SPI, there are two. Use the ADI_SPI_DEV_ID_TYPE enumerator to select which device is being initialized by function adi_SPI_Init() or adi_SPI_SlaveInit().
Enumerator
ADI_SPI_DEVID_0
SPI0 device ID.
ADI_SPI_DEVID_1
SPI1 device ID.
ADI_SPI_DEVID_H
SPIH device ID.
Definition at line 92 of file spi.h.
enum ADI_SPI_EVENT
Enumeration of events notified in the application provided callback.
Enumerator
ADI_SPI_EVENT_BUFFER_PROCESSED
The given buffer is processed. Application can use this event to submit the next buffer to be transmitted.
Definition at line 137 of file spi.h.
enum ADI_SPI_IRQ_MODE_TYPE
SPI driver interrupt mode. Allows designation through the adi_SPI_SetInterruptMode() API of when the SPI controller generates interrupts, based on the number of transmit and receive bytes transacted. This is helpful in managing the rate of interrupts vs. the the data FIFO "fullness", the idea being to minimize the number of interrupts while not allowing either FIFO to overflow or underflow. Only the 4 combinations listed are supported by the hardware.
Enumerator
ADI_SPI_IRQMODE_T1R1
Interrupt every 1-byte tx, 1-byte rx.
ADI_SPI_IRQMODE_T2R2
Interrupt every 2-byte tx, 2-byte rx.
ADI_SPI_IRQMODE_T3R3
Interrupt every 3-byte tx, 3-byte rx.
ADI_SPI_IRQMODE_T4R4
Interrupt every 4-byte tx, 4-byte rx.
Definition at line 176 of file spi.h.
enum ADI_SPI_RESULT_TYPE
SPI Device Error Codes. ADI_SPI_SUCCESS is always zero and all other SPI error codes are offset by the base SPI error code offset, ADI_DEV_SPI_ERROR_OFFSET. A number of SPI error codes are debug-only, as controlled by the "ADI_DEBUG" build macro.
The return value of all SPI APIs returning ADI_SPI_RESULT_TYPE should always be tested at the application level for success or failure.
Enumerator
ADI_SPI_SUCCESS
Generic success.
ADI_SPI_ERR_UNKNOWN
Generic error.
ADI_SPI_ERR_ALREADY_INITIALIZED
SPI device is already initialized.
ADI_SPI_ERR_BAD_DEV_HANDLE
Invalid device handle.
ADI_SPI_ERR_BAD_DEV_ID
Invalid device ID.
ADI_SPI_ERR_BAD_DMA_CONFIG
DMA configuration failure.
ADI_SPI_ERR_BAD_GPIO_CONFIG
SPI failed to configure GPIO.
ADI_SPI_ERR_DMA_ALREADY_IN_USE
DMA is already in progress.
ADI_SPI_ERR_NO_DMA_FOR_DEVICE
DMA is not defined for this device.
ADI_SPI_ERR_NOT_INITIALIZED
SPI device is uninitialized.
ADI_SPI_ERR_NULL_DATA_POINTER
NULL data pointer not allowed.
ADI_SPI_ERR_PARAM_OUT_OF_RANGE
Parameter is out of range.
ADI_SPI_ERR_UNSUPPORTED_MODE
Unsupported mode of operation.
ADI_SPI_ERR_SEMAPHORE_FAILED
Semaphore in error .
Definition at line 113 of file spi.h.
enum ADI_SPI_STATE_TYPE
SPI driver state. Used for internal tracking of the SPI device initialization progress during the adi_SPI_Init() and adi_SPI_SlaveInit() functions. Also used to insure the SPI device has been properly initialized as a prerequisite to using the balance of the SPI API.
Enumerator
ADI_SPI_STATE_UNINITIALIZED
SPI is not initialized.
ADI_SPI_STATE_INITIALIZING
SPI initialization is in progress.
ADI_SPI_STATE_MASTER
SPI initialization is complete.
ADI_SPI_STATE_SLAVE
SPI initialization is complete.
Definition at line 155 of file spi.h.
Function Documentation
ADI_INT_HANDLER (SPI0_Int_Handler)
SPI0 Interrupt Handler.
Returns
void.
Overrides default SPI0 interrupt handler.
Definition at line 2976 of file spi.c.
ADI_INT_HANDLER (SPI1_Int_Handler)
SPI1 Interrupt Handler.
Returns
void.
Overrides default SPI1 interrupt handler.
Definition at line 2988 of file spi.c.
ADI_INT_HANDLER (SPIH_Int_Handler)
SPIH Interrupt Handler.
Returns
void.
Overrides default SPIH interrupt handler.
Definition at line 3000 of file spi.c.
ADI_INT_HANDLER (DMA_SPI0_TX_Int_Handler)
SPI0 DMA Transmit Interrupt Handler.
Returns
void.
Overrides default SPI0 DMA transmit interrupt handler.
Definition at line 3429 of file spi.c.
ADI_INT_HANDLER (DMA_SPI0_RX_Int_Handler)
SPI0 DMA Receive Interrupt Handler.
Returns
void.
Overrides default SPI0 DMA receive interrupt handler.
Definition at line 3441 of file spi.c.
ADI_INT_HANDLER (DMA_SPI1_TX_Int_Handler)
SPI1 DMA Transmit Interrupt Handler.
Returns
void.
Overrides default SPI1 DMA transmit interrupt handler.
Definition at line 3453 of file spi.c.
ADI_INT_HANDLER (DMA_SPI1_RX_Int_Handler)
SPI1 DMA Receive Interrupt Handler.
Returns
void.
Overrides default SPI1 DMA receive interrupt handler.
Definition at line 3465 of file spi.c.
ADI_INT_HANDLER (DMA_SPIH_TX_Int_Handler)
SPIH DMA Transmit Interrupt Handler.
Returns
void.
Overrides default SPIH DMA transmit interrupt handler.
Definition at line 3477 of file spi.c.
ADI_INT_HANDLER (DMA_SPIH_RX_Int_Handler)
SPIH DMA Receive Interrupt Handler.
Returns
void.
Overrides default SPIH DMA receive interrupt handler.
Definition at line 3489 of file spi.c.
uint32_t adi_SPI_GetBitrate (ADI_SPI_DEV_HANDLE const hDevice)
Get the SPI serial clock frequency.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
Returns
Returns the exact serial clock frequence (in Hertz).
Get the current serial clock frequency. The returned value is exact but may not exactly match the value set with adi_SPI_SetBitrate() due to computational round-off errors resulting from fixed register size and finite-precision arithmetic.
See Also
adi_SPI_SetBitrate().
Definition at line 1707 of file spi.c.
Referenced by adi_SPI_GetGenericSettings().
bool_t adi_SPI_GetBlockingMode (ADI_SPI_DEV_HANDLE const hDevice)
Get the blocking mode.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
Returns
Returns the current blocking mode.
true Using blocking-mode.
false Using non-blocking-mode.
Get the current state of the SPI blocking mode.
See Also
adi_SPI_SetBlockingMode().
Definition at line 1871 of file spi.c.
Referenced by adi_SPI_GetGenericSettings().
ADI_SPI_CHIP_SELECT_TYPE adi_SPI_GetChipSelect (ADI_SPI_DEV_HANDLE const hDevice)
Get the currently designated chip select.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
Returns
Returns a struct value representing the chip select line currently configured.
Get the current state of the SPI chip select port and pin designation.
See Also
adi_SPI_SetChipSelect().
Definition at line 1813 of file spi.c.
Referenced by adi_SPI_GetGenericSettings().
bool_t adi_SPI_GetClockPhase (ADI_SPI_DEV_HANDLE const hDevice)
Get the clock phase.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
Returns
Returns the current state of the SPI clock phase.
true Sample data on trailing-edge of each serial bit.
false Sample data on leading-edge of each serial bit.
Get the current state of the SPI clock phase control bit.
See Also
adi_SPI_GetClockPolarity().
adi_SPI_SetClockPhase().
adi_SPI_SetClockPolarity().
Definition at line 1576 of file spi.c.
bool_t adi_SPI_GetClockPolarity (ADI_SPI_DEV_HANDLE const hDevice)
Get the clock polarity.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
Returns
Returns the current state of the SPI clock polarity control.
true Clock is idled high.
false Clock is idled low.
Get the current state of the SPI clock polarity.
See Also
adi_SPI_GetClockPhase().
adi_SPI_SetClockPhase().
adi_SPI_SetClockPolarity().
Definition at line 1502 of file spi.c.
bool_t adi_SPI_GetContinousMode (ADI_SPI_DEV_HANDLE const hDevice)
Get the continuous transfer mode.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
Returns
Returns the current state of the continuous transfer mode.
true Continuous transfer mode is set.
false Continuous transfer mode is cleared.
Get the current state of the continuous data transfer mode.
See Also
adi_SPI_SetContinousMode().
Definition at line 1012 of file spi.c.
bool_t adi_SPI_GetDmaMode (ADI_SPI_DEV_HANDLE const hDevice)
Get the DMA mode.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
Returns
Returns the current state of the DMA usage mode.
true DMA mode is enabled.
false DMA mode is disabled.
Get the current state of the SPI DMA mode.
See Also
adi_SPI_GetBlockingMode().
adi_SPI_GetDmaRxComplete().
adi_SPI_GetDmaTxComplete().
adi_SPI_SetBlockingMode().
adi_SPI_SetDmaMode().
Definition at line 1964 of file spi.c.
Referenced by adi_SPI_GetGenericSettings().
bool_t adi_SPI_GetDmaRxComplete (ADI_SPI_DEV_HANDLE const hDevice)
Get receive DMA completion status.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
Returns
Returns the current completion state of a DMA receive transaction.
true DMA receive sequence is complete.
false DMA receive sequence is incomplete.
Get the current state of the SPI DMA receive completion. Used at the application level to poll for completion of a previously submitted receive request as a non-blocking DMA transfer. The application may call adi_SPI_GetDmaTxComplete(), adi_SPI_GetDmaRxComplete(), or both, as necessary.
See Also
adi_SPI_GetBlockingMode().
adi_SPI_GetDmaMode().
adi_SPI_GetDmaTxComplete().
adi_SPI_SetBlockingMode().
adi_SPI_SetDmaMode().
Definition at line 2014 of file spi.c.
Referenced by adi_SPI_MasterTransfer().
bool_t adi_SPI_GetDmaTxComplete (ADI_SPI_DEV_HANDLE const hDevice)
Get transmit DMA completion status.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
Returns
Returns the current completion state of the DMA transmit transaction.
true DMA transmit sequence is complete.
false DMA transmit sequence is incomplete.
Get the current state of the SPI DMA transmit completion. Used at the application level to poll for completion of a previously submitted transmit request as a non-blocking DMA transfer. The application may call adi_SPI_GetDmaTxComplete(), adi_SPI_GetDmaRxComplete(), or both, as necessary.
See Also
adi_SPI_GetBlockingMode().
adi_SPI_GetDmaMode().
adi_SPI_GetDmaRxComplete().
adi_SPI_SetBlockingMode().
adi_SPI_SetDmaMode().
Definition at line 1989 of file spi.c.
Referenced by adi_SPI_MasterTransfer().
bool_t adi_SPI_GetFifoRxFlush (ADI_SPI_DEV_HANDLE const hDevice)
Get the SPI receive FIFO flush mode.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
Returns
Returns the current state of the recieve FIFO flush control bit.
true Receive FIFO flush mode is set.
false Receive FIFO flush mode is cleared.
See Also
adi_SPI_GetFifoTxFlush().
adi_SPI_SetFifoRxFlush().
adi_SPI_SetFifoTxFlush().
Definition at line 948 of file spi.c.
bool_t adi_SPI_GetFifoTxFlush (ADI_SPI_DEV_HANDLE const hDevice)
Get the SPI transmit FIFO flush mode.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
Returns
Returns the current state of the transmit FIFO flush mode.
true Transmit FIFO flush mode is set.
false Transmit FIFO flush mode is cleared.
See Also
adi_SPI_GetFifoRxFlush().
adi_SPI_SetFifoRxFlush().
adi_SPI_SetFifoTxFlush().
Definition at line 884 of file spi.c.
ADI_SPI_RESULT_TYPE adi_SPI_GetGenericSettings (ADI_SPI_DEV_HANDLE const hDevice, ADI_SPI_DEV_GENERIC_SETTINGS_TYPE *const pSettings)
Get generic SPI settings.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
[out] pSettings Pointer to caller-allocated generic device settings structure.
Returns
Status
ADI_SPI_ERR_BAD_DEV_HANDLE [D] Invalid device handle parameter.
ADI_SPI_ERR_NOT_INITIALIZED [D] Device has not been previously configured for use.
ADI_SPI_ERR_PARAM_OUT_OF_RANGE [D] Invalid or NULL pSettings parameter.
ADI_SPI_SUCCESS Call completed successfully.
Retrieves various generic device settings and modes in a single call. Contents of caller's pSettings structure are written on success.
See Also
adi_SPI_GetGenericSettings().
Definition at line 693 of file spi.c.
ADI_SPI_IRQ_MODE_TYPE adi_SPI_GetInterruptMode (ADI_SPI_DEV_HANDLE const hDevice)
Get SPI IRQ mode.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
Retrieves the SPI FIFOs interrupt generation mode, based on their relative "fullness".
Returns
Returns the current setting for SPI FIFO interrupt mode, based on their relative "fullness".
See Also
adi_SPI_SetInterruptMode().
Definition at line 798 of file spi.c.
bool_t adi_SPI_GetLoopback (ADI_SPI_DEV_HANDLE const hDevice)
Get the SPI loopback control bit.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
Returns
Returns the current state of the internal SPI loopback mode.
true Internal loopback mode is set.
false Internal loopback mode is cleared.
Get the current state of the internal SPI loopback control bit.
See Also
adi_SPI_SetLoopback().
Definition at line 1069 of file spi.c.
bool_t adi_SPI_GetLsbFirst (ADI_SPI_DEV_HANDLE const hDevice)
Get SPI LSB or MSB first transfer mode.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
Returns
Returns the current state of the SPI MSB/LSB transfer mode.
true If transferring MSB first.
false If transferring LSB first.
Returns whether the SPI controller is currently configured to transmit LSB or MSB first.
See Also
adi_SPI_SetLsbFirst().
Definition at line 1369 of file spi.c.
bool_t adi_SPI_GetMasterMode (ADI_SPI_DEV_HANDLE const hDevice)
Get SPI Master-Mode operation.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
Returns
Returns the current state of SPI Master-Mode setting.
true Master-Mode is currently selected.
false Slave-Mode is currently selected.
Get the current state of the SPI Master Mode control bit.
See Also
adi_SPI_SetMasterMode().
Definition at line 1633 of file spi.c.
bool_t adi_SPI_GetMisoOutput (ADI_SPI_DEV_HANDLE const hDevice)
Get SPI Slave-Mode MISO output enable.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
Returns
Returns the current state of the Slave-Mode MISO output enable.
true MISO output driver is enabled.
false MISO output driver is disabled.
Get the current state of the slave-mode MISO pin output driver enable.
See Also
adi_SPI_SetMisoOutput().
Definition at line 1130 of file spi.c.
bool_t adi_SPI_GetReceiveOverflow (ADI_SPI_DEV_HANDLE const hDevice)
Get the SPI receive FIFO overflow mode.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
Returns
Returns the current state of the receive FIFO overflow mode.
true If discarding old data on receive FIFO overfolw.
false If discarding new data on receive FIFO overfolw.
Get the current state of the SPI receive FIFO overflow mode.
See Also
adi_SPI_SetReceiveOverflow().
Definition at line 1191 of file spi.c.
bool_t adi_SPI_GetTransferInitiateMode (ADI_SPI_DEV_HANDLE const hDevice)
Get SPI transfer initiate and interrupt mode.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
Returns
Returns the current state of the SPI transfer initiate and interrupt mode.
true If initiating transfers on write to transmit FIFO and interrupt when empty.
false If initiating transfers on read from receive FIFO and interrupt when full.
Get the current state of the SPI transfer initiate mode control bit, describing when transfers are initiated and when interrupts are generated.
See Also
adi_SPI_SetTransferInitiateMode().
Definition at line 1312 of file spi.c.
bool_t adi_SPI_GetTransmitUnderflow (ADI_SPI_DEV_HANDLE const hDevice)
Get the SPI transmit FIFO underflow mode.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
Returns
Returns the current state of the Slave-Mode MISO output enable.
true If sending zeroes on transmit FIFO underflow.
false If resending last data on transmit FIFO underflow.
Get the current state of the SPI transmit FIFO underflow mode, describing what data is transmitted if the transmit FIFO underflows.
See Also
adi_SPI_SetTransmitUnderflow().
Definition at line 1251 of file spi.c.
bool_t adi_SPI_GetWiredOrMode (ADI_SPI_DEV_HANDLE const hDevice)
Get the SPI "Wired-OR" output mode.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
Returns
Returns the current state of the SPI "wired-or" output mode.
true If "Wired-OR" (open-collector) output mode is enabled.
false If "Wired-OR" (fully-driven) output mode is disabled.
Get the current state of the SPI "Wired-OR" output mode.
See Also
adi_SPI_SetWiredOrMode().
Definition at line 1428 of file spi.c.
bool_t adi_SPI_MasterComplete (ADI_SPI_DEV_HANDLE const hDevice)
Get the SPI transaction completion status.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
Returns
Returns the current state of a previously submitted non-blocking transaction.
true Transaction is complete.
false Transaction is incomplete.
See Also
adi_SPI_MasterTransfer().
Definition at line 2341 of file spi.c.
Referenced by adi_SPI_MasterTransfer().
ADI_SPI_RESULT_TYPE adi_SPI_MasterInit (ADI_SPI_DEV_ID_TYPE const devID, ADI_SPI_DEV_HANDLE *const phDevice)
Initialize and allocate an SPI device for use in Master Mode.
Parameters
[in] devID Zero-based device index designating which device to initialize.
[out] phDevice The caller's device handle pointer for storing the initialized device instance data pointer.
Returns
Status
ADI_SPI_ERR_ALREADY_INITIALIZED [D] Specified device has already been initialized.
ADI_SPI_ERR_BAD_DEV_ID [D] Invalid device index.
ADI_SPI_ERR_BAD_DMA_CONFIG Internal DMA initializations failed.
ADI_SPI_ERR_BAD_GPIO_CONFIG Internal GPIO initializations failed.
ADI_SPI_ERR_SEMAPHORE_FAILED Semaphore creation failed.
ADI_SPI_SUCCESS Call completed successfully.
No other SPI APIs may be called until the device init function is called.
Initialize an SPI device using internal default configuration settings and allocate the device for use. The caller's device handle is written with the device instance data pointer. The returned device handle is required to be passed to all subsequent calls to convey which device instance to operate on.
Note
The contents of phDevice will be set to NULL upon failure.
See Also
adi_SPI_SlaveInit().
adi_SPI_UnInit().
Definition at line 374 of file spi.c.
ADI_SPI_RESULT_TYPE adi_SPI_MasterTransfer (ADI_SPI_DEV_HANDLE const hDevice, ADI_SPI_TRANSCEIVE_TYPE *const pXfr)
Submit data buffers for SPI Master-Mode transaction.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
[in] pXfr Pointer to transfer data struct.
Returns
Status
ADI_SPI_ERR_BAD_DEV_HANDLE [D] Invalid device handle parameter.
ADI_SPI_ERR_DMA_ALREADY_IN_USE [D] DMA transaction already underway.
ADI_SPI_ERR_NOT_INITIALIZED [D] Device has not been previously configured for use.
ADI_SPI_ERR_NULL_DATA_POINTER [D] Invalid data pointer detected (NULL).
ADI_SPI_ERR_PARAM_OUT_OF_RANGE [D] Invalid size parameter detected (0).
ADI_SPI_SUCCESS Call completed successfully.
Request a synchronous transmit and receive of multiple data bytes over the SPI serial channel. Honors current blocking and DMA modes. Buffer allocations are made by the calling code (the application).
There are three PROGRAMMING MODELS for using this API. The simplest is blocking mode, in which the API blocks internally until the transaction is complete. In blocking mode, there is no opportunity for the application to do background processing, so there will be wasted horsepower especially in the DMA case (where the core has minimal work to do). The other two cases are non-blocking-with-polling and non-blocking-with-callback. In both cases of the non-blocking mode, the application has the opportunity to perform background processing, but it may never submit additional SPI transactions until the current one is complete. In non-blocking-with-polling mode, the application needs to poll the SPI driver for completion. In non-blocking-with-callback mode, the application need not concern itself with the progress of the current SPI transaction and will know the transaction is complete when it receives the callback.
The transmit buffer is sent and the receive buffer is written according to the size and increment information contained by the pXft transfer data structure parameter.
The ADI_SPI_TRANSCEIVE_TYPE contains all the parameters describing the transfer. There are three main parts to it: a prologue, the transmit data and the receive data. Each part has a size attribute, and each data pointer has an increment flag. Setting the increment flag to false allows a data pointer to remain stationary (see bTxIncrement and bRxIncrement, below).
The prologue is a special block that can contain optional command or protocol information unique to the external SPI device or command protocol. The prologue can be zero-sized if not needed.
Each call to adi_SPI_MasterTransfer() must populate the following fields of the ADI_SPI_TRANSCEIVE_TYPE block:
pPrologue
The pPrologue pointer points to an application-defined prologue block that is transmitted before the data. The prologue block is a data chunk of command or protocol-related information unique to the external device the SPI controller is communicating with. It can be used to tell the external device how to process the coming data or to perform some special task. The prologue block is an optional element and may not be needed. If not needed, the PrologueSize parameter should be set to zero to prevent prologue transactions from taking up bandwidth or confusing an external device that is not expecting a prologue.
DataSize
The number of data bytes to transfer. DMA mode requires evenly-sized byte counts and buffer allocations due to the underlying SPI hardware that employs 16-bit DMA. PIO mode transactions are limited to 64KB transactions. All data buffer allocations are made by the application and passed by pointer. The size of the application-allocated transmit and receive data buffers are the same unless one of the increment flags is disabled resulting in a stationary data pointer. If using a stationary data pointer, e.g., a FIFO address, the associated data buffer allocation may be of size one (unless using DMA mode, see above). Blocking-mode calls cause the driver to block on this API until the transaction is complete. Non-blocking calls return right away and require the application to poll on the transfer completion status or register/receive a callback, such that the application may perform other tasks. The application may never submit multiple transactions and must always insure each transaction is complete before submitting any other transactions.
pTxData
Pointer to the application-defined transmit data buffer. This is the data sent out over the SPI transmit wire (MOSI for Master-mode, MISO for Slave-mode) during the SPI transaction. For ADuCM350 SPI DMA mode (which is 16-bit based), the transmit buffer must be 16-bit aligned.
pRxData
Pointer to the application-defined receive data buffer. This is where the receive data will be stored from the SPI receive wire (MISO for Master-mode, MOSI for Slave-mode) during the SPI transaction. For ADuCM350 SPI DMA mode (which is 16-bit based), the receive buffer must be 16-bit aligned.
PrologueSize
The size (in bytes) of the prologue block, pPrologue. The prologue data is sent out ahead of the data. The prologue size may be set to zero to disable transmission of prologue data.
bTxIncrement
Increment flag for the transmit buffer. If true, the transmit data buffer pointer is advanced as each byte is sent. If false, the transmit data pointer is stationary. A stationary buffer pointer is useful for sending the same data to an external device or if the source data is from a fixed memory address.
bRxIncrement
Increment flag for the receive buffer. If true, the receive data buffer pointer is advanced as each byte is received. If false, the receive data pointer is stationary. A stationary buffer pointer is useful for monitoring commands from an external device or if the receive data is going to a fixed memory address.
See Also
adi_SPI_GetBlockingMode().
adi_SPI_GetDmaMode().
adi_SPI_GetDmaRxComplete().
adi_SPI_GetDmaTxComplete().
adi_SPI_SetBlockingMode().
adi_SPI_SetDmaMode().
adi_SPI_MasterComplete().
Definition at line 2126 of file spi.c.
ADI_SPI_RESULT_TYPE adi_SPI_RegisterCallback (ADI_SPI_DEV_HANDLE const hDevice, ADI_CALLBACK const pfCallback, void *const pCBParam)
Register or unregister the callback.
Parameters
[in] hDevice Device handle obtained from adi_SPI_Master/SlaveInit().
[in] pfCallback Pointer to the callback function. Can be passed as NULL to unregister the previously registered callback.
[in] pCBParam Callback parameter which will be passed back to the application when the callback is called.
Returns
Status
ADI_SPI_ERR_BAD_DEV_HANDLE [D] Invalid device handle parameter.
ADI_SPI_ERR_NOT_INITIALIZED [D] Device has not been previously configured for use.
ADI_SPI_SUCCESS Call completed successfully.
Definition at line 614 of file spi.c.
ADI_SPI_RESULT_TYPE adi_SPI_SetBitrate (ADI_SPI_DEV_HANDLE const hDevice, const uint32_t Hertz)
Set the SPI serial clock frequency.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
[in] Hertz Target frequency (in Hz) for SPI bitrate.
Returns
Status
ADI_SPI_ERR_BAD_DEV_HANDLE [D] Invalid device handle parameter.
ADI_SPI_ERR_NOT_INITIALIZED [D] Device has not been previously configured for use.
ADI_SPI_ERR_PARAM_OUT_OF_RANGE Specified frequence out of range.
ADI_SPI_SUCCESS Call completed successfully.
Compute and set the internal SPI clock rate divider register to produce the desired serial clock frequency. Resulting frequency is subject to arithmetic rounding errors. Use adi_SPI_GetBitrate() to obtain the exact frequency produced, including rounding errors.
See Also
adi_SPI_GetBitrate().
Definition at line 1657 of file spi.c.
Referenced by adi_SPI_SetGenericSettings().
ADI_SPI_RESULT_TYPE adi_SPI_SetBlockingMode (ADI_SPI_DEV_HANDLE const hDevice, const bool_t bFlag)
Set the blocking mode.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
[in] bFlag Flag to select between blocking-mode and non-blocking-mode transfers.
true Use blocking-mode.
false Use non-blocking-mode.
Returns
Status
ADI_SPI_ERR_BAD_DEV_HANDLE [D] Invalid device handle parameter.
ADI_SPI_ERR_NOT_INITIALIZED [D] Device has not been previously configured for use.
ADI_SPI_SUCCESS Call completed successfully.
Sets the blocking mode for data transfers. Transfers made in blocking-mode will not return until complete. Transfers made in non-blocking-mode may return before the transfer is complete and will require application level polling calls to determin when and how much of non-blocking transactions are complete. See adi_SPI_MasterTransfer() API for making non-blocking polling calls.
See Also
adi_SPI_MasterTransfer().
adi_SPI_GetBlockingMode().
Definition at line 1841 of file spi.c.
ADI_SPI_RESULT_TYPE adi_SPI_SetChipSelect (ADI_SPI_DEV_HANDLE const hDevice, const ADI_GPIO_PORT_TYPE Port, const ADI_GPIO_DATA_TYPE Pin)
Designate the chip select port and pin.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
[in] Port The GPIO port used for chip select (e.g. ADI_GPIO_PORT_3).
[in] Pin The GPIO pin used for chip select (e.g. ADI_GPIO_PIN_3).
Returns
Status
ADI_SPI_ERR_BAD_DEV_HANDLE [D] Invalid device handle parameter.
ADI_SPI_ERR_NOT_INITIALIZED [D] Device has not been previously configured for use.
ADI_SPI_ERR_BAD_GPIO_CONFIG GPIO problem reconfiguring CS.
ADI_SPI_SUCCESS Call completed successfully.
Designates the desired chip select to use for activating an external slave device. Does not assert the designated chip select, which is done by the driver automatically with data transactions.
Note
Any available GPIO port and pin combination may be used as chip select, not just the default pins associated with the SPI controller. This is bacause the SPI driver does not use the hardware chip select on the controller; it uses a software (GPIO-based) CS methodology.
See Also
adi_SPI_GetChipSelect().
Definition at line 1775 of file spi.c.
ADI_SPI_RESULT_TYPE adi_SPI_SetClockPhase (ADI_SPI_DEV_HANDLE const hDevice, const bool_t bFlag)
Set the clock phase.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
[in] bFlag Flag to manage the phase of the serial data clock.
true Sample data on trailing-edge of each serial bit.
false Sample data on leading-edge of each serial bit.
Returns
Status
ADI_SPI_ERR_BAD_DEV_HANDLE [D] Invalid device handle parameter.
ADI_SPI_ERR_NOT_INITIALIZED [D] Device has not been previously configured for use.
ADI_SPI_SUCCESS Call completed successfully.
Sets the SPI clock polarity phase bit (CPHA). Used in conjunction with clock polarity (CPOL) to program the exact timing of serial data capture and transmit. Both clock phase and polarity must be considered in selecting the data transfer mode best suited to the Master/Slave device pair, typically dependant on the manufacturer and timing requirements of the external SPI device.
Both Master and Slave devices must use the same settings for clock phase and polarity.
If the phase of the clock is zero (CPHA=0), receive data are latched on the rising-clock-edge with CPOL=0 (idle-low) polarity, and on the falling-clock-edge with CPOL=1 (idle high) ploarity.
If CPHA=1, the effective clock edges are reversed; CPOL=0 latches receive data on the falling-clock-edge and CPOL=1 latches receive data on the rising-clock-edge.
Data are transmitted on the opposite clock edge as the receive, i.e., receive and transmit are out of phase.
See Also
adi_SPI_GetClockPhase().
adi_SPI_GetClockPolarity().
adi_SPI_SetClockPolarity().
Definition at line 1540 of file spi.c.
ADI_SPI_RESULT_TYPE adi_SPI_SetClockPolarity (ADI_SPI_DEV_HANDLE const hDevice, const bool_t bFlag)
Set the clock polarity.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
[in] bFlag Flag to manage the idle state of the serial data clock between samples.
true Clock is idled high.
false Clock is idled low.
Returns
Status
ADI_SPI_ERR_BAD_DEV_HANDLE [D] Invalid device handle parameter.
ADI_SPI_ERR_NOT_INITIALIZED [D] Device has not been previously configured for use.
ADI_SPI_SUCCESS Call completed successfully.
Sets the SPI clock polarity control bit (CPOL). Used in conjunction with clock phase (CPHA) to program the exact timing of serial data capture and transmit. Both clock phase and polarity must be considered in selecting the data transfer mode best suited to the Master/Slave device pair, typically dependant on the manufacturer and timing requirements of the external SPI device.
Both Master and Slave devices must use the same settings for clock phase and polarity.
If the phase of the clock is zero (CPHA=0), receive data are latched on the rising-clock-edge with CPOL=0 (idle-low) polarity, and on the falling-clock-edge with CPOL=1 (idle high) ploarity.
If CPHA=1, the effective clock edges are reversed; CPOL=0 latches receive data on the falling-clock-edge and CPOL=1 latches receive data on the rising-clock-edge.
Data are transmitted on the opposite clock edge as the receive, i.e., receive and transmit are out of phase.
See Also
adi_SPI_GetClockPhase().
adi_SPI_GetClockPolarity().
adi_SPI_SetClockPhase().
Definition at line 1466 of file spi.c.
ADI_SPI_RESULT_TYPE adi_SPI_SetContinousMode (ADI_SPI_DEV_HANDLE const hDevice, const bool_t bFlag)
Set the continuous transfer mode.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
[in] bFlag Flag to manage SPI continuous transfer mode.
true Set continuous transfer mode.
false Clear continuous transfer mode.
Returns
Status
ADI_SPI_ERR_BAD_DEV_HANDLE [D] Invalid device handle parameter.
ADI_SPI_ERR_NOT_INITIALIZED [D] Device has not been previously configured for use.
ADI_SPI_SUCCESS Call completed successfully.
Setting this mode causes the SPI controller to drive the Chip Select signal continuously until the transmit FIFO is emptied. Clearing it causes Chip Select to cycle between bytes. If the transmit FIFO is allowed to become empty, Chip Select will de-assert regardless of this mode.
Note
If the transmit FIFO is allowed to empty during a send, the hardware-based (SPI controller-driven) Chip Select will de-assert which may disrupt extended transactions. For this reason, the SPI device driver explicitly manages the Chip Select pin using GPIO protocol so that the chip remains selected throughout the entire transaction... regardless of whether the transmit FIFO may momentarily empty.
See Also
adi_SPI_GetContinousMode().
Definition at line 978 of file spi.c.
ADI_SPI_RESULT_TYPE adi_SPI_SetDmaMode (ADI_SPI_DEV_HANDLE const hDevice, const bool_t bFlag)
Set the DMA mode.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
[in] bFlag Flag to manage whether to use DMA to effect SPI transfers (SPI1 only).
true Enable DMA mode.
false Disable DMA mode.
Returns
Status
ADI_SPI_ERR_BAD_DEV_HANDLE [D] Invalid device handle parameter.
ADI_SPI_ERR_NOT_INITIALIZED [D] Device has not been previously configured for use.
ADI_SPI_SUCCESS Call completed successfully.
Manages whether data transfers on SPI device will employ the DMA controller manage the transfer as a background process. When coupled with non-blocking-mode, DMA transfers require polling calls to ascertain completion of the transfer.
Note
Invalid for use on SPI device 0 (SPI0), which is dedicated to UHF communications.
See Also
adi_SPI_GetBlockingMode().
adi_SPI_GetDmaMode().
adi_SPI_GetDmaRxComplete().
adi_SPI_GetDmaTxComplete().
adi_SPI_SetBlockingMode().
Definition at line 1901 of file spi.c.
Referenced by adi_SPI_SetGenericSettings().
ADI_SPI_RESULT_TYPE adi_SPI_SetFifoRxFlush (ADI_SPI_DEV_HANDLE const hDevice, const bool_t bFlag)
Set the SPI receive FIFO flush mode.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
[in] bFlag Flag to manage FIFO receive flush mode.
true Set receive flush mode.
false Clear receive flush mode.
Returns
Status
ADI_SPI_ERR_BAD_DEV_HANDLE [D] Invalid device handle parameter.
ADI_SPI_ERR_NOT_INITIALIZED [D] Device has not been previously configured for use.
ADI_SPI_SUCCESS Call completed successfully.
Set the receive FIFO flush mode to flush the FIFO and/or keep it flushed. The receive FIFO is essentially disabled while this mode is set. Clear it for normal FIFO operation. A one-time flush is obtained by setting this mode and then clearing it.
Note
This mode is NOT self-clearing. Clear this mode to prevent continuous receive FIFO flushing.
See Also
adi_SPI_GetFifoRxFlush().
adi_SPI_GetFifoTxFlush().
adi_SPI_SetFifoTxFlush().
Definition at line 914 of file spi.c.
ADI_SPI_RESULT_TYPE adi_SPI_SetFifoTxFlush (ADI_SPI_DEV_HANDLE const hDevice, const bool_t bFlag)
Set the SPI transmit FIFO flush mode.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
[in] bFlag Flag to manage FIFO transmit flush mode.
true Set transmit flush mode.
false Clear transmit flush mode.
Returns
Status
ADI_SPI_ERR_BAD_DEV_HANDLE [D] Invalid device handle parameter.
ADI_SPI_ERR_NOT_INITIALIZED [D] Device has not been previously configured for use.
ADI_SPI_SUCCESS Call completed successfully.
Set the transmit FIFO flush mode to flush the FIFO and/or keep it flushed. The transmit FIFO is essentially disabled while this mode is set. Clear it for normal FIFO operation. A one-time flush is obtained by setting this mode and then clearing it.
Note
This mode is NOT self-clearing. Clear this mode to prevent continuous transmit FIFO flushing.
See Also
adi_SPI_GetFifoRxFlush().
adi_SPI_GetFifoTxFlush().
adi_SPI_SetFifoRxFlush().
Definition at line 850 of file spi.c.
ADI_SPI_RESULT_TYPE adi_SPI_SetGenericSettings (ADI_SPI_DEV_HANDLE const hDevice, ADI_SPI_DEV_GENERIC_SETTINGS_TYPE *const pSettings)
Set generic SPI settings.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
[in] pSettings Pointer to caller-configured generic device settings structure.
Returns
Status
ADI_SPI_ERR_BAD_DEV_HANDLE [D] Invalid device handle parameter.
ADI_SPI_ERR_NOT_INITIALIZED [D] Device has not been previously configured for use.
ADI_SPI_ERR_PARAM_OUT_OF_RANGE [D] Invalid or NULL pSettings parameter.
ADI_SPI_SUCCESS Call completed successfully.
Configures various generic device settings and modes in a single call.
See Also
adi_SPI_GetGenericSettings().
Definition at line 645 of file spi.c.
ADI_SPI_RESULT_TYPE adi_SPI_SetHWChipSelect (ADI_SPI_DEV_HANDLE const hDevice, const bool_t bFlag)
Turn HW Chip Select on or off.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
[in] bFlag Enable (true) or disable (false) HW Chip Select
Returns
Status
ADI_SPI_ERR_BAD_DEV_HANDLE [D] Invalid device handle parameter.
ADI_SPI_ERR_NOT_INITIALIZED [D] Device has not been previously configured for use.
ADI_SPI_SUCCESS Call completed successfully.
See Also
adi_SPI_GetChipSelect().
Definition at line 1739 of file spi.c.
ADI_SPI_RESULT_TYPE adi_SPI_SetInterruptMode (ADI_SPI_DEV_HANDLE const hDevice, const ADI_SPI_IRQ_MODE_TYPE Mode)
Set SPI IRQ mode.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
[in] Mode Designating new FIFO interrupt mode, based on their relative fullness or emptiness.
Returns
Status
ADI_SPI_ERR_BAD_DEV_HANDLE [D] Invalid device handle parameter.
ADI_SPI_ERR_NOT_INITIALIZED [D] Device has not been previously configured for use.
ADI_SPI_ERR_PARAM_OUT_OF_RANGE Invalid or NULL Mode parameter.
ADI_SPI_SUCCESS Call completed successfully.
Configures when the SPI FIFOs generate interrupts, based on their relative "fullness". See user manual for mode descriptions.
Note
For DMA Rx transfers (SPI1 only), these bits should be set to '00' (ADI_SPI_IRQMODE_T1R1).
See Also
adi_SPI_GetInterruptMode().
Definition at line 736 of file spi.c.
ADI_SPI_RESULT_TYPE adi_SPI_SetLoopback (ADI_SPI_DEV_HANDLE const hDevice, const bool_t bFlag)
Set the internal loopback mode.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
[in] bFlag Flag to manage internal SPI loopback mode.
true Set internal loopback mode.
false Clear internal loopback mode.
Returns
Status
ADI_SPI_ERR_BAD_DEV_HANDLE [D] Invalid device handle parameter.
ADI_SPI_ERR_NOT_INITIALIZED [D] Device has not been previously configured for use.
ADI_SPI_SUCCESS Call completed successfully.
Set or clear the internal SPI loopback mode. Primairly used for testing.
See Also
adi_SPI_GetLoopback().
Definition at line 1035 of file spi.c.
ADI_SPI_RESULT_TYPE adi_SPI_SetLsbFirst (ADI_SPI_DEV_HANDLE const hDevice, const bool_t bFlag)
Set SPI LSB or MSB first transfer mode.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
[in] bFlag Flag to manage serialization direction of transfer.
true For LSB first.
false For MSB first.
Returns
Status
ADI_SPI_ERR_BAD_DEV_HANDLE [D] Invalid device handle parameter.
ADI_SPI_ERR_NOT_INITIALIZED [D] Device has not been previously configured for use.
ADI_SPI_SUCCESS Call completed successfully.
Configures whether data is transferred as LSB first or MSB first.
See Also
adi_SPI_GetLsbFirst().
Definition at line 1335 of file spi.c.
ADI_SPI_RESULT_TYPE adi_SPI_SetMasterMode (ADI_SPI_DEV_HANDLE const hDevice, const bool_t bFlag)
Set SPI Master-Mode operation.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
[in] bFlag Flag to select either Master-Mode or Slave-Mode operation.
true Enable Master-Mode.
false Enable Slave-Mode.
Returns
Status
ADI_SPI_ERR_BAD_DEV_HANDLE [D] Invalid device handle parameter.
ADI_SPI_ERR_NOT_INITIALIZED [D] Device has not been previously configured for use.
ADI_SPI_SUCCESS Call completed successfully.
Controls SPI Master/Slave mode of operation, set for Master-Mode, clear for Slave-Mode.
See Also
adi_SPI_GetMasterMode().
Definition at line 1599 of file spi.c.
ADI_SPI_RESULT_TYPE adi_SPI_SetMisoOutput (ADI_SPI_DEV_HANDLE const hDevice, const bool_t bFlag)
Set SPI Slave-Mode MISO output enable.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
[in] bFlag Flag to manage Slave-Mode MISO output ebable.
true Enable "normal" opersation (driven output).
false Disable the MISO output driver (open circuit).
Returns
Status
ADI_SPI_ERR_BAD_DEV_HANDLE [D] Invalid device handle parameter.
ADI_SPI_ERR_NOT_INITIALIZED [D] Device has not been previously configured for use.
ADI_SPI_SUCCESS Call completed successfully.
Set or clear this mode to manage the MISO pin output driver enable.
See Also
adi_SPI_GetMisoOutput().
Definition at line 1092 of file spi.c.
ADI_SPI_RESULT_TYPE adi_SPI_SetReceiveOverflow (ADI_SPI_DEV_HANDLE const hDevice, const bool_t bFlag)
Set the SPI receive FIFO overflow mode.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
[in] bFlag Flag to manage recieve FIFO overflow behavior.
true Discard old data on receive FIFO overflow.
false Discard new data on receive FIFO overflow.
Returns
Status
ADI_SPI_ERR_BAD_DEV_HANDLE [D] Invalid device handle parameter.
ADI_SPI_ERR_NOT_INITIALIZED [D] Device has not been previously configured for use.
ADI_SPI_SUCCESS Call completed successfully.
Controls what to do with excess incoming data when the receive FIFO becomes full. Either the new data or the old data is discarded. Set the receive FIFO overflow mode to replace data in the RX register (top of receive FIFO) with the incoming new data. Clear it to discard incoming new data and preserve old undead data.
See Also
adi_SPI_GetReceiveOverflow().
Definition at line 1157 of file spi.c.
ADI_SPI_RESULT_TYPE adi_SPI_SetTransferInitiateMode (ADI_SPI_DEV_HANDLE const hDevice, const bool_t bFlag)
Set SPI transfer initiate and interrupt mode.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
[in] bFlag Flag to manage transfer initiate and interrupt mode.
true Initiate transfers on write to transmit FIFO and interrupt when empty.
false Initiate transfers on read from receive FIFO and interrupt when full.
Returns
Status
ADI_SPI_ERR_BAD_DEV_HANDLE [D] Invalid device handle parameter.
ADI_SPI_ERR_NOT_INITIALIZED [D] Device has not been previously configured for use.
ADI_SPI_SUCCESS Call completed successfully.
Set to initiate transfers on a write to the transmit data register and interrupt when the transmit FIFO is empty. Clear to initiate transfers with a read from the receive data register and interrupt when the receive FIFO is full.
See Also
adi_SPI_GetTransferInitiateMode().
Definition at line 1277 of file spi.c.
ADI_SPI_RESULT_TYPE adi_SPI_SetTransmitUnderflow (ADI_SPI_DEV_HANDLE const hDevice, const bool_t bFlag)
Set the SPI transmit FIFO underflow mode.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
[in] bFlag Flag to manage transmit FIFO underflow behavior.
true Send zeroes on transmit FIFO underflow.
false Resend last data on transmit FIFO underflow.
Returns
Status
ADI_SPI_ERR_BAD_DEV_HANDLE [D] Invalid device handle parameter.
ADI_SPI_ERR_NOT_INITIALIZED [D] Device has not been previously configured for use.
ADI_SPI_SUCCESS Call completed successfully.
Controls what to transmit when lacking valid data because the transmit FIFO is empty. Either zeros or the last valid data are transmitted. Set transmit FIFO underflow mode to send zeros. Clear it to resend the last transmitted data.
See Also
adi_SPI_GetTransmitUnderflow().
Definition at line 1216 of file spi.c.
ADI_SPI_RESULT_TYPE adi_SPI_SetWiredOrMode (ADI_SPI_DEV_HANDLE const hDevice, const bool_t bFlag)
Set the SPI "Wired-OR" output mode.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
[in] bFlag Flag to select output circuit configuration.
true For "wired-or" (open-collector) output mode.
false For "normal" (fully-driven) output levels.
Returns
Status
ADI_SPI_ERR_BAD_DEV_HANDLE [D] Invalid device handle parameter.
ADI_SPI_ERR_NOT_INITIALIZED [D] Device has not been previously configured for use.
ADI_SPI_SUCCESS Call completed successfully.
Controls the output driver configuration. Set to enable an "Open-Collector" output circuit for performing external "Wired-OR" logic, requiring an external pull-up resistor. Clear for normal, fully-driven outputs.
See Also
adi_SPI_GetWiredOrMode().
Definition at line 1394 of file spi.c.
bool_t adi_SPI_SlaveComplete (ADI_SPI_DEV_HANDLE const hDevice)
Get the SPI slave transaction completion status.
Parameters
[in] hDevice Device handle obtained from adi_SPI_SlaveInit().
Returns
Returns the completion state of a previously slave submitted buffer.
true Transaction is complete.
false Transaction is incomplete.
See Also
adi_SPI_Slave_Transmit().
adi_SPI_Slave_Receive().
Definition at line 2560 of file spi.c.
ADI_SPI_RESULT_TYPE adi_SPI_SlaveInit (ADI_SPI_DEV_ID_TYPE const devID, ADI_SPI_DEV_HANDLE *const phDevice)
Initialize and allocate an SPI device for use in Slave Mode.
Parameters
[in] devID Zero-based device index designating which device to initialize.
[out] phDevice The caller's device handle pointer for storing the initialized device instance data.
Returns
Status
ADI_SPI_ERR_ALREADY_INITIALIZED [D] Specified device has already been initialized.
ADI_SPI_ERR_BAD_DEV_ID [D] Invalid device index.
ADI_SPI_ERR_BAD_DMA_CONFIG Internal DMA initializations failed.
ADI_SPI_ERR_BAD_GPIO_CONFIG Internal GPIO initializations failed.
ADI_SPI_ERR_SEMAPHORE_FAILED Semaphore creation failed.
ADI_SPI_SUCCESS Call completed successfully.
No other SPI APIs may be called until the device init function is called.
Initialize an SPI device using internal default configuration settings and allocate the device for use. The caller's device handle is written with the device instance data pointer. The returned device handle is required to be passed to all subsequent calls to convey which device instance to operate on.
Note
The contents of phDevice will be set to NULL upon failure.
See Also
adi_SPI_MasterInit().
adi_SPI_UnInit().
Definition at line 473 of file spi.c.
ADI_SPI_RESULT_TYPE adi_SPI_SlaveTransfer (ADI_SPI_DEV_HANDLE const hDevice, ADI_SPI_TRANSCEIVE_TYPE *const pXfr)
Submit data buffers for SPI Slave-Mode transaction.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
[in] pXfr Pointer to transfer data struct.
Returns
Status
ADI_SPI_ERR_BAD_DEV_HANDLE [D] Invalid device handle parameter.
ADI_SPI_ERR_DMA_ALREADY_IN_USE [D] DMA transaction already underway.
ADI_SPI_ERR_NOT_INITIALIZED [D] Device has not been previously configured for use.
ADI_SPI_ERR_NULL_DATA_POINTER [D] Invalid data pointer detected (NULL).
ADI_SPI_ERR_PARAM_OUT_OF_RANGE [D] Invalid size parameter detected (0).
ADI_SPI_SUCCESS Call completed successfully.
Request a synchronous transmit and receive of multiple data bytes over the SPI serial channel. Honors current blocking and DMA modes. Buffer allocations are made by the calling code (the application).
There are three PROGRAMMING MODELS for using this API. The simpelest is blocking mode, in which the API blocks internally until the transaction is complete. In blocking mode, there is no oppertunity for the application to do background processing, so there will be wasted horseower espicially in the DMA case (where the core has minimal work to do). The other two cases are non-blocking-with-polling and non-blocking-with-callback. In both cases of the non-blocking mode, the application has the oppertunity to perform background processing, but it may never submit additional SPI transactions until the current one is complete. In non-blocking-with-polling mode, the application needs to poll the SPI driver for completion. In non-blocking-with-callback mode, the application need not concern itself with the progress of the current SPI transaction and will know the transaction is complete when it receives the callback.
The transmit buffer is sent and the receive buffer is written according to the size and increment information contained by the pXft transfer data structure parameter.
The ADI_SPI_TRANSCEIVE_TYPE contains all the parameters describing the transfer. There are three main parts to it: a prologue, the transmit data and the receive data. Each part has a size attribute, and each data pointer has an increment flag. Setting the increment flag to false allows a data pointer to remain stationary (see bTxIncrement and bRxIncrement, below).
Note
The prologue buffer cannot be used in Slave mode.
Each call to adi_SPI_SlaveTransfer() must populate the following fields of the ADI_SPI_TRANSCEIVE_TYPE block:
DataSize
The number of data bytes to transfer. DMA mode requires evenly-sized byte counts and buffer allocations due to the underlying SPI hardware that employs 16-bit DMA. All data buffer allocations are made by the application and passed by pointer. The size of the application-allocated transmit and receive data buffers are the same unless one of the increment flags is disabled resulting in a stationary data pointer. If using a stationary data pointer, e.g., a FIFO address, the associated data buffer allocation may be of size one (unless using DMA mode, see above). Blocking-mode calls cause the driver to block on this API until the transaction is complete. Non-blocking calls return right away and require the application to poll on the transfer completion status or register/receive a callback, such that the application may perform other tasks. The application may never submit multiple transactions and must always insure each transaction is complete before submitting any other transactions.
pTxData
Pointer to the application-defined transmit data buffer. This is the data sent out over the SPI transmit wire (MOSI for Master-mode, MISO for Slave-mode) during the SPI transaction. For ADuCM350 SPI DMA mode (which is 16-bit based), the transmit buffer must be 16-bit aligned.
pRxData
Pointer to the application-defined receive data buffer. This is where the receive data will be stored from the SPI receive wire (MISO for Master-mode, MOSI for Slave-mode) during the SPI transaction. For ADuCM350 SPI DMA mode (which is 16-bit based), the receive buffer must be 16-bit aligned.
bTxIncrement
Increment flag for the transmit buffer. If true, the transmit data buffer pointer is advanced as each byte is sent. If false, the transmit data pointer is stationary. A stationary buffer pointer is useful for sending the same data to an external device or if the source data is from a fixed memory address.
bRxIncrement
Increment flag for the receive buffer. If true, the receive data buffer pointer is advanced as each byte is received. If false, the receive data pointer is stationary. A stationary buffer pointer is useful for monitoring commands from an external device or if the receive data is going to a fixed memory address.
See Also
adi_SPI_GetBlockingMode().
adi_SPI_GetDmaMode().
adi_SPI_GetDmaRxComplete().
adi_SPI_GetDmaTxComplete().
adi_SPI_SetBlockingMode().
adi_SPI_SetDmaMode().
adi_SPI_SlaveComplete().
Definition at line 2436 of file spi.c.
ADI_SPI_RESULT_TYPE adi_SPI_UnInit (ADI_SPI_DEV_HANDLE const hDevice)
Uninitialize and deallocate an SPI device.
Parameters
[in] hDevice Device handle obtained from adi_SPI_MasterInit() or adi_SPI_SlaveInit().
Returns
Status
ADI_SPI_ERR_BAD_DEV_HANDLE [D] Invalid device handle parameter.
ADI_SPI_ERR_BAD_DMA_CONFIG Internal DMA operations failed.
ADI_SPI_ERR_BAD_GPIO_CONFIG Internal GPIO operations failed.
ADI_SPI_ERR_NOT_INITIALIZED [D] Device has not been previously configured for use.
ADI_SPI_SUCCESS Call completed successfully.
Uninitialize and release an allocated SPI device for other use.
See Also
adi_SPI_MasterInit().
Definition at line 553 of file spi.c.